import { createWebStyles } from "../web";
import { C, P, RADIUS, SHADOW } from "../tokens";

const orange = C.orange;
const black = C.text;
const body = C.body;
const white = C.white;
const offWhite = C.cream;
const border = C.border;
const muted = C.muted;
const ink = P.dark;
const panel = "#161616";
const panelSoft = "#202020";
const darkBorder = C.borderGreen;
const darkMuted = C.mutedInverse;

export const dashboard = createWebStyles({
  root: { flex: 1, backgroundColor: ink, overscrollBehavior: "none" as any },
  rootApp: { backgroundColor: "#F5F8FA" },
  loadingRoot: { flex: 1, backgroundColor: ink, alignItems: "center", justifyContent: "center", gap: 12 },
  loadingText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: muted },

  topHeader: {
    position: "fixed" as any,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 200,
    height: 60,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(18,18,18,0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: 32,
  },
  topHeaderCompact: { paddingRight: 16 },
  topHeaderMobileWeb: { paddingRight: 0, justifyContent: "center" },
  brandBlock: {
    width: 220,
    height: "100%" as any,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 24,
    borderRightWidth: 1,
    borderRightColor: "rgba(18,18,18,0.08)",
  },
  brandBlockCompact: { width: "auto" as any, paddingHorizontal: 16, borderRightWidth: 0 },
  brandBlockMobileWeb: { position: "absolute" as any, left: 0, top: 0, bottom: 0, zIndex: 2, paddingHorizontal: 14 },
  logoImg: { width: 34, height: 34, borderRadius: 17 },
  logoImgMobileWeb: { width: 30, height: 30, borderRadius: 15 },
  logoText: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 19, fontWeight: "600" as const, color: "#121212" },
  logoTextMobileWeb: { fontSize: 18 },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 16 },
  headerRightMobile: { gap: 8 },
  streakPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F4F4F4",
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  mobileHeaderStreak: {
    position: "fixed" as any,
    left: "50vw" as any,
    right: "auto" as any,
    top: 0,
    bottom: "auto" as any,
    width: "max-content" as any,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    transform: "translateX(-50%)" as any,
    pointerEvents: "none" as any,
    zIndex: 210,
  },
  streakPillMobileWeb: { paddingHorizontal: 12, paddingVertical: 7, backgroundColor: "rgba(255,255,255,0.08)" },
  streakValue: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: "#121212" },
  streakText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: "#6A6A6A" },
  headerEmoji: { fontSize: 14, lineHeight: 18 },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: orange,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarMobileHidden: { display: "none" as any },
  avatarImage: { width: "100%" as any, height: "100%" as any },
  avatarText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "700" as const, color: white },
  dashboardMenuButton: {
    position: "absolute" as any,
    right: 12,
    top: 9,
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 420,
  },
  dashboardMenuButtonActive: { backgroundColor: orange, borderColor: orange },
  dashboardMobileMenu: {
    position: "fixed" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: "100vh" as any,
    backgroundColor: "rgba(8,8,8,0.985)",
    borderWidth: 0,
    borderRadius: 0,
    paddingTop: 84,
    paddingHorizontal: 18,
    paddingBottom: 24,
    gap: 8,
    zIndex: 360,
    backdropFilter: "blur(18px)" as any,
    WebkitBackdropFilter: "blur(18px)" as any,
  },
  dashboardMobileMenuItem: {
    minHeight: 48,
    borderRadius: 11,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dashboardMobileMenuItemActive: { backgroundColor: "rgba(232,93,42,0.12)" },
  dashboardMobileMenuLabel: { flexDirection: "row", alignItems: "center", gap: 11 },
  dashboardMobileMenuText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, fontWeight: "700" as const, color: "rgba(255,255,255,0.78)" },
  dashboardMobileMenuTextActive: { color: orange },
  dashboardMobileMenuDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.08)", marginVertical: 6 },

  body: { flex: 1, flexDirection: "row", paddingTop: 60 },
  bodyDesktop: { paddingTop: 0 },
  bodyCompact: { flexDirection: "column" },
  bodyMobile: { paddingTop: 60, backgroundColor: ink },
  bodyApp: { paddingTop: 0 },
  bodyAppLight: { backgroundColor: "#F5F8FA" },
  sidebar: {
    position: "fixed" as any,
    top: 0,
    left: 0,
    bottom: 0,
    width: 220,
    backgroundColor: "#101010",
    borderRightWidth: 1,
    borderRightColor: darkBorder,
    padding: 12,
    paddingTop: 20,
    zIndex: 100,
  },
  // Logo row at the top of the sidebar (replaces the removed top header bar)
  sidebarLogoRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 10, paddingTop: 4, paddingBottom: 22 },
  sidebarLogoImg: { width: 34, height: 34, borderRadius: 17 },
  sidebarLogoText: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 19, fontWeight: "600" as const, color: "#FFFFFF" },
  sidebarCompact: {
    position: "relative" as any,
    top: "auto" as any,
    left: "auto" as any,
    bottom: "auto" as any,
    width: "100%" as any,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: darkBorder,
  },
  sidebarMobile: { paddingHorizontal: 8 },
  sidebarMain: { flex: 1, gap: 2 },
  sidebarMainCompact: { flexDirection: "row", flex: 0, gap: 6, overflow: "scroll" as any },
  sidebarBottom: { borderTopWidth: 1, borderTopColor: darkBorder, paddingTop: 16, gap: 2 },
  sidebarBottomCompact: { display: "none" as any },
  navItem: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: RADIUS.sm, paddingHorizontal: 14, paddingVertical: 10 },
  navItemActive: { backgroundColor: "rgba(232,93,42,0.14)" },
  navText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: "rgba(255,255,255,0.56)" },
  navTextActive: { color: orange, fontWeight: "600" as const },
  navDot: { marginLeft: "auto" as any, width: 4, height: 4, borderRadius: 2, backgroundColor: orange },

  contentFrame: { flex: 1, marginLeft: 220, backgroundColor: "#FFFFFF", position: "relative" as any, overflow: "hidden", overscrollBehavior: "none" as any },
  contentFrameCompact: { marginLeft: 0 },
  contentFrameMobile: { width: "100%" as any, maxWidth: "100vw" as any, overflow: "hidden" as any },
  contentFrameApp: { marginLeft: 0 },
  contentFrameAppLight: { backgroundColor: "#F5F8FA" },
  footerBounceBlocker: {
    position: "absolute" as any,
    left: 0,
    right: 0,
    bottom: 0,
    height: "36vh" as any,
    minHeight: 220,
    backgroundColor: "#FFFFFF",
    zIndex: 1,
  },
  footerBounceBlockerApp: { backgroundColor: "#F5F8FA", opacity: 0 },
  pageSurface: { position: "relative" as any, overflow: "hidden", backgroundColor: "transparent", overscrollBehavior: "none" as any },
  pageSurfaceFooterPinned: { flex: 1 },
  pageSurfaceApp: { backgroundColor: "#F5F8FA" },
  pageSurfaceContent: { position: "relative" as any, zIndex: 5 },
  dashboardBgLayer: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  dashboardBg: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%" as any,
    height: "100%" as any,
    opacity: 0,
  },
  dashboardBgApp: { opacity: 0 },
  dashboardBgWash: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
  },
  dashboardBgWashApp: { backgroundColor: "#F5F8FA" },
  content: { flex: 1, backgroundColor: "#FFFFFF", zIndex: 2, overscrollBehavior: "none" as any, overscrollBehaviorY: "none" as any, overscrollBehaviorX: "none" as any },
  contentApp: { backgroundColor: "#F5F8FA" },
  contentMobile: { width: "100%" as any, maxWidth: "100vw" as any, overflowX: "hidden" as any },
  contentInner: { width: "100%" as any, backgroundColor: "#FFFFFF" },
  contentInnerCompact: { maxWidth: "none" as any },
  contentInnerMobile: { width: "100%" as any, maxWidth: "100vw" as any, minWidth: 0, overflowX: "hidden" as any, boxSizing: "border-box" as any },
  contentInnerMobileWeb: { paddingBottom: 0 },
  contentInnerApp: { paddingTop: 44, paddingBottom: 118 },
  contentInnerAppPolished: { backgroundColor: "#F5F8FA" },
  contentInnerFooterPinned: { minHeight: "100vh" as any, display: "flex" as any, flexDirection: "column" },
  contentInnerFooterPinnedCompact: { minHeight: "calc(100vh - 60px)" as any },
  pageHeader: {
    backgroundColor: "#121212",
    backgroundImage: "linear-gradient(135deg, #121212 0%, #1B1B1B 54%, #0A0A0A 100%)" as any,
    borderBottomWidth: 1,
    borderBottomColor: darkBorder,
    paddingHorizontal: 32,
    paddingVertical: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pageHeaderApp: {
    marginHorizontal: 14,
    marginTop: 14,
    borderRadius: 24,
    borderBottomWidth: 0,
    borderWidth: 1,
    borderColor: "rgba(20,42,58,0.08)",
    backgroundColor: "#FFFFFF",
    backgroundImage: "none" as any,
    paddingHorizontal: 20,
    paddingVertical: 20,
    boxShadow: "0 18px 38px rgba(31,61,80,0.08)" as any,
  },
  pageHeaderLight: {
    backgroundColor: "#FFFFFF",
    backgroundImage: "none" as any,
    borderBottomWidth: 0,
    borderBottomColor: "transparent",
  },
  pageHeaderMobile: { width: "100%" as any, maxWidth: "100vw" as any, paddingHorizontal: 18, paddingVertical: 18, flexDirection: "column", alignItems: "flex-start", gap: 14, boxSizing: "border-box" as any },
  h1: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 28, fontWeight: "900" as const, color: white, lineHeight: 34 },
  h1Light: { color: "#121212" },
  h1App: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 27, lineHeight: 32, fontWeight: "900" as const, color: "#172A38" },
  headerSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: darkMuted, marginTop: 3 },
  headerSubLight: { color: "#5F5F5F" },
  headerSubApp: { color: "#6A7A86", lineHeight: 20, marginTop: 5 },

  // ── Vault — locked / coming soon ──────────────────────────────────────────
  vaultLockWrap: { flex: 1, alignItems: "center", justifyContent: "center", paddingVertical: 56, paddingHorizontal: 16 },
  vaultLockCard: {
    width: "100%" as any,
    maxWidth: 560,
    alignItems: "center",
    backgroundColor: white,
    borderWidth: 1,
    borderColor: border,
    borderRadius: 28,
    paddingVertical: 56,
    paddingHorizontal: 44,
    boxShadow: "0 24px 60px rgba(0,0,0,0.07)" as any,
  },
  vaultLockCardMobile: { paddingVertical: 40, paddingHorizontal: 24, borderRadius: 22 },
  vaultLockIcon: {
    width: 86, height: 86, borderRadius: 999,
    backgroundColor: "#FEF0EB",
    alignItems: "center", justifyContent: "center",
    marginBottom: 26,
  },
  vaultLockBadge: {
    flexDirection: "row", alignItems: "center", gap: 7,
    backgroundColor: "#FEF0EB",
    borderWidth: 1, borderColor: "rgba(232,93,42,0.28)",
    borderRadius: 999, paddingHorizontal: 14, paddingVertical: 6,
    marginBottom: 20,
  },
  vaultLockBadgeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "700" as const, letterSpacing: 1.6, color: orange, textTransform: "uppercase" as any },
  vaultLockTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 30, fontWeight: "900" as const, color: black, textAlign: "center", marginBottom: 12 },
  vaultLockText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, lineHeight: 24, color: muted, textAlign: "center", maxWidth: 430 },

  // ── Sidebar — locked nav item ─────────────────────────────────────────────
  navItemLocked: { opacity: 0.6 },
  navLockBadge: { marginLeft: "auto" as any, flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "rgba(255,255,255,0.07)", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
  navLockBadgeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, letterSpacing: 0.8, color: "rgba(255,255,255,0.5)", textTransform: "uppercase" as any },

  // ── Dashboard hero card (template redesign) ───────────────────────────────
  heroCard: {
    backgroundColor: white,
    borderWidth: 1, borderColor: "rgba(18,18,18,0.08)",
    borderRadius: 24, padding: 32, marginBottom: 24, marginHorizontal: 32,
    flexDirection: "row", gap: 28, alignItems: "stretch",
    boxShadow: SHADOW.md as any,
  },
  heroCardMobile: { flexDirection: "column", padding: 22, borderRadius: 20, gap: 20, marginHorizontal: 16 },
  heroLeft: { flex: 1, justifyContent: "center" },
  heroGreeting: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 34, fontWeight: "900" as const, color: black, lineHeight: 40, marginBottom: 6 },
  heroGreetingMobile: { fontSize: 26, lineHeight: 32 },
  heroSubtitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: muted, marginBottom: 20, lineHeight: 20 },
  heroPillRow: { flexDirection: "row", flexWrap: "wrap" as any, gap: 10, marginBottom: 24 },
  heroPill: { flexDirection: "row", alignItems: "center", gap: 7, backgroundColor: "#F3F3F3", borderRadius: 999, paddingHorizontal: 14, paddingVertical: 8 },
  heroPillText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: body },
  heroPillAccent: { backgroundColor: "#FEF0EB" },
  heroPillAccentDot: { width: 7, height: 7, borderRadius: 999, backgroundColor: orange },
  heroPillAccentText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, color: orange, letterSpacing: 0.6, textTransform: "uppercase" as any, fontSize: 12, fontWeight: "700" as const },
  heroStartBtn: { flexDirection: "row", alignItems: "center", gap: 9, alignSelf: "flex-start", backgroundColor: orange, borderRadius: 12, paddingHorizontal: 28, paddingVertical: 15, boxShadow: "0 12px 28px rgba(232,93,42,0.32)" as any, cursor: "pointer" as any },
  heroStartText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 16, fontWeight: "700" as const, color: white },

  // Rank sub-card (right side of hero)
  rankCard: { width: 300, backgroundColor: offWhite, borderWidth: 1, borderColor: "rgba(18,18,18,0.07)", borderRadius: 18, paddingHorizontal: 24, paddingVertical: 24, justifyContent: "center" },
  rankCardMobile: { width: "100%" as any },
  rankTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 2 },
  rankLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, letterSpacing: 1.6, color: muted, textTransform: "uppercase" as any },
  rankXp: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "800" as const, color: black },
  rankXpUnit: { color: muted, fontWeight: "600" as const },
  rankName: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 26, fontWeight: "900" as const, color: black, marginBottom: 16 },
  rankToNextRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 12 },
  rankToNextLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "600" as const, letterSpacing: 1.2, color: muted, textTransform: "uppercase" as any },
  rankToNextValue: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "700" as const, color: body },

  // ── System Quests 2×2 grid (template redesign) ────────────────────────────
  questsSection: { marginBottom: 24, paddingHorizontal: 32 },
  questsSectionMobile: { paddingHorizontal: 16 },
  questsSectionHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 16 },
  questsClearedText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: muted },
  questGrid: { flexDirection: "row", flexWrap: "wrap" as any, gap: 18 },
  questGridCard: {
    flexGrow: 1, flexBasis: "calc(50% - 9px)" as any, minWidth: 280,
    backgroundColor: white, borderWidth: 1, borderColor: "rgba(18,18,18,0.08)",
    borderRadius: 18, padding: 22, boxShadow: SHADOW.sm as any,
  },
  questGridCardComplete: { borderColor: "rgba(232,93,42,0.35)", backgroundColor: "#FFF8F5" },
  questCardHead: { flexDirection: "row", alignItems: "flex-start", gap: 12, marginBottom: 12 },
  questCardHeadText: { flex: 1 },
  questCardPtsRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 4, marginBottom: 9 },
  questCardPts: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "700" as const, color: black },
  questCardPctText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: muted },
  questCardFooter: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted, marginTop: 11 },
  startBtn: { backgroundColor: orange, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 12, flexDirection: "row", alignItems: "center", gap: 7 },
  startBtnApp: { backgroundColor: "#0F7EA8", borderRadius: 999, boxShadow: "0 10px 24px rgba(15,126,168,0.22)" as any },
  startBtnMobile: { width: "100%" as any, justifyContent: "center" },
  startBtnText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "600" as const, color: white },

  grid: { display: "grid" as any, gridTemplateColumns: "1fr 340px" as any, gap: 20, alignItems: "stretch" as any, paddingHorizontal: 32, paddingTop: 28, paddingBottom: 28 },
  gridCompact: { display: "flex" as any, gridTemplateColumns: "none" as any, flexDirection: "column", paddingHorizontal: 22, paddingTop: 22 },
  gridMobile: { width: "100%" as any, maxWidth: "100vw" as any, minWidth: 0, paddingHorizontal: 14, paddingTop: 14, paddingBottom: 24, gap: 14, overflow: "hidden" as any, boxSizing: "border-box" as any },
  mainColumn: { gap: 20, minWidth: 0 },
  mainColumnMobile: { width: "100%" as any, maxWidth: "100%" as any, minWidth: 0, gap: 14, overflow: "hidden" as any },
  sideColumn: { gap: 20, minWidth: 0 },
  sideColumnMobile: { width: "100%" as any, maxWidth: "100%" as any, minWidth: 0, gap: 14, overflow: "hidden" as any },
  card: { backgroundColor: white, borderWidth: 1, borderColor: "rgba(18,18,18,0.10)", borderRadius: 14, padding: 24, marginBottom: 20, boxShadow: SHADOW.md as any },
  cardApp: {
    borderColor: "rgba(20,42,58,0.08)",
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any,
  },
  cardMobile: { width: "calc(100vw - 28px)" as any, maxWidth: "calc(100vw - 28px)" as any, minWidth: 0, alignSelf: "stretch", borderRadius: 16, padding: 16, marginBottom: 0, overflow: "hidden" as any, boxSizing: "border-box" as any, boxShadow: "0 8px 24px rgba(18,18,18,0.06)" as any },
  favouritePanel: { height: "100%" as any, minHeight: 380, marginBottom: 0, overflow: "hidden" },
  progressSnapshotPanel: { height: "100%" as any, minHeight: 380, marginBottom: 0 },
  performanceCard: { gridColumn: "1 / -1" as any, marginBottom: 0 },
  performanceCardMobile: { width: "calc(100vw - 28px)" as any, maxWidth: "calc(100vw - 28px)" as any, overflow: "hidden" as any },
  darkCard: { backgroundColor: panel, borderColor: darkBorder, boxShadow: "0 18px 44px rgba(0,0,0,0.18)" as any },
  darkCardApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)", boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any },
  darkCardTitle: { color: white },
  darkCardTitleApp: { color: "#172A38" },
  darkMutedText: { color: darkMuted },
  darkSubPanel: { backgroundColor: panelSoft, borderColor: darkBorder },
  darkSubPanelApp: { backgroundColor: "#F7FBFD", borderColor: "rgba(20,42,58,0.08)" },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16, gap: 16 },
  cardHeaderMobile: { width: "100%" as any, minWidth: 0, alignItems: "flex-start", gap: 10, flexWrap: "wrap" as any },
  cardTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, fontWeight: "600" as const, color: black },
  sectionLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, letterSpacing: 1.2, textTransform: "uppercase" as any, color: muted, marginBottom: 10 },
  sectionLabelApp: { color: "#0F7EA8" },
  contentFadeIn: {},
  questCountPill: {
    borderWidth: 1,
    borderColor: "rgba(232,93,42,0.22)",
    backgroundColor: "rgba(232,93,42,0.08)",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  questCountPillApp: { borderColor: "rgba(15,126,168,0.18)", backgroundColor: "rgba(15,126,168,0.08)" },
  questCountTextApp: { color: "#0F7EA8" },
  questCountText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "800" as const, color: orange, textTransform: "uppercase" as any },
  questRankPanel: {
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.08)",
    backgroundColor: "rgba(18,18,18,0.035)",
    borderRadius: 12,
    padding: 12,
    gap: 9,
    marginBottom: 10,
  },
  questRankPanelApp: { backgroundColor: "#F3FAFD", borderColor: "rgba(15,126,168,0.12)", borderRadius: 18, padding: 14 },
  questRankTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  questRankTopMobile: { alignItems: "flex-start", flexWrap: "wrap" as any },
  questRankLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "900" as const,
    letterSpacing: 1,
    textTransform: "uppercase" as any,
    color: black,
  },
  questRankXp: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "800" as const, color: muted },
  questItem: {
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.08)",
    backgroundColor: "rgba(247,247,247,0.78)",
    borderRadius: 14,
    padding: 15,
    gap: 12,
  },
  questItemApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)", borderRadius: 18 },
  questItemComplete: {
    borderColor: "rgba(232,93,42,0.28)",
    backgroundColor: "rgba(232,93,42,0.07)",
  },
  questHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 13 },
  questHeaderMobile: { gap: 11 },
  questIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: panel,
    flexShrink: 0,
  },
  questIconApp: { backgroundColor: "#EAF7FC" },
  questTextBlock: { flex: 1, minWidth: 0, gap: 5 },
  questMetaRow: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" as any },
  questKicker: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 10,
    fontWeight: "900" as const,
    letterSpacing: 1,
    textTransform: "uppercase" as any,
    color: orange,
  },
  questTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 16, fontWeight: "900" as const, color: black, lineHeight: 20 },
  questTitleMobile: { fontSize: 15, lineHeight: 19 },
  questDescription: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, lineHeight: 17, color: muted },
  questBadge: {
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    backgroundColor: white,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  questBadgeComplete: { borderColor: "rgba(232,93,42,0.22)", backgroundColor: "rgba(232,93,42,0.10)" },
  questBadgeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, color: muted, textTransform: "capitalize" as any },
  questBadgeTextComplete: { color: orange },
  questRight: { alignItems: "flex-end", flexShrink: 0 },
  questRightMobile: { minWidth: 56 },
  questPercent: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 24, fontWeight: "900" as const, color: orange, lineHeight: 27 },
  questPercentComplete: { color: black },
  questPercentLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: muted, textTransform: "uppercase" as any },
  questProgressWrap: { gap: 8 },
  questFooterRow: { flexDirection: "row", justifyContent: "space-between", gap: 12, flexWrap: "wrap" as any },
  questProgressText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "800" as const, color: black },
  questSystemMessage: { flex: 1, minWidth: 190, textAlign: "right", fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, lineHeight: 16, color: muted },
  questNotice: {
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.08)",
    backgroundColor: "rgba(18,18,18,0.03)",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  questNoticeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, lineHeight: 17, color: muted },

  onTrackPill: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "rgba(232,93,42,0.08)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  onTrackPillApp: { backgroundColor: "rgba(15,126,168,0.08)", borderWidth: 1, borderColor: "rgba(15,126,168,0.14)" },
  onTrackTextApp: { color: "#0F7EA8" },
  onTrackText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "600" as const, color: orange },
  progressTrack: { height: 6, backgroundColor: border, borderRadius: 999, overflow: "hidden" },
  progressFill: { height: "100%" as any, borderRadius: 999 },
  progressFillApp: { backgroundColor: "#0F7EA8" },

  donePill: { backgroundColor: "rgba(42,157,143,0.10)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  donePillText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "600" as const, color: "#2A9D8F" },
  listStack: { gap: 10 },
  taskRow: { flexDirection: "row", alignItems: "center", gap: 14, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 12, borderWidth: 1, borderColor: border, backgroundColor: offWhite },
  taskRowApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)", borderRadius: 18, paddingVertical: 14 },
  taskIcon: { width: 38, height: 38, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  taskEmoji: { fontSize: 18, lineHeight: 24 },
  taskContent: { flex: 1 },
  taskTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "600" as const, color: black },
  taskTitleDone: { color: muted, textDecorationLine: "line-through" as const },
  taskDur: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted, marginTop: 2 },
  checkCircle: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: border, alignItems: "center", justifyContent: "center" },

  favRail: { flex: 1, width: "100%" as any, minHeight: 312 },
  favGrid: { flexDirection: "row", gap: 14, paddingRight: 4 },
  favGridMobile: { flexDirection: "row" },
  favCardViewport: { width: 226, height: 312, overflow: "hidden", flexShrink: 0, borderRadius: 17 },
  favGameCard: { transform: [{ scale: 0.78 }], transformOrigin: "top left" as any },
  favItem: { flex: 1, alignItems: "center", gap: 8, backgroundColor: offWhite, borderWidth: 1, borderColor: border, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 14 },
  favItemApp: { backgroundColor: "#F7FBFD", borderColor: "rgba(20,42,58,0.08)", borderRadius: 18 },
  favIcon: { width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  favText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "500" as const, color: body, textAlign: "center" },
  favEmpty: { flex: 1, minHeight: 312, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: offWhite, borderWidth: 1, borderColor: border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 18 },
  favEmptyText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "700" as const, color: muted, textAlign: "center" },

  recommendRow: { flexDirection: "row", alignItems: "center", gap: 14, padding: 14, backgroundColor: offWhite, borderRadius: 12, borderWidth: 1, borderColor: border, marginBottom: 10 },
  recommendRowApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)", borderRadius: 18 },
  recommendDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: orange },
  recommendContent: { flex: 1 },
  recommendTop: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  recommendTopMobile: { flexWrap: "wrap" as any },
  recommendTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "600" as const, color: black },
  recommendSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: muted },

  skillTreeGrid: { position: "absolute" as any, inset: 0, opacity: 0.2, backgroundImage: "linear-gradient(rgba(255,255,255,0.12) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.12) 1px, transparent 1px)" as any, backgroundSize: "44px 44px" as any },
  lessonOverlay: { flex: 1, alignItems: "center", justifyContent: "center", padding: 18 },
  lessonScrim: { position: "absolute" as any, inset: 0, backgroundColor: "rgba(8,8,8,0.62)", backdropFilter: "blur(10px)" as any, WebkitBackdropFilter: "blur(10px)" as any },
  lessonPanel: {
    width: "min(720px, 94vw)" as any,
    maxHeight: "88vh" as any,
    backgroundColor: panel,
    borderWidth: 1,
    borderColor: darkBorder,
    borderRadius: 18,
    overflow: "hidden",
    boxShadow: "0 28px 90px rgba(0,0,0,0.44)" as any,
  },
  lessonHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 14, paddingHorizontal: 22, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: darkBorder, backgroundColor: "#101010" },
  lessonTitleGroup: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 },
  lessonIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: "#5B5BD6", alignItems: "center", justifyContent: "center" },
  lessonEyebrow: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "900" as const, letterSpacing: 1.1, color: orange, textTransform: "uppercase" as any },
  lessonTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 30, fontWeight: "700" as const, color: white, lineHeight: 33 },
  lessonClose: { width: 36, height: 36, borderRadius: 12, borderWidth: 1, borderColor: darkBorder, alignItems: "center", justifyContent: "center", backgroundColor: panelSoft },
  lessonScroll: { maxHeight: "62vh" as any },
  lessonScrollContent: { paddingHorizontal: 22, paddingVertical: 18, gap: 14 },
  lessonPromise: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 16, fontWeight: "800" as const, color: white, lineHeight: 23 },
  lessonBlock: { borderWidth: 1, borderColor: darkBorder, backgroundColor: panelSoft, borderRadius: 14, padding: 14 },
  lessonTryBlock: { backgroundColor: "rgba(232,93,42,0.10)", borderColor: "rgba(232,93,42,0.28)" },
  lessonBlockTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "900" as const, letterSpacing: 1.0, textTransform: "uppercase" as any, color: orange, marginBottom: 6 },
  lessonBody: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, lineHeight: 22, color: darkMuted },
  lessonActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, paddingHorizontal: 22, paddingVertical: 16, borderTopWidth: 1, borderTopColor: darkBorder, backgroundColor: "#101010" },
  lessonSecondaryBtn: { borderWidth: 1, borderColor: darkBorder, backgroundColor: panelSoft, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 11 },
  lessonSecondaryText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "800" as const, color: white },
  lessonPrimaryBtn: { backgroundColor: orange, borderRadius: 10, paddingHorizontal: 18, paddingVertical: 11 },
  lessonPrimaryText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "900" as const, color: white },
  statGrid: { display: "grid" as any, gridTemplateColumns: "1fr 1fr 1fr" as any, gap: 12, marginBottom: 20 },
  statGridMobile: { width: "100%" as any, gridTemplateColumns: "repeat(3, minmax(0, 1fr))" as any, gap: 8 },
  statMini: { backgroundColor: panelSoft, borderWidth: 1, borderColor: darkBorder, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 14, alignItems: "center" },
  statMiniMobile: { width: "100%" as any, minWidth: 0, paddingHorizontal: 6, boxSizing: "border-box" as any },
  statEmoji: { fontSize: 16, lineHeight: 22 },
  statMiniValue: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 21, fontWeight: "700" as const, color: white, marginTop: 6 },
  statMiniLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, color: darkMuted, marginTop: 2, textAlign: "center" },
  chartLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted, marginBottom: 10 },
  chartLabelTrend: { marginTop: 18, marginBottom: 18 },
  graphSelector: { marginBottom: 12 },
  graphSelectorMobile: { width: "100%" as any, maxWidth: "100%" as any, overflowX: "auto" as any, overflowY: "hidden" as any },
  graphSelectorContent: { gap: 8, paddingRight: 6 },
  graphSelectorContentMobile: { paddingRight: 6 },
  graphSelectorBtn: { borderWidth: 1, borderColor: darkBorder, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7, backgroundColor: "rgba(255,255,255,0.04)" },
  graphSelectorBtnActive: { backgroundColor: "rgba(232,93,42,0.16)", borderColor: orange },
  graphSelectorText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: darkMuted },
  graphSelectorTextActive: { color: white },
  timeScaleRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 6, flexWrap: "wrap" as any },
  timeScaleRowMobile: { width: "100%" as any, minWidth: 0 },
  timeScaleBtn: { borderWidth: 1, borderColor: darkBorder, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: "rgba(255,255,255,0.04)" },
  timeScaleBtnActive: { backgroundColor: orange, borderColor: orange },
  timeScaleText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "800" as const, color: darkMuted },
  timeScaleTextActive: { color: white },
  graphZoomHint: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: darkMuted, marginLeft: 4 },
  graphZoomHintActive: { color: orange },
  chart: { flexDirection: "row", alignItems: "flex-end", gap: 5, height: 62 },
  chartColumn: { flex: 1, alignItems: "center", gap: 4, height: "100%" as any, justifyContent: "flex-end" },
  chartBar: { width: "100%" as any, minHeight: 4, borderRadius: 4, opacity: 0.95 },
  chartDay: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, color: muted },
  chartDayActive: { color: orange, fontWeight: "600" as const },
  trainingMiniPlay: { width: 36, height: 36, borderRadius: 12, backgroundColor: orange, alignItems: "center", justifyContent: "center" },
  trainingMiniPlayApp: { backgroundColor: "#0F7EA8", borderRadius: 18 },
  trainingMiniCard: { borderWidth: 1, borderColor: darkBorder, borderRadius: 12, backgroundColor: panelSoft, paddingHorizontal: 14, paddingVertical: 13, marginBottom: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  trainingMiniCardApp: { backgroundColor: "#F7FBFD", borderColor: "rgba(20,42,58,0.08)", borderRadius: 18 },
  trainingMiniCardMobile: { width: "100%" as any, maxWidth: "100%" as any, minWidth: 0, boxSizing: "border-box" as any },
  trainingMiniCopyMobile: { flex: 1, minWidth: 0 },
  trainingMiniLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, letterSpacing: 1.1, textTransform: "uppercase" as any, color: orange, marginBottom: 4 },
  trainingMiniLabelApp: { color: "#0F7EA8" },
  trainingMiniTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, fontWeight: "800" as const, color: white },
  trainingMiniTitleApp: { color: "#172A38" },
  trainingMiniSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, lineHeight: 16, color: darkMuted, marginTop: 3 },
  trainingMiniSubApp: { color: "#6A7A86" },
  trainingMiniPct: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 18, fontWeight: "800" as const, color: orange },
  trainingMiniPctApp: { color: "#0F7EA8" },
  trainingMiniPctMobile: { flexShrink: 0, textAlign: "right" },
  graphDetailTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 4 },
  graphDetailTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "800" as const, color: white },
  graphDetailDate: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: orange },
  graphDetailText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, lineHeight: 17, color: darkMuted },
  performanceScorePill: { alignItems: "flex-end", borderWidth: 1, borderColor: "rgba(232,93,42,0.30)", backgroundColor: "rgba(232,93,42,0.12)", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 9 },
  performanceScorePillMobile: { alignItems: "flex-start", paddingHorizontal: 12, paddingVertical: 8 },
  performanceScore: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 20, fontWeight: "800" as const, color: orange },
  performanceScoreLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: darkMuted, textTransform: "uppercase" as any },
  graphChartScroll: { marginTop: 14 },
  graphChartScrollMobile: { width: "100%" as any, maxWidth: "100%" as any, overflowX: "auto" as any, overflowY: "hidden" as any },
  graphChartScrollContent: { paddingBottom: 2 },
  graphChartScrollContentMobile: { paddingBottom: 2 },
  graphLineChart: { position: "relative" as any, width: 1120, height: 340, overflow: "hidden", borderWidth: 1, borderColor: darkBorder, borderRadius: 14, backgroundColor: "#111111", transition: "border-color 180ms ease, background-color 180ms ease" as any },
  graphLineChartMobile: { height: 300, borderRadius: 12 },
  graphLineChartSelected: { borderColor: orange, boxShadow: "0 0 0 3px rgba(232,93,42,0.18), 0 22px 52px rgba(0,0,0,0.22)" as any },
  graphLineGrid: { position: "absolute" as any, inset: 0, opacity: 0.35, backgroundImage: "linear-gradient(rgba(255,255,255,0.10) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.08) 1px, transparent 1px)" as any, backgroundSize: "100% 25%, 12.5% 100%" as any },
  graphTodayMarker: { position: "absolute" as any, top: 42, bottom: 52, width: 1, backgroundColor: "rgba(255,255,255,0.22)" },
  graphTodayLabel: { position: "absolute" as any, top: 14, width: 58, marginLeft: 10, textAlign: "left", fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, color: orange, textTransform: "uppercase" as any },
  graphTodayLabelMobile: { top: 10, marginLeft: 4, fontSize: 9 },
  graphLineSegment: { position: "absolute" as any, height: 3, borderRadius: 999, backgroundColor: orange, transformOrigin: "left center" as any, boxShadow: "0 0 18px rgba(232,93,42,0.28)" as any, zIndex: 2, transition: "left 220ms ease, top 220ms ease, width 220ms ease, transform 220ms ease" as any },
  graphLinePoint: { position: "absolute" as any, width: 30, height: 30, marginLeft: -15, marginTop: -15, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: panelSoft, borderWidth: 2, borderColor: orange, zIndex: 3, transition: "left 220ms ease, top 220ms ease, background-color 160ms ease, box-shadow 160ms ease" as any },
  graphLinePointActive: { backgroundColor: orange, boxShadow: "0 0 0 6px rgba(232,93,42,0.18)" as any },
  graphLinePointText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, color: white },
  graphAxisLabel: { position: "absolute" as any, bottom: 18, width: 74, marginLeft: -37, textAlign: "center", fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: darkMuted },
  graphAxisLabelMobile: { bottom: 10, width: 54, marginLeft: -27, fontSize: 9, lineHeight: 12, overflow: "hidden" },
  graphEmptyState: { position: "absolute" as any, inset: 0, alignItems: "center", justifyContent: "center", gap: 6, paddingHorizontal: 24 },
  graphEmptyTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, fontWeight: "800" as const, color: white },
  graphDetailPanelWide: { marginTop: 14, borderWidth: 1, borderColor: darkBorder, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.04)", paddingHorizontal: 14, paddingVertical: 12 },
  graphDetailPanelWideMobile: { width: "100%" as any, maxWidth: "100%" as any, minWidth: 0, boxSizing: "border-box" as any },
  performanceStatsRow: { flexDirection: "row", alignItems: "center", gap: 14, flexWrap: "wrap" as any },
  weekStrip: { flexDirection: "row", gap: 8, marginBottom: 18 },
  weekDay: { flex: 1, alignItems: "center", gap: 6 },
  weekDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: panelSoft,
    borderWidth: 1,
    borderColor: darkBorder,
  },
  weekDotActive: { backgroundColor: orange, borderColor: orange },
  weekDotToday: { boxShadow: "0 0 0 3px rgba(232,93,42,0.20)" as any },
  weekLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: darkMuted },
  weekLabelToday: { color: orange },

  techniqueRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, backgroundColor: offWhite, borderWidth: 1, borderColor: border },
  techniqueRowMobile: { width: "100%" as any, maxWidth: "100%" as any, minWidth: 0, boxSizing: "border-box" as any },
  techniqueLocked: { opacity: 0.62, backgroundColor: "#FAFAFA", borderColor: "#EFEFEF" },
  techniqueIcon: { width: 28, height: 28, borderRadius: 8, backgroundColor: "rgba(232,93,42,0.10)", alignItems: "center", justifyContent: "center" },
  techniqueIconLocked: { backgroundColor: border },
  techniqueText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "500" as const, color: white },
  techniqueTextApp: { color: "#172A38", fontWeight: "800" as const },
  techniqueTextMobile: { minWidth: 0, flexShrink: 1 },
  techniqueTextLocked: { color: muted, fontWeight: "400" as const },
  vaultPreviewCompleted: { borderColor: "rgba(91,91,214,0.36)", backgroundColor: "rgba(91,91,214,0.12)" },
  vaultPreviewIconCompleted: { backgroundColor: "#5B5BD6" },
  vaultPreviewTextBlock: { flex: 1, gap: 2 },
  vaultPreviewTextBlockMobile: { minWidth: 0 },
  vaultPreviewStatus: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, color: darkMuted, textTransform: "uppercase" as any },
  vaultPreviewStatusDone: { color: "#9F9FFF" },
  segment: { flexDirection: "row", backgroundColor: panelSoft, borderWidth: 1, borderColor: darkBorder, borderRadius: 8, padding: 2, gap: 2 },
  segmentMobile: { flexShrink: 0 },
  segmentText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: darkMuted },
  segmentTextActive: { color: white, fontWeight: "600" as const },
  leaderRow: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: offWhite, borderRadius: 12, borderWidth: 1, borderColor: border, paddingHorizontal: 14, paddingVertical: 11 },
  leaderRowMobile: { width: "100%" as any, maxWidth: "100%" as any, minWidth: 0, gap: 8, paddingHorizontal: 10, boxSizing: "border-box" as any },
  leaderRowYou: { backgroundColor: "rgba(232,93,42,0.04)", borderColor: "rgba(232,93,42,0.24)" },
  rankBadge: { width: 26, height: 26, borderRadius: 13, backgroundColor: border, alignItems: "center", justifyContent: "center" },
  rankGold: { backgroundColor: "#FFD700" },
  rankSilver: { backgroundColor: "#C0C0C0" },
  rankBronze: { backgroundColor: "#CD7F32" },
  rankText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: white },
  leaderIdentity: { flex: 1, minWidth: 0, gap: 2 },
  leaderName: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: white },
  leaderNameMobile: { minWidth: 0, flexShrink: 1 },
  leaderNameYou: { color: orange, fontWeight: "600" as const },
  leaderLevel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, color: darkMuted, textTransform: "uppercase" as any },
  leaderXp: { flexDirection: "row", alignItems: "center", gap: 4 },
  leaderXpMobile: { flexShrink: 0 },
  leaderEmoji: { fontSize: 12, lineHeight: 16 },
  leaderXpText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: white },
  leaderXpLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, color: muted },
  leaderOpenPill: { flexDirection: "row", alignItems: "center", gap: 4, borderWidth: 1, borderColor: "rgba(232,93,42,0.28)", backgroundColor: "rgba(232,93,42,0.10)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  leaderOpenText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "800" as const, color: orange },
  modalRoot: {
    position: "fixed" as any,
    inset: 0,
    zIndex: 500,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalScrim: {
    position: "absolute" as any,
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.64)",
    backdropFilter: "blur(10px)" as any,
    WebkitBackdropFilter: "blur(10px)" as any,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 18,
    marginBottom: 18,
  },
  modalTitle: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "700" as const,
    color: white,
  },
  modalClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: offWhite,
    borderWidth: 1,
    borderColor: border,
    flexShrink: 0,
  },
  leaderboardModalCard: { width: "min(92vw, 620px)" as any, maxHeight: "78vh" as any, overflow: "hidden", backgroundColor: panel, borderRadius: 20, padding: 24, borderWidth: 1, borderColor: darkBorder, boxShadow: "0 24px 70px rgba(0,0,0,0.34)" as any },
  leaderboardModalCardMobile: { width: "calc(100vw - 28px)" as any, maxHeight: "78vh" as any, padding: 18, borderRadius: 18, boxSizing: "border-box" as any },
  leaderboardModalTitle: { color: white },
  leaderboardModalSub: { marginTop: 4, maxWidth: 410, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, lineHeight: 17, color: darkMuted },
  leaderboardModalList: { maxHeight: "58vh" as any },
  leaderboardModalListContent: { gap: 10, paddingBottom: 4 },

  mobileBottomNav: {
    position: "fixed" as any,
    left: 12,
    right: 12,
    bottom: "max(14px, env(safe-area-inset-bottom))" as any,
    zIndex: 260,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 3,
    backgroundColor: "rgba(12,12,12,0.96)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    borderRadius: 28,
    paddingHorizontal: 7,
    paddingTop: 7,
    paddingBottom: 8,
    boxShadow: "0 18px 46px rgba(0,0,0,0.36)" as any,
    backdropFilter: "blur(18px)" as any,
    WebkitBackdropFilter: "blur(18px)" as any,
  },
  mobileBottomNavNative: {
    position: "absolute" as any,
    bottom: 14,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderColor: "rgba(20,42,58,0.10)",
    boxShadow: "0 18px 42px rgba(31,61,80,0.18)" as any,
  },
  mobileTab: {
    flex: 1,
    minHeight: 58,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    paddingVertical: 5,
  },
  mobileTabCenter: {
    flex: 1.12,
    minHeight: 68,
    marginTop: -10,
  },
  mobileTabActive: {
    backgroundColor: "rgba(232,93,42,0.08)",
  },
  mobileTabActiveApp: { backgroundColor: "rgba(15,126,168,0.08)" },
  mobileTabIconShell: {
    width: 34,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "transparent",
  },
  mobileTabIconShellActive: {
    backgroundColor: "rgba(232,93,42,0.18)",
    borderColor: "rgba(232,93,42,0.38)",
  },
  mobileTabIconShellActiveApp: {
    backgroundColor: "rgba(15,126,168,0.14)",
    borderColor: "rgba(15,126,168,0.30)",
  },
  mobileTabIconShellCenter: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#171717",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    boxShadow: "0 12px 28px rgba(0,0,0,0.28)" as any,
  },
  mobileTabIconShellCenterActive: {
    backgroundColor: orange,
    borderColor: "rgba(255,255,255,0.18)",
    boxShadow: "0 14px 34px rgba(232,93,42,0.28)" as any,
  },
  mobileTabIconShellCenterActiveApp: {
    backgroundColor: "#0F7EA8",
    boxShadow: "0 14px 34px rgba(15,126,168,0.24)" as any,
  },
  mobileTabText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 9.5,
    fontWeight: "800" as const,
    color: "rgba(255,255,255,0.50)",
  },
  mobileTabTextApp: { color: "#7A8A95" },
  mobileTabTextActive: { color: white },
  mobileTabTextActiveApp: { color: "#172A38" },

  vaultSkillPage: { paddingHorizontal: 32, paddingTop: 28, paddingBottom: 48, gap: 18 },
  vaultSkillPageApp: { backgroundColor: "#F5F8FA" },
  vaultSkillPageMobile: { paddingHorizontal: 14, paddingTop: 16, paddingBottom: 28, gap: 14 },
  vaultSkillIntro: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
    backgroundColor: panel,
    borderWidth: 1,
    borderColor: darkBorder,
    borderRadius: 18,
    padding: 22,
    boxShadow: "0 18px 44px rgba(0,0,0,0.18)" as any,
  },
  vaultSkillIntroApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)", borderRadius: 24, boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any },
  vaultSkillIntroMobile: { flexDirection: "column", alignItems: "stretch", padding: 18 },
  vaultSkillEyebrow: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "900" as const,
    letterSpacing: 1,
    color: orange,
    textTransform: "uppercase" as any,
  },
  vaultSkillEyebrowApp: { color: "#0F7EA8" },
  vaultSkillTitle: { marginTop: 6, fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 34, lineHeight: 38, fontWeight: "700" as const, color: white },
  vaultSkillTitleApp: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontWeight: "900" as const, color: "#172A38" },
  vaultSkillIntroText: { marginTop: 6, maxWidth: 720, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, lineHeight: 22, color: darkMuted },
  vaultSkillIntroTextApp: { color: "#607482" },
  vaultSkillLegend: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" as any },
  vaultSkillLegendItem: { flexDirection: "row", alignItems: "center", gap: 7, borderWidth: 1, borderColor: darkBorder, backgroundColor: panelSoft, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 },
  vaultSkillLegendDot: { width: 10, height: 10, borderRadius: 5 },
  vaultSkillLegendText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "800" as const, color: darkMuted },
  vaultDomainTabs: { gap: 10, paddingRight: 8 },
  vaultDomainTab: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: darkBorder,
    backgroundColor: panel,
    borderRadius: 999,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  vaultDomainTabApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)" },
  vaultDomainTabActive: {
    backgroundColor: "rgba(232,93,42,0.16)",
    borderColor: orange,
    boxShadow: "0 0 0 3px rgba(232,93,42,0.10)" as any,
  },
  vaultDomainTabText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "900" as const, color: darkMuted },
  vaultDomainTabTextApp: { color: "#6A7A86" },
  vaultDomainTabTextActive: { color: white },
  vaultSkillTreeStage: {
    position: "relative" as any,
    overflow: "hidden",
    backgroundColor: "#101010",
    borderWidth: 1,
    borderColor: darkBorder,
    borderRadius: 18,
    paddingHorizontal: 30,
    paddingVertical: 34,
    gap: 28,
    boxShadow: "0 24px 70px rgba(18,18,18,0.24)" as any,
  },
  vaultSkillTreeStageApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)", boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any },
  vaultSkillTreeStageMobile: { paddingHorizontal: 14, paddingVertical: 24, gap: 22 },
  vaultSkillCenterLine: {
    position: "absolute" as any,
    top: 74,
    bottom: 74,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  vaultSkillCenterLineStroke: {
    width: 3,
    height: "100%" as any,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  vaultSkillCenterLineMobile: {},
  vaultSkillForkLine: {
    position: "absolute" as any,
    top: 316,
    left: "24%" as any,
    right: "24%" as any,
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  vaultSkillRootRow: { position: "relative" as any, zIndex: 2, alignItems: "center" },
  vaultSkillFoundationRow: {
    position: "relative" as any,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 22,
    flexWrap: "wrap" as any,
  },
  vaultSkillFoundationRowMobile: { gap: 14 },
  vaultSkillSplitRow: {
    position: "relative" as any,
    zIndex: 2,
    flexDirection: "row",
    justifyContent: "center",
    gap: 42,
    alignItems: "flex-start",
  },
  vaultSkillSplitRowMobile: {
    gap: 12,
    justifyContent: "space-between",
  },
  vaultSkillBranchColumn: { flex: 1, minWidth: 0, alignItems: "center", gap: 24 },
  vaultSkillBranchColumnMobile: { gap: 18 },
  vaultSkillMergeRow: { position: "relative" as any, zIndex: 2, alignItems: "center", paddingTop: 8 },
  vaultSkillNodeWrap: { width: 150, alignItems: "center", gap: 7 },
  vaultSkillNodeWrapCompact: { width: 132 },
  vaultSkillCircle: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: panelSoft,
    boxShadow: "0 16px 36px rgba(0,0,0,0.28)" as any,
    transition: "transform 180ms ease, box-shadow 180ms ease, border-color 180ms ease" as any,
  },
  vaultSkillNodeRoot: { backgroundColor: orange, borderColor: "rgba(255,255,255,0.36)", boxShadow: "0 0 0 6px rgba(232,93,42,0.14), 0 18px 42px rgba(0,0,0,0.30)" as any },
  vaultSkillNodeFoundation: { backgroundColor: panelSoft, borderColor: "rgba(232,93,42,0.48)" },
  vaultSkillNodeBranch: { backgroundColor: "#121212", borderColor: "rgba(232,93,42,0.64)" },
  vaultSkillNodeTechnique: { backgroundColor: "#2A2A2A", borderColor: "rgba(255,255,255,0.22)" },
  vaultSkillNodeSystem: { backgroundColor: "#1A1A1A", borderColor: "rgba(255,255,255,0.18)" },
  vaultSkillNodeMerge: { backgroundColor: orange, borderColor: "rgba(255,255,255,0.30)", boxShadow: "0 0 0 6px rgba(232,93,42,0.13), 0 18px 42px rgba(0,0,0,0.30)" as any },
  vaultSkillNodeTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, lineHeight: 17, fontWeight: "900" as const, color: white, textAlign: "center" },
  vaultSkillNodeTitleApp: { color: "#172A38" },
  vaultSkillNodeTitleCompact: { fontSize: 12, lineHeight: 16 },
  vaultSkillNodeSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, lineHeight: 14, fontWeight: "800" as const, color: darkMuted, textAlign: "center", textTransform: "uppercase" as any },
  vaultSkillNodeSubApp: { color: "#7A8A95" },
  vaultLessonPanelMobile: { width: "94vw" as any, maxHeight: "86vh" as any },
  vaultLessonTitleCopy: { flex: 1, minWidth: 0 },
  vaultLessonMetaGrid: { display: "grid" as any, gridTemplateColumns: "repeat(2, minmax(0, 1fr))" as any, gap: 12 },

});
