import { createWebStyles } from "../web";
import { C, P, RADIUS, SHADOW } from "../tokens";

const orange = C.orange;
const orangeLight = C.orangeLight;
const black = C.text;
const body = C.body;
const white = C.white;
const offWhite = C.cream;
const border = C.border;
const muted = C.muted;
const ink = P.dark;
const panel = "#161616";
const panelSoft = "#202020";
const darkBorder = C.borderGreen;
const darkMuted = C.mutedInverse;

export const dashboard = createWebStyles({
  root: { flex: 1, backgroundColor: ink },
  loadingRoot: { flex: 1, backgroundColor: ink, alignItems: "center", justifyContent: "center", gap: 12 },
  loadingText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: muted },

  topHeader: {
    position: "fixed" as any,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 200,
    height: 60,
    backgroundColor: "rgba(8,8,8,0.96)",
    backdropFilter: "blur(18px)" as any,
    WebkitBackdropFilter: "blur(18px)" as any,
    borderBottomWidth: 1,
    borderBottomColor: darkBorder,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: 32,
  },
  topHeaderCompact: { paddingRight: 16 },
  brandBlock: {
    width: 220,
    height: "100%" as any,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 24,
    borderRightWidth: 1,
    borderRightColor: darkBorder,
  },
  brandBlockCompact: { width: "auto" as any, paddingHorizontal: 16, borderRightWidth: 0 },
  logoImg: { width: 34, height: 34, borderRadius: 17 },
  logoText: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 19, fontWeight: "600" as const, color: white },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 16 },
  headerRightMobile: { gap: 8 },
  headerIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: darkBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  streakPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: darkBorder,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  streakValue: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: white },
  streakText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: darkMuted },
  headerEmoji: { fontSize: 14, lineHeight: 18 },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: orange,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: { width: "100%" as any, height: "100%" as any },
  avatarText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "700" as const, color: white },

  body: { flex: 1, flexDirection: "row", paddingTop: 60 },
  bodyCompact: { flexDirection: "column" },
  sidebar: {
    position: "fixed" as any,
    top: 60,
    left: 0,
    bottom: 0,
    width: 220,
    backgroundColor: "#101010",
    borderRightWidth: 1,
    borderRightColor: darkBorder,
    padding: 12,
    paddingTop: 20,
    zIndex: 100,
  },
  sidebarCompact: {
    position: "relative" as any,
    top: "auto" as any,
    left: "auto" as any,
    bottom: "auto" as any,
    width: "100%" as any,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: darkBorder,
  },
  sidebarMobile: { paddingHorizontal: 8 },
  sidebarMain: { flex: 1, gap: 2 },
  sidebarMainCompact: { flexDirection: "row", flex: 0, gap: 6, overflow: "scroll" as any },
  sidebarBottom: { borderTopWidth: 1, borderTopColor: darkBorder, paddingTop: 16, gap: 2 },
  sidebarBottomCompact: { display: "none" as any },
  navItem: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: RADIUS.sm, paddingHorizontal: 14, paddingVertical: 10 },
  navItemActive: { backgroundColor: "rgba(232,93,42,0.14)" },
  navEmoji: { width: 20, fontSize: 16, lineHeight: 20, opacity: 0.72, textAlign: "center" },
  navEmojiActive: { opacity: 1 },
  navText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: "rgba(255,255,255,0.56)" },
  navTextActive: { color: orange, fontWeight: "600" as const },
  navDot: { marginLeft: "auto" as any, width: 4, height: 4, borderRadius: 2, backgroundColor: orange },

  contentFrame: { flex: 1, marginLeft: 220, backgroundColor: "#F7F1E8", position: "relative" as any, overflow: "hidden" },
  contentFrameBeige: { backgroundColor: "#F3EDE1" },
  contentFrameCompact: { marginLeft: 0 },
  dashboardBg: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%" as any,
    height: "100%" as any,
    opacity: 0.42,
    zIndex: 0,
  },
  dashboardBgWash: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255,250,242,0.52)",
    zIndex: 1,
  },
  content: { flex: 1, backgroundColor: "transparent", zIndex: 2 },
  contentInner: { width: "100%" as any },
  contentInnerCompact: { maxWidth: "none" as any },
  pageHeader: {
    backgroundColor: "#121212",
    backgroundImage: "linear-gradient(135deg, #121212 0%, #1B1B1B 54%, #0A0A0A 100%)" as any,
    borderBottomWidth: 1,
    borderBottomColor: darkBorder,
    paddingHorizontal: 32,
    paddingVertical: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pageHeaderMobile: { paddingHorizontal: 18, paddingVertical: 18, flexDirection: "column", alignItems: "flex-start", gap: 14 },
  h1: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 30, fontWeight: "600" as const, color: white, lineHeight: 34 },
  headerSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: darkMuted, marginTop: 3 },
  startBtn: { backgroundColor: orange, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 12, flexDirection: "row", alignItems: "center", gap: 7 },
  startBtnText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "600" as const, color: white },

  grid: { display: "grid" as any, gridTemplateColumns: "1fr 340px" as any, gap: 20, alignItems: "start" as any, paddingHorizontal: 32, paddingTop: 28, paddingBottom: 48 },
  gridCompact: { display: "flex" as any, gridTemplateColumns: "none" as any, flexDirection: "column", paddingHorizontal: 22, paddingTop: 22 },
  gridMobile: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 32 },
  mainColumn: { gap: 20 },
  sideColumn: { gap: 20 },
  card: { backgroundColor: white, borderWidth: 1, borderColor: "rgba(18,18,18,0.10)", borderRadius: 14, padding: 24, marginBottom: 20, boxShadow: SHADOW.md as any },
  performanceCard: { gridColumn: "1 / -1" as any, marginBottom: 0 },
  darkCard: { backgroundColor: panel, borderColor: darkBorder, boxShadow: "0 18px 44px rgba(0,0,0,0.18)" as any },
  darkCardTitle: { color: white },
  darkMutedText: { color: darkMuted },
  darkSubPanel: { backgroundColor: panelSoft, borderColor: darkBorder },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16, gap: 16 },
  cardTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, fontWeight: "600" as const, color: black },
  sectionLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, letterSpacing: 1.2, textTransform: "uppercase" as any, color: muted, marginBottom: 10 },

  goalHeader: { flexDirection: "row", justifyContent: "space-between", gap: 24, marginBottom: 20 },
  goalItem: { borderWidth: 1, borderColor: "rgba(18,18,18,0.08)", backgroundColor: "rgba(247,247,247,0.72)", borderRadius: 14, padding: 16 },
  goalEmoji: { width: 46, height: 46, borderRadius: 14, alignItems: "center", justifyContent: "center", flexShrink: 0 },
  goalEmojiText: { fontSize: 22, lineHeight: 28 },
  goalTextBlock: { flex: 1 },
  goalTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 30, fontWeight: "600" as const, color: black, lineHeight: 34 },
  goalTitleEm: { color: orange, fontStyle: "italic" as const },
  goalMeta: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 8, flexWrap: "wrap" as any },
  goalMetaText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: muted },
  boldText: { color: black, fontWeight: "600" as const },
  onTrackPill: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "rgba(232,93,42,0.08)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  onTrackText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "600" as const, color: orange },
  goalRight: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  goalPercent: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 42, fontWeight: "700" as const, color: orange, lineHeight: 42, textAlign: "right" },
  goalPercentLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted, textAlign: "right" },
  gearBtn: { width: 34, height: 34, borderRadius: 8, backgroundColor: offWhite, borderWidth: 1, borderColor: border, alignItems: "center", justifyContent: "center" },
  goalProgressWrap: { gap: 8 },
  milestoneRow: { flexDirection: "row", justifyContent: "space-between" },
  milestoneText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, color: muted },
  milestoneTextActive: { color: orange, fontWeight: "600" as const },

  progressTrack: { height: 6, backgroundColor: border, borderRadius: 999, overflow: "hidden" },
  progressFill: { height: "100%" as any, borderRadius: 999 },

  quickStart: { backgroundColor: orange, backgroundImage: "linear-gradient(135deg, #121212 0%, #242424 58%, #E85D2A 160%)" as any, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", borderRadius: 14, padding: 28, marginBottom: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between", boxShadow: "0 14px 38px rgba(18,18,18,0.22)" as any },
  quickLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "600" as const, color: "rgba(255,255,255,0.68)", letterSpacing: 1.0, textTransform: "uppercase" as any, marginBottom: 8 },
  quickTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 30, fontWeight: "600" as const, color: white, marginBottom: 4 },
  quickSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: "rgba(255,255,255,0.70)" },
  quickIcon: { width: 56, height: 56, borderRadius: 28, backgroundColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },

  donePill: { backgroundColor: "rgba(42,157,143,0.10)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  donePillText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "600" as const, color: "#2A9D8F" },
  listStack: { gap: 10 },
  taskRow: { flexDirection: "row", alignItems: "center", gap: 14, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 12, borderWidth: 1, borderColor: border, backgroundColor: offWhite },
  taskIcon: { width: 38, height: 38, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  taskEmoji: { fontSize: 18, lineHeight: 24 },
  taskContent: { flex: 1 },
  taskTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "600" as const, color: black },
  taskTitleDone: { color: muted, textDecorationLine: "line-through" as const },
  taskDur: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted, marginTop: 2 },
  checkCircle: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: border, alignItems: "center", justifyContent: "center" },

  continueRow: { flexDirection: "row", alignItems: "center", gap: 14, padding: 14, backgroundColor: offWhite, borderRadius: 12, borderWidth: 1, borderColor: border },
  continueContent: { flex: 1, gap: 7 },
  continueTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "500" as const, color: black },
  continuePct: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted },
  continuePlay: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center" },

  favGrid: { flexDirection: "row", gap: 10 },
  favItem: { flex: 1, alignItems: "center", gap: 8, backgroundColor: offWhite, borderWidth: 1, borderColor: border, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 14 },
  favIcon: { width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  favText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "500" as const, color: body, textAlign: "center" },

  recommendRow: { flexDirection: "row", alignItems: "center", gap: 14, padding: 14, backgroundColor: offWhite, borderRadius: 12, borderWidth: 1, borderColor: border, marginBottom: 10 },
  recommendDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: orange },
  recommendContent: { flex: 1 },
  recommendTop: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  recommendTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "600" as const, color: black },
  recommendSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: muted },

  gamesPage: { paddingHorizontal: 32, paddingTop: 28, paddingBottom: 40, gap: 20 },
  gamesPageMobile: { paddingHorizontal: 14, paddingTop: 14 },
  gamesIntro: {
    backgroundColor: white,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: 14,
    padding: 24,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 20,
    boxShadow: "0 10px 30px rgba(18,18,18,0.05)" as any,
  },
  gamesTitle: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 31,
    fontWeight: "600" as const,
    color: black,
    lineHeight: 34,
    maxWidth: 640,
  },
  gamesCountPill: {
    backgroundColor: "rgba(232,93,42,0.08)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  gamesCountText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "700" as const, color: orange },
  gameSectionGrid: { display: "grid" as any, gridTemplateColumns: "1fr 1fr" as any, gap: 16 },
  gameSectionGridCompact: { display: "flex" as any, flexDirection: "column" },
  gameSectionCard: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 22,
    minHeight: 248,
    boxShadow: "0 12px 28px rgba(18,18,18,0.06)" as any,
  },
  gameSectionTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 14, marginBottom: 18 },
  gameSectionIcon: { width: 46, height: 46, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  gameColorCode: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  gameColorCodeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "800" as const, color: white },
  gameSectionTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 30, fontWeight: "700" as const, color: black, lineHeight: 32 },
  gameSectionSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: body, lineHeight: 19, marginTop: 6 },
  gameList: { gap: 8, marginTop: 16 },
  gameListItem: { flexDirection: "row", alignItems: "center", gap: 8 },
  gameListDot: { width: 6, height: 6, borderRadius: 3 },
  gameListText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: black },
  gameSectionAction: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 18 },
  gameSectionActionText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "800" as const },
  paletteCard: {
    backgroundColor: white,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: 14,
    padding: 24,
    boxShadow: "0 10px 30px rgba(18,18,18,0.05)" as any,
  },
  paletteRows: { gap: 10, marginTop: 8 },
  paletteRow: { flexDirection: "row", alignItems: "center", gap: 12, flexWrap: "wrap" as any, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: "#EFEFEF" },
  paletteSwatch: { width: 24, height: 24, borderRadius: 8, borderWidth: 1, borderColor: "rgba(18,18,18,0.10)" },
  paletteName: { minWidth: 70, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "800" as const, color: black },
  paletteCode: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: body, backgroundColor: offWhite, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4 },
  vaultTechniqueText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: black },

  vaultPage: { paddingHorizontal: 32, paddingTop: 28, paddingBottom: 48, gap: 18 },
  vaultTabs: { flexDirection: "row", flexWrap: "wrap" as any, gap: 10 },
  vaultTab: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderColor: "rgba(18,18,18,0.10)", borderRadius: 999, backgroundColor: white, paddingHorizontal: 14, paddingVertical: 9 },
  vaultTabEmoji: { fontSize: 15, lineHeight: 20 },
  vaultTabText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "800" as const, color: body },
  vaultTabTextActive: { color: white },
  vaultHero: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 22, backgroundColor: white, borderWidth: 1, borderColor: "rgba(18,18,18,0.10)", borderRadius: 14, padding: 24, boxShadow: SHADOW.md as any },
  vaultTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 36, fontWeight: "700" as const, color: black, lineHeight: 40 },
  vaultIntro: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: muted, lineHeight: 22, maxWidth: 620, marginTop: 6 },
  vaultHeroIcon: { width: 66, height: 66, borderRadius: 22, alignItems: "center", justifyContent: "center", flexShrink: 0 },
  vaultHeroEmoji: { fontSize: 30, lineHeight: 38 },
  skillTreeCard: { position: "relative" as any, minHeight: 560, overflow: "hidden", backgroundColor: "#101010", borderWidth: 1, borderColor: darkBorder, borderRadius: 18, boxShadow: "0 24px 70px rgba(18,18,18,0.24)" as any },
  skillTreeGrid: { position: "absolute" as any, inset: 0, opacity: 0.2, backgroundImage: "linear-gradient(rgba(255,255,255,0.12) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.12) 1px, transparent 1px)" as any, backgroundSize: "44px 44px" as any },
  skillNodeWrap: { position: "absolute" as any, width: 150, alignItems: "center", gap: 9 },
  skillConnector: { position: "absolute" as any, top: 34, left: 82, width: 118, height: 2, transform: [{ rotate: "16deg" }], transformOrigin: "left center" as any },
  skillNode: { width: 70, height: 70, borderRadius: 35, borderWidth: 2, alignItems: "center", justifyContent: "center", backgroundColor: panelSoft, boxShadow: "0 14px 34px rgba(0,0,0,0.22)" as any },
  skillNodeLabel: { alignItems: "center", gap: 2 },
  skillNodeTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "800" as const, color: white, textAlign: "center" },
  skillNodeSub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: darkMuted, textTransform: "uppercase" as any },
  vaultEmpty: { minHeight: 520, alignItems: "center", justifyContent: "center", padding: 32 },
  vaultEmptyIcon: { width: 78, height: 78, borderRadius: 28, alignItems: "center", justifyContent: "center", marginBottom: 18 },
  vaultEmptyEmoji: { fontSize: 34, lineHeight: 42 },
  vaultEmptyTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 34, fontWeight: "700" as const, color: white, textAlign: "center" },
  vaultEmptyText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: darkMuted, lineHeight: 22, textAlign: "center", maxWidth: 380, marginTop: 8 },
  vaultLegend: { flexDirection: "row", alignItems: "center", gap: 14, flexWrap: "wrap" as any, backgroundColor: "rgba(255,255,255,0.62)", borderWidth: 1, borderColor: "rgba(18,18,18,0.08)", borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12 },
  vaultLegendItem: { flexDirection: "row", alignItems: "center", gap: 8 },
  vaultLegendDot: { width: 10, height: 10, borderRadius: 5 },
  vaultLegendText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "700" as const, color: "#6B6057" },

  statGrid: { display: "grid" as any, gridTemplateColumns: "1fr 1fr 1fr" as any, gap: 12, marginBottom: 20 },
  statMini: { backgroundColor: panelSoft, borderWidth: 1, borderColor: darkBorder, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 14, alignItems: "center" },
  statEmoji: { fontSize: 16, lineHeight: 22 },
  statMiniValue: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 21, fontWeight: "700" as const, color: white, marginTop: 6 },
  statMiniLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, color: darkMuted, marginTop: 2, textAlign: "center" },
  chartHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 8 },
  chartLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted, marginBottom: 10 },
  chartLabelInline: { marginBottom: 0 },
  chartScoreText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "800" as const, color: orange },
  graphSelector: { marginBottom: 12 },
  graphSelectorContent: { gap: 8, paddingRight: 6 },
  graphSelectorBtn: { borderWidth: 1, borderColor: darkBorder, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7, backgroundColor: "rgba(255,255,255,0.04)" },
  graphSelectorBtnActive: { backgroundColor: "rgba(232,93,42,0.16)", borderColor: orange },
  graphSelectorText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: darkMuted },
  graphSelectorTextActive: { color: white },
  timeScaleRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 6, flexWrap: "wrap" as any },
  timeScaleBtn: { borderWidth: 1, borderColor: darkBorder, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: "rgba(255,255,255,0.04)" },
  timeScaleBtnActive: { backgroundColor: orange, borderColor: orange },
  timeScaleText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "800" as const, color: darkMuted },
  timeScaleTextActive: { color: white },
  graphZoomHint: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: darkMuted, marginLeft: 4 },
  graphZoomHintActive: { color: orange },
  chart: { flexDirection: "row", alignItems: "flex-end", gap: 5, height: 62 },
  chartColumn: { flex: 1, alignItems: "center", gap: 4, height: "100%" as any, justifyContent: "flex-end" },
  chartBar: { width: "100%" as any, minHeight: 4, borderRadius: 4, opacity: 0.95 },
  chartDay: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, color: muted },
  chartDayActive: { color: orange, fontWeight: "600" as const },
  graphDetailPanel: { marginTop: 12, borderWidth: 1, borderColor: darkBorder, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.04)", paddingHorizontal: 12, paddingVertical: 10 },
  graphDetailTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 4 },
  graphDetailTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "800" as const, color: white },
  graphDetailDate: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: orange },
  graphDetailText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, lineHeight: 17, color: darkMuted },
  performanceScorePill: { alignItems: "flex-end", borderWidth: 1, borderColor: "rgba(232,93,42,0.30)", backgroundColor: "rgba(232,93,42,0.12)", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 9 },
  performanceScore: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 20, fontWeight: "800" as const, color: orange },
  performanceScoreLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: darkMuted, textTransform: "uppercase" as any },
  graphChartScroll: { marginTop: 14 },
  graphChartScrollContent: { paddingBottom: 2 },
  graphLineChart: { position: "relative" as any, width: 1120, height: 340, overflow: "hidden", borderWidth: 1, borderColor: darkBorder, borderRadius: 14, backgroundColor: "#111111", transition: "border-color 180ms ease, background-color 180ms ease" as any },
  graphLineChartSelected: { borderColor: orange, boxShadow: "0 0 0 3px rgba(232,93,42,0.18), 0 22px 52px rgba(0,0,0,0.22)" as any },
  graphLineGrid: { position: "absolute" as any, inset: 0, opacity: 0.35, backgroundImage: "linear-gradient(rgba(255,255,255,0.10) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.08) 1px, transparent 1px)" as any, backgroundSize: "100% 25%, 12.5% 100%" as any },
  graphTodayMarker: { position: "absolute" as any, top: 42, bottom: 52, width: 1, backgroundColor: "rgba(255,255,255,0.22)" },
  graphTodayLabel: { position: "absolute" as any, top: 14, width: 58, marginLeft: 10, textAlign: "left", fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, color: orange, textTransform: "uppercase" as any },
  graphLineSegment: { position: "absolute" as any, height: 3, borderRadius: 999, backgroundColor: orange, transformOrigin: "left center" as any, boxShadow: "0 0 18px rgba(232,93,42,0.28)" as any, zIndex: 2, transition: "left 220ms ease, top 220ms ease, width 220ms ease, transform 220ms ease" as any },
  graphLinePoint: { position: "absolute" as any, width: 30, height: 30, marginLeft: -15, marginTop: -15, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: panelSoft, borderWidth: 2, borderColor: orange, zIndex: 3, transition: "left 220ms ease, top 220ms ease, background-color 160ms ease, box-shadow 160ms ease" as any },
  graphLinePointActive: { backgroundColor: orange, boxShadow: "0 0 0 6px rgba(232,93,42,0.18)" as any },
  graphLinePointText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, color: white },
  graphAxisLabel: { position: "absolute" as any, bottom: 18, width: 74, marginLeft: -37, textAlign: "center", fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: darkMuted },
  graphEmptyState: { position: "absolute" as any, inset: 0, alignItems: "center", justifyContent: "center", gap: 6, paddingHorizontal: 24 },
  graphEmptyTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, fontWeight: "800" as const, color: white },
  graphDetailPanelWide: { marginTop: 14, borderWidth: 1, borderColor: darkBorder, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.04)", paddingHorizontal: 14, paddingVertical: 12 },
  performanceStatsRow: { flexDirection: "row", alignItems: "center", gap: 14, flexWrap: "wrap" as any },
  weekStrip: { flexDirection: "row", gap: 8, marginBottom: 18 },
  weekDay: { flex: 1, alignItems: "center", gap: 6 },
  weekDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: panelSoft,
    borderWidth: 1,
    borderColor: darkBorder,
  },
  weekDotActive: { backgroundColor: orange, borderColor: orange },
  weekDotToday: { boxShadow: "0 0 0 3px rgba(232,93,42,0.20)" as any },
  weekLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: darkMuted },
  weekLabelToday: { color: orange },

  techniqueRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10, backgroundColor: offWhite, borderWidth: 1, borderColor: border },
  techniqueLocked: { opacity: 0.62, backgroundColor: "#FAFAFA", borderColor: "#EFEFEF" },
  techniqueIcon: { width: 28, height: 28, borderRadius: 8, backgroundColor: "rgba(232,93,42,0.10)", alignItems: "center", justifyContent: "center" },
  techniqueIconLocked: { backgroundColor: border },
  techniqueText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "500" as const, color: white },
  techniqueTextLocked: { color: muted, fontWeight: "400" as const },
  outlineBtn: { marginTop: 16, alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 7, borderWidth: 1, borderColor: darkBorder, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 9, backgroundColor: "rgba(255,255,255,0.04)" },
  outlineBtnText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: white },

  segment: { flexDirection: "row", backgroundColor: panelSoft, borderWidth: 1, borderColor: darkBorder, borderRadius: 8, padding: 2, gap: 2 },
  segmentBtn: { borderRadius: 6, paddingHorizontal: 12, paddingVertical: 5 },
  segmentBtnActive: { backgroundColor: orange, boxShadow: "0 1px 4px rgba(0,0,0,0.18)" as any },
  segmentText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: darkMuted },
  segmentTextActive: { color: white, fontWeight: "600" as const },
  leaderRow: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: offWhite, borderRadius: 12, borderWidth: 1, borderColor: border, paddingHorizontal: 14, paddingVertical: 11 },
  leaderRowYou: { backgroundColor: "rgba(232,93,42,0.04)", borderColor: "rgba(232,93,42,0.24)" },
  rankBadge: { width: 26, height: 26, borderRadius: 13, backgroundColor: border, alignItems: "center", justifyContent: "center" },
  rankGold: { backgroundColor: "#FFD700" },
  rankSilver: { backgroundColor: "#C0C0C0" },
  rankBronze: { backgroundColor: "#CD7F32" },
  rankText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, fontWeight: "700" as const, color: white },
  leaderName: { flex: 1, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: white },
  leaderNameYou: { color: orange, fontWeight: "600" as const },
  leaderXp: { flexDirection: "row", alignItems: "center", gap: 4 },
  leaderEmoji: { fontSize: 12, lineHeight: 16 },
  leaderXpText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "600" as const, color: white },
  leaderXpLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, color: muted },

  dashboardFooter: {
    borderTopWidth: 1,
    borderTopColor: "rgba(18,18,18,0.10)",
    paddingHorizontal: 32,
    paddingVertical: 22,
    backgroundColor: "rgba(255,255,255,0.58)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  dashboardFooterBrand: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 17, fontWeight: "700" as const, color: black },
  dashboardFooterText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: muted, textAlign: "right" },
  dashboardFooterBeige: { backgroundColor: "#EDE7D8", borderTopColor: "rgba(0,0,0,0.08)" },

  modalRoot: { flex: 1, alignItems: "center", justifyContent: "center" },
  modalScrim: { position: "absolute" as any, inset: 0, backgroundColor: "rgba(18,18,18,0.45)" },
  modalCard: { width: "min(92vw, 520px)" as any, overflow: "visible", backgroundColor: white, borderRadius: 20, padding: 32, borderWidth: 1, borderColor: border, boxShadow: "0 24px 64px rgba(0,0,0,0.18)" as any },
  modalHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 24 },
  modalTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 25, fontWeight: "600" as const, color: black },
  modalClose: { width: 30, height: 30, borderRadius: 8, borderWidth: 1, borderColor: border, backgroundColor: offWhite, alignItems: "center", justifyContent: "center" },
  inputLabel: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "600" as const, color: muted, letterSpacing: 0.8, textTransform: "uppercase" as any, marginBottom: 8, marginTop: 14 },
  goalTypeRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" as any },
  goalTypeBtn: { borderWidth: 1, borderColor: border, borderRadius: 9, backgroundColor: offWhite, alignItems: "center", paddingHorizontal: 12, paddingVertical: 9 },
  goalTypeBtnActive: { borderColor: orange, backgroundColor: "rgba(232,93,42,0.08)" },
  goalTypeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: body, textTransform: "capitalize" as any },
  goalTypeTextActive: { color: orange, fontWeight: "600" as const },
  goalTargetGrid: { display: "grid" as any, gridTemplateColumns: "repeat(3, minmax(0, 1fr))" as any, gap: 10, width: "100%" as any, position: "relative" as any, zIndex: 30 },
  goalTargetField: { minWidth: 0, position: "relative" as any, zIndex: 31 },
  modalInput: { minWidth: 0, width: "100%" as any, backgroundColor: offWhite, borderWidth: 1, borderColor: border, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: black, boxSizing: "border-box" as any },
  metricSelect: { minWidth: 0, width: "100%" as any, backgroundColor: offWhite, borderWidth: 1, borderColor: border, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, boxSizing: "border-box" as any, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 6 },
  metricSelectText: { flex: 1, minWidth: 0, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: black, textTransform: "capitalize" as any },
  metricMenu: { position: "absolute" as any, top: 45, left: 0, right: 0, zIndex: 1000, elevation: 20, maxHeight: 268, overflow: "hidden", backgroundColor: white, borderWidth: 1, borderColor: border, borderRadius: 10, paddingVertical: 4, boxShadow: "0 12px 28px rgba(18,18,18,0.14)" as any },
  metricMenuScroll: { maxHeight: 252 },
  metricMenuItem: { paddingHorizontal: 12, paddingVertical: 9 },
  modalActions: { flexDirection: "row", gap: 10, marginTop: 28 },
  cancelBtn: { flex: 1, borderWidth: 1, borderColor: border, borderRadius: 10, alignItems: "center", paddingVertical: 12 },
  cancelBtnText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: body },
  saveBtn: { flex: 2, backgroundColor: orangeLight, borderRadius: 10, alignItems: "center", paddingVertical: 12 },
  saveBtnText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "600" as const, color: white },
});
