import { createWebStyles } from "../web";

export const FLASHCARD_ACCENT = "#5B5BD6";

export const flashcards = createWebStyles({
  page: { paddingHorizontal: 32, paddingTop: 28, paddingBottom: 36, gap: 22 },
  pageMobile: { paddingHorizontal: 14, paddingTop: 18, paddingBottom: 24, gap: 16 },
  toolbar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" },
  toolbarGroup: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" },
  primaryButton: { minHeight: 44, paddingHorizontal: 18, borderRadius: 13, backgroundColor: FLASHCARD_ACCENT, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, boxShadow: "0 10px 24px rgba(91,91,214,0.24)" as any },
  primaryButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
  secondaryButton: { minHeight: 42, paddingHorizontal: 15, borderRadius: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "rgba(24,38,48,0.13)", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
  secondaryButtonText: { color: "#263947", fontSize: 13, fontWeight: "800" },
  dangerButton: { backgroundColor: "#FFF3F2", borderColor: "#F1B7B1" },
  dangerButtonText: { color: "#B7352C" },
  disabled: { opacity: 0.45 },
  errorBanner: { padding: 13, borderRadius: 12, backgroundColor: "#FFF2F0", borderWidth: 1, borderColor: "#F2C1BA", flexDirection: "row", alignItems: "flex-start", gap: 9 },
  errorText: { flex: 1, color: "#9E3229", fontSize: 13, lineHeight: 19 },
  successBanner: { padding: 13, borderRadius: 12, backgroundColor: "#ECFAF4", borderWidth: 1, borderColor: "#A8E1C7", flexDirection: "row", alignItems: "center", gap: 9 },
  successText: { flex: 1, color: "#176245", fontSize: 13, fontWeight: "700" },
  emptyCard: { minHeight: 350, padding: 32, borderRadius: 24, backgroundColor: "rgba(255,255,255,0.95)", borderWidth: 1, borderColor: "rgba(28,47,60,0.10)", alignItems: "center", justifyContent: "center", boxShadow: "0 18px 48px rgba(34,57,70,0.08)" as any },
  emptyCardMobile: { minHeight: 300, padding: 22, borderRadius: 18 },
  emptyIcon: { width: 72, height: 72, borderRadius: 24, backgroundColor: "#EEEEFF", alignItems: "center", justifyContent: "center", marginBottom: 18 },
  emptyTitle: { color: "#172A38", fontSize: 25, lineHeight: 31, fontWeight: "900", textAlign: "center" },
  emptyText: { maxWidth: 520, marginTop: 9, marginBottom: 22, color: "#677A87", fontSize: 14, lineHeight: 22, textAlign: "center" },
  libraryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  systemCard: { width: "31.5%" as any, minWidth: 250, flexGrow: 1, padding: 20, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.96)", borderWidth: 1, borderColor: "rgba(31,51,64,0.10)", boxShadow: "0 12px 30px rgba(32,52,64,0.07)" as any, gap: 15 },
  systemCardMobile: { width: "100%" as any, minWidth: 0, padding: 17 },
  systemTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  systemIcon: { width: 45, height: 45, borderRadius: 14, backgroundColor: "#EEEEFF", alignItems: "center", justifyContent: "center" },
  kindPill: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 999, backgroundColor: "#F1F1FA" },
  kindText: { color: FLASHCARD_ACCENT, fontSize: 10, fontWeight: "900", letterSpacing: 0.8, textTransform: "uppercase" },
  systemTitle: { color: "#172A38", fontSize: 19, lineHeight: 24, fontWeight: "900" },
  systemMeta: { marginTop: 4, color: "#71818C", fontSize: 12, lineHeight: 18 },
  cardStats: { flexDirection: "row", gap: 8 },
  miniStat: { flex: 1, padding: 10, borderRadius: 11, backgroundColor: "#F6F7F9" },
  miniStatValue: { color: "#213744", fontSize: 15, fontWeight: "900" },
  miniStatLabel: { marginTop: 2, color: "#81909A", fontSize: 10, fontWeight: "700" },
  pendingBadge: { alignSelf: "flex-start", paddingHorizontal: 9, paddingVertical: 5, borderRadius: 999, backgroundColor: "#FFF6DA", flexDirection: "row", alignItems: "center", gap: 5 },
  pendingText: { color: "#826414", fontSize: 10, fontWeight: "800" },
  importPanel: { padding: 24, borderRadius: 22, backgroundColor: "rgba(255,255,255,0.98)", borderWidth: 1, borderColor: "rgba(28,47,60,0.12)", boxShadow: "0 18px 48px rgba(34,57,70,0.10)" as any, gap: 18 },
  importPanelMobile: { padding: 16, borderRadius: 17 },
  panelHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 14 },
  panelKicker: { color: FLASHCARD_ACCENT, fontSize: 10, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase" },
  panelTitle: { marginTop: 4, color: "#172A38", fontSize: 22, lineHeight: 28, fontWeight: "900" },
  panelSubtitle: { marginTop: 5, color: "#6E808C", fontSize: 13, lineHeight: 20 },
  closeButton: { width: 36, height: 36, borderRadius: 11, backgroundColor: "#F3F4F6", alignItems: "center", justifyContent: "center" },
  dropZone: { minHeight: 150, borderRadius: 17, borderWidth: 2, borderStyle: "dashed", borderColor: "#BEBEF0", backgroundColor: "#F8F8FF", alignItems: "center", justifyContent: "center", padding: 22 },
  dropTitle: { color: "#283E4C", fontSize: 16, fontWeight: "900", marginTop: 10 },
  dropText: { color: "#75858F", fontSize: 12, lineHeight: 18, marginTop: 4, textAlign: "center" },
  orRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  orLine: { flex: 1, height: 1, backgroundColor: "#E4E7EA" },
  orText: { color: "#97A2A9", fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
  textarea: { minHeight: 110, padding: 13, borderRadius: 13, borderWidth: 1, borderColor: "#D9DEE2", backgroundColor: "#FFFFFF", color: "#1E3340", fontSize: 13, textAlignVertical: "top" },
  input: { minHeight: 43, paddingHorizontal: 13, borderRadius: 11, borderWidth: 1, borderColor: "#D8DEE2", backgroundColor: "#FFFFFF", color: "#1D3340", fontSize: 13 },
  fieldLabel: { color: "#526672", fontSize: 11, fontWeight: "800", marginBottom: 6 },
  previewSummary: { padding: 14, borderRadius: 13, backgroundColor: "#F1F1FF", flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" },
  previewSummaryText: { flex: 1, minWidth: 180, color: "#3E3E91", fontSize: 13, fontWeight: "800", lineHeight: 19 },
  mappingRow: { flexDirection: "row", gap: 9, flexWrap: "wrap" },
  mappingCard: { minWidth: 130, flexGrow: 1, flexBasis: 150, padding: 11, borderRadius: 11, backgroundColor: "#F7F8F9", borderWidth: 1, borderColor: "#E0E4E7" },
  mappingHeader: { color: "#304652", fontSize: 11, fontWeight: "900" },
  mappingSample: { color: "#84919A", fontSize: 10, marginTop: 3, marginBottom: 8 },
  roleButton: { minHeight: 32, borderRadius: 8, backgroundColor: "#E9E9FB", alignItems: "center", justifyContent: "center", paddingHorizontal: 9 },
  roleButtonText: { color: FLASHCARD_ACCENT, fontSize: 10, fontWeight: "900", textTransform: "uppercase" },
  issueList: { gap: 7, maxHeight: 180, overflow: "auto" as any },
  issueRow: { padding: 10, borderRadius: 10, backgroundColor: "#FFF8E9", flexDirection: "row", alignItems: "flex-start", gap: 8 },
  issueText: { flex: 1, color: "#735C20", fontSize: 11, lineHeight: 17 },
  optionRow: { flexDirection: "row", gap: 9, flexWrap: "wrap" },
  optionButton: { minHeight: 40, paddingHorizontal: 13, borderRadius: 11, borderWidth: 1, borderColor: "#D8DEE2", backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
  optionButtonActive: { borderColor: FLASHCARD_ACCENT, backgroundColor: "#EEEEFF" },
  optionText: { color: "#61737E", fontSize: 12, fontWeight: "800" },
  optionTextActive: { color: FLASHCARD_ACCENT },
  previewTable: { borderWidth: 1, borderColor: "#E2E6E9", borderRadius: 12, overflow: "hidden" },
  tableRow: { flexDirection: "row", minHeight: 38, borderBottomWidth: 1, borderBottomColor: "#EDF0F2", alignItems: "center" },
  tableCell: { minWidth: 105, flex: 1, paddingHorizontal: 9, paddingVertical: 8, color: "#435762", fontSize: 11 },
  tableHeaderCell: { backgroundColor: "#F4F5F7", color: "#263C49", fontWeight: "900" },
  statsGrid: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  statCard: { minWidth: 130, flex: 1, padding: 15, borderRadius: 15, backgroundColor: "rgba(255,255,255,0.96)", borderWidth: 1, borderColor: "rgba(29,49,62,0.10)" },
  statValue: { color: "#1C3341", fontSize: 22, fontWeight: "900" },
  statLabel: { marginTop: 3, color: "#72838E", fontSize: 11, fontWeight: "700" },
  contentCard: { padding: 21, borderRadius: 20, backgroundColor: "rgba(255,255,255,0.97)", borderWidth: 1, borderColor: "rgba(29,49,62,0.10)", boxShadow: "0 12px 34px rgba(31,51,64,0.07)" as any, gap: 16 },
  contentCardMobile: { padding: 15, borderRadius: 16 },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" },
  sectionTitle: { color: "#1B3240", fontSize: 18, fontWeight: "900" },
  sectionText: { marginTop: 4, color: "#74858F", fontSize: 12, lineHeight: 18 },
  heatmapFrame: { width: "100%" as any },
  heatmap: { width: "100%" as any, flexDirection: "row", flexWrap: "wrap", gap: 5, alignContent: "flex-start" },
  heatCell: { width: 46, height: 46, borderRadius: 9, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.6)" },
  heatCellText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900", textShadowColor: "rgba(0,0,0,0.25)", textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 2 },
  pegSheet: { padding: 17, borderRadius: 15, backgroundColor: "#F6F7FF", borderWidth: 1, borderColor: "#D9D9F4", gap: 12 },
  pegSheetTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  pegKey: { color: FLASHCARD_ACCENT, fontSize: 27, fontWeight: "900" },
  pegValues: { flexDirection: "row", gap: 9, flexWrap: "wrap" },
  pegValue: { minWidth: 130, flex: 1, padding: 11, borderRadius: 11, backgroundColor: "#FFFFFF" },
  pegValueLabel: { color: "#8B96A0", fontSize: 9, fontWeight: "900", textTransform: "uppercase" },
  pegValueText: { color: "#223B49", fontSize: 13, fontWeight: "800", marginTop: 3 },
  editableRow: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#E9ECEE", gap: 9 },
  editableTop: { flexDirection: "row", alignItems: "center", gap: 10 },
  editableKey: { width: 45, color: FLASHCARD_ACCENT, fontSize: 15, fontWeight: "900" },
  editableFields: { flex: 1, flexDirection: "row", gap: 8, flexWrap: "wrap" },
  editableInput: { minWidth: 120, flex: 1, minHeight: 38, paddingHorizontal: 10, borderRadius: 9, borderWidth: 1, borderColor: "#D8DEE2", color: "#253B48", fontSize: 12, backgroundColor: "#FFFFFF" },
  historyRow: { paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: "#EBEEF0", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  historyName: { color: "#29404D", fontSize: 12, fontWeight: "800" },
  historyMeta: { color: "#83909A", fontSize: 10, marginTop: 3 },
  trainStage: { padding: 24, borderRadius: 24, backgroundColor: "#17172A", boxShadow: "0 20px 56px rgba(22,22,42,0.24)" as any },
  trainStageMobile: { padding: 12, borderRadius: 18 },
  setupPanel: { padding: 24, borderRadius: 18, backgroundColor: "#FFFFFF", gap: 20 },
  setupPanelMobile: { padding: 16, gap: 16 },
  setupGrid: { flexDirection: "row", gap: 14, flexWrap: "wrap" },
  setupField: { minWidth: 220, flex: 1, gap: 7 },
  setupLabel: { color: "#506570", fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.7 },
  settingHint: { color: "#7B8A93", fontSize: 10, lineHeight: 15 },
  boxSummary: { flexDirection: "row", gap: 9, flexWrap: "wrap" },
  boxCount: { minWidth: 92, flex: 1, paddingHorizontal: 12, paddingVertical: 11, borderRadius: 12, borderWidth: 1 },
  boxCount_unseen: { backgroundColor: "#F3F4F7", borderColor: "#D8DDE3" },
  boxCount_box0: { backgroundColor: "#FFF1EF", borderColor: "#EDB8B2" },
  boxCount_box1: { backgroundColor: "#FFF7E8", borderColor: "#E8CC91" },
  boxCount_box2: { backgroundColor: "#F3F7E9", borderColor: "#CAD99B" },
  boxCount_box3: { backgroundColor: "#EAF7F0", borderColor: "#A8D8BE" },
  boxCountValue: { color: "#263947", fontSize: 18, fontWeight: "900" },
  boxCountLabel: { marginTop: 2, color: "#687A85", fontSize: 10, fontWeight: "800" },
  progressTrack: { height: 7, borderRadius: 999, backgroundColor: "#E5E6ED", overflow: "hidden" },
  progressFill: { height: "100%" as any, borderRadius: 999, backgroundColor: FLASHCARD_ACCENT },
  sessionTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  sessionCounter: { color: "#6F7E88", fontSize: 11, fontWeight: "800" },
  sessionBoxText: { color: "#7B8494", fontSize: 10, fontWeight: "800" },
  swipeCardWrap: { width: "100%" as any },
  flashCard: { width: "100%" as any, minHeight: 330, padding: 26, borderRadius: 20, backgroundColor: "#F7F7FC", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#E1E1EF", overflow: "hidden" },
  flashCardMobile: { minHeight: 300, padding: 18 },
  swipeGrade: { position: "absolute", top: 18, zIndex: 2, flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, borderWidth: 1 },
  swipePoor: { left: 18, backgroundColor: "#FFF1EF", borderColor: "#EDB8B2" },
  swipeGood: { right: 18, backgroundColor: "#EAF7F0", borderColor: "#A8D8BE" },
  swipePoorText: { color: "#B64036", fontSize: 12, fontWeight: "900" },
  swipeGoodText: { color: "#23845B", fontSize: 12, fontWeight: "900" },
  gestureHint: { color: "#87959E", fontSize: 11, fontWeight: "700", textAlign: "center", marginTop: 22 },
  promptLabel: { color: "#8A94A0", fontSize: 10, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase" },
  prompt: { marginTop: 10, color: "#171D2D", fontSize: 45, lineHeight: 53, fontWeight: "900", textAlign: "center" },
  promptMobile: { fontSize: 35, lineHeight: 42 },
  revealValues: { width: "100%" as any, marginTop: 26, gap: 9 },
  revealValue: { padding: 12, borderRadius: 11, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#DFE2E8", flexDirection: "row", justifyContent: "space-between", gap: 12 },
  revealLabel: { color: "#74838E", fontSize: 11, fontWeight: "800" },
  revealAnswer: { flex: 1, color: "#263A48", fontSize: 13, fontWeight: "900", textAlign: "right" },
  answerStack: { width: "100%" as any, marginTop: 24, gap: 9 },
  choiceGrid: { width: "100%" as any, marginTop: 24, flexDirection: "row", gap: 9, flexWrap: "wrap" },
  choiceButton: { minWidth: "47%" as any, flex: 1, padding: 14, borderRadius: 12, borderWidth: 1, borderColor: "#D9DCE4", backgroundColor: "#FFFFFF", alignItems: "center" },
  choiceText: { color: "#314653", fontSize: 13, fontWeight: "800", textAlign: "center" },
  feedbackCorrect: { borderColor: "#64BC91", backgroundColor: "#EDFAF4" },
  feedbackWrong: { borderColor: "#DE897F", backgroundColor: "#FFF1EF" },
  actionRow: { flexDirection: "row", justifyContent: "center", gap: 10, flexWrap: "wrap" },
  knewButton: { backgroundColor: "#23845B" },
  missedButton: { backgroundColor: "#C64E43" },
  resultHero: { alignItems: "center", paddingVertical: 18 },
  resultScore: { color: FLASHCARD_ACCENT, fontSize: 54, lineHeight: 62, fontWeight: "900" },
  resultTitle: { color: "#1B3140", fontSize: 22, fontWeight: "900" },
  resultText: { color: "#71818C", fontSize: 13, lineHeight: 20, textAlign: "center", marginTop: 6 },
  missedList: { gap: 7 },
  missedRow: { padding: 11, borderRadius: 10, backgroundColor: "#FFF3F1", flexDirection: "row", alignItems: "center", gap: 9 },
  missedKey: { color: "#B73F35", fontSize: 13, fontWeight: "900" },
  missedText: { flex: 1, color: "#7B4B47", fontSize: 11 },
});
