import { createWebStyles } from "../web";
import { C, P, RADIUS, SHADOW } from "../tokens";

const T = {
  orange: C.orange,
  ink: C.bgForest,
  black: C.text,
  white: C.white,
  beige: "#F3EDE1",
  beigeCard: "#FDFAF5",
  beigeBorder: "rgba(0,0,0,0.08)",
  beigeSubtle: "#EDE7D8",
  muted: C.muted,
  mutedDark: "#6B6057",
  darkMuted: C.mutedInverse,
};

export const games = createWebStyles({
  page: { backgroundColor: T.beige, minHeight: "100%" as any },
  pageInner: { paddingHorizontal: 32, paddingTop: 32, paddingBottom: 56 },
  pageInnerMobile: { paddingHorizontal: 14, paddingTop: 18, paddingBottom: 34 },

  searchBar: {
    width: 360,
    maxWidth: "100%" as any,
    position: "relative" as any,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.10)",
    borderRadius: RADIUS.sm,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  searchBarFocus: { borderColor: T.orange },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: T.white,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    outlineStyle: "none" as any,
  },
  clearSearch: { width: 20, height: 20, alignItems: "center", justifyContent: "center" },

  featured: {
    backgroundColor: "#4848BE",
    backgroundImage: "linear-gradient(135deg, #2E2E96 0%, #4848BE 100%)" as any,
    borderRadius: RADIUS.md,
    paddingHorizontal: 32,
    paddingVertical: 28,
    marginBottom: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 24,
    borderWidth: 1,
    borderColor: "rgba(91,91,214,0.25)",
    boxShadow: SHADOW.md as any,
  },
  featuredMobile: { flexDirection: "column", alignItems: "flex-start", paddingHorizontal: 22 },
  featuredEyebrowRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10, flexWrap: "wrap" as any },
  eyebrow: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, letterSpacing: 1.2, textTransform: "uppercase" as any, color: "rgba(255,255,255,0.50)" },
  hotPill: { backgroundColor: "rgba(255,215,0,0.15)", borderRadius: 6, paddingHorizontal: 9, paddingVertical: 2 },
  hotText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: "#FFD700" },
  featuredTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 36, fontWeight: "700" as const, color: T.white, lineHeight: 40 },
  featuredText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: "rgba(255,255,255,0.62)", lineHeight: 23, maxWidth: 420, marginTop: 10, marginBottom: 20 },
  featuredBtn: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 1.5, borderColor: "rgba(255,255,255,0.25)", borderRadius: RADIUS.sm, paddingHorizontal: 22, paddingVertical: 11 },
  featuredBtnText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "700" as const, color: T.white },
  featuredOrb: { width: 140, height: 140, borderRadius: 70, backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  featuredOrbInner: { width: 96, height: 96, borderRadius: 48, backgroundColor: "rgba(255,255,255,0.08)", alignItems: "center", justifyContent: "center" },

  searchMeta: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: T.mutedDark, marginBottom: 20 },
  searchMetaStrong: { color: T.ink, fontWeight: "700" as const },
  searchGrid: { flexDirection: "row", flexWrap: "wrap" as any, gap: 12 },
  emptyState: { alignItems: "center", paddingVertical: 60, paddingHorizontal: 20, backgroundColor: T.beigeCard, borderRadius: 14, borderWidth: 1, borderColor: T.beigeBorder },
  emptyText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: T.muted },

  carouselSection: { marginBottom: 48 },
  rowHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 16 },
  rowMarker: { width: 3, height: 20, borderRadius: 2 },
  rowTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 24, fontWeight: "700" as const, color: T.ink },
  rowCount: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: T.muted },
  carouselShell: {
    minHeight: 600,
    borderRadius: RADIUS.xl,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: T.beigeBorder,
    boxShadow: SHADOW.sm as any,
    flexDirection: "row",
  },
  carouselShellCompact: { flexDirection: "column", minHeight: 0 },
  categoryPanel: { width: "40%" as any, minWidth: 310, paddingHorizontal: 32, paddingVertical: 44, justifyContent: "center", overflow: "hidden", position: "relative" as any },
  categoryPanelCompact: { width: "100%" as any, minWidth: 0 },
  categoryBgImage: { position: "absolute" as any, inset: 0, width: "100%" as any, height: "100%" as any, opacity: 0.72 },
  categoryBgWash: {
    position: "absolute" as any,
    inset: 0,
    backgroundImage: "linear-gradient(90deg, rgba(12,10,18,0.72) 0%, rgba(47,44,127,0.58) 48%, rgba(91,91,214,0.34) 100%)" as any,
  },
  categoryContent: { position: "relative" as any, zIndex: 2 },
  categoryHero: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.30)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 18,
  },
  categoryImage: { width: "100%" as any, height: "100%" as any },
  categoryHeroEmoji: { fontSize: 34, lineHeight: 42 },
  categoryTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 34, fontWeight: "700" as const, color: T.white },
  categorySub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: "rgba(255,255,255,0.68)", lineHeight: 20, marginTop: 8, marginBottom: 22 },
  pillWrap: { flexDirection: "row", flexWrap: "wrap" as any, gap: 10 },
  pillWrapVertical: { flexDirection: "column", flexWrap: "nowrap" as any, alignItems: "flex-start", gap: 12 },
  categoryPill: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 999, borderWidth: 1, borderColor: "rgba(255,255,255,0.24)", paddingHorizontal: 18, paddingVertical: 10 },
  categoryPillActive: { backgroundColor: "rgba(255,255,255,0.96)", borderColor: "rgba(255,255,255,0.96)" },
  categoryPillText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "700" as const, letterSpacing: 0.5, textTransform: "uppercase" as any, color: "rgba(255,255,255,0.70)" },
  categoryPillTextActive: { color: T.black },
  cardRail: { flex: 1, minHeight: 520, backgroundColor: T.beige, paddingHorizontal: 24, paddingVertical: 28, justifyContent: "center", alignItems: "center", overflow: "hidden" },
  cardRailScroll: { gap: 18 },
  cardStack: { width: 360, height: 480, position: "relative" as any, alignItems: "center", justifyContent: "center" },

  gameCard: { width: 290, height: 400, backgroundColor: "#1A1614", borderRadius: 22, overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,255,255,0.06)", boxShadow: "0 24px 70px rgba(0,0,0,0.18)" as any, backfaceVisibility: "hidden" as any, transformStyle: "preserve-3d" as any, willChange: "transform, opacity" as any },
  stackedGameCard: { position: "absolute" as any, top: 40, left: 35 },
  gameCardLocked: { opacity: 0.58 },
  artZone: { height: 170, position: "relative" as any, overflow: "hidden", backgroundColor: "#2A2420" },
  artStripe: { position: "absolute" as any, inset: 0, opacity: 0.18, backgroundImage: "repeating-linear-gradient(135deg, rgba(0,0,0,0.34) 0 2px, transparent 2px 12px)" as any },
  artWash: { position: "absolute" as any, inset: 0 },
  artPatternRow: { position: "absolute" as any, inset: 0, flexDirection: "row", flexWrap: "wrap" as any, gap: 18, padding: 18, opacity: 0.18 },
  artPatternMark: { color: T.white, fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 22, fontWeight: "700" as const },
  artIcon: { position: "absolute" as any, top: 18, left: 20, width: 50, height: 50, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.14)", borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },
  favouriteBtn: { position: "absolute" as any, top: 18, right: 14, width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(0,0,0,0.28)", borderWidth: 1, borderColor: "rgba(255,255,255,0.14)", alignItems: "center", justifyContent: "center", zIndex: 4 },
  favouriteBtnActive: { backgroundColor: C.orange, borderColor: C.orange },
  cardEmojiBadge: { position: "absolute" as any, left: 18, bottom: 12, width: 40, height: 40, borderRadius: 14, backgroundColor: "rgba(0,0,0,0.24)", borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", alignItems: "center", justifyContent: "center" },
  cardEmojiText: { fontSize: 20, lineHeight: 26 },
  artLabel: { position: "absolute" as any, right: 12, bottom: 10, backgroundColor: "rgba(0,0,0,0.35)", borderWidth: 1, borderColor: "rgba(255,255,255,0.10)", borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  artLabelText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, color: "rgba(255,255,255,0.48)", letterSpacing: 0.6 },
  badgeStack: { position: "absolute" as any, top: 58, right: 12, gap: 4, alignItems: "flex-end" },
  smallBadge: { borderRadius: 5, paddingHorizontal: 7, paddingVertical: 2, borderWidth: 1 },
  smallBadgeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, fontWeight: "800" as const, letterSpacing: 0.6, textTransform: "uppercase" as any },
  cardBody: { flex: 1, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 20, gap: 10 },
  cardKickerRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  cardKicker: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, fontWeight: "800" as const, letterSpacing: 1.2, textTransform: "uppercase" as any },
  cardRule: { flex: 1, height: 1 },
  cardTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 28, fontWeight: "700" as const, color: "#F5EFE3", lineHeight: 31 },
  cardDesc: { flex: 1, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: "rgba(245,239,227,0.52)", lineHeight: 20 },
  cardMeta: { flexDirection: "row", alignItems: "center", gap: 7 },
  diffBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  diffText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, letterSpacing: 0.4, textTransform: "uppercase" as any },
  duration: { marginLeft: "auto" as any, flexDirection: "row", alignItems: "center", gap: 4 },
  durationText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, color: "rgba(245,239,227,0.42)" },
  playButton: { width: "100%" as any, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 11, borderWidth: 1, paddingVertical: 12 },
  playButtonText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "800" as const },
});
