import { createWebStyles } from "../web";
import { C, P, RADIUS, SHADOW } from "../tokens";

const T = {
  orange: C.orange,
  ink: P.dark,
  panel: "#161616",
  panelSoft: "#202020",
  black: C.text,
  white: C.white,
  borderDark: C.borderGreen,
  muted: C.muted,
  mutedDark: C.mutedInverse,
  darkMuted: C.mutedInverse,
};

export const games = createWebStyles({
  page: { backgroundColor: "transparent", backgroundImage: "none" as any, minHeight: "100%" as any, overscrollBehavior: "none" as any },
  pageApp: { backgroundColor: "#F5F8FA" },
  pageInner: { paddingHorizontal: 32, paddingTop: 32, paddingBottom: 10 },
  pageInnerApp: { paddingTop: 22 },
  pageInnerMobile: { paddingHorizontal: 14, paddingTop: 18, paddingBottom: 12, overflowX: "hidden" as any, backgroundColor: "transparent", backgroundImage: "none" as any },

  searchBar: {
    width: 360,
    maxWidth: "100%" as any,
    position: "relative" as any,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.10)",
    borderRadius: RADIUS.sm,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  searchBarFocus: { borderColor: T.orange },
  searchBarApp: {
    width: "100%" as any,
    backgroundColor: "#F7FBFD",
    borderColor: "rgba(20,42,58,0.10)",
    borderRadius: 999,
  },
  searchBarFocusApp: { borderColor: "#0F7EA8" },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: T.white,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    outlineStyle: "none" as any,
  },
  searchInputApp: { color: "#172A38" },
  searchInputMobile: { fontSize: 16 },
  clearSearch: { width: 20, height: 20, alignItems: "center", justifyContent: "center" },

  featured: {
    backgroundColor: "#4848BE",
    backgroundImage: "linear-gradient(135deg, #2E2E96 0%, #4848BE 100%)" as any,
    borderRadius: RADIUS.md,
    paddingHorizontal: 32,
    paddingVertical: 28,
    marginBottom: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 24,
    borderWidth: 1,
    borderColor: "rgba(91,91,214,0.25)",
    boxShadow: SHADOW.md as any,
  },
  featuredMobile: { flexDirection: "column", alignItems: "flex-start", paddingHorizontal: 22 },
  featuredEyebrowRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10, flexWrap: "wrap" as any },
  eyebrow: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, letterSpacing: 1.2, textTransform: "uppercase" as any, color: "rgba(255,255,255,0.50)" },
  hotPill: { backgroundColor: "rgba(255,215,0,0.15)", borderRadius: 6, paddingHorizontal: 9, paddingVertical: 2 },
  hotText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "700" as const, color: "#FFD700" },
  featuredTitle: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 34, fontWeight: "900" as const, color: T.white, lineHeight: 39 },
  featuredText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: "rgba(255,255,255,0.62)", lineHeight: 23, maxWidth: 420, marginTop: 10, marginBottom: 20 },
  featuredBtn: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 1.5, borderColor: "rgba(255,255,255,0.25)", borderRadius: RADIUS.sm, paddingHorizontal: 22, paddingVertical: 11 },
  featuredBtnText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "700" as const, color: T.white },
  featuredOrb: { width: 140, height: 140, borderRadius: 70, backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  featuredOrbInner: { width: 96, height: 96, borderRadius: 48, backgroundColor: "rgba(255,255,255,0.08)", alignItems: "center", justifyContent: "center" },

  searchMeta: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: T.mutedDark, marginBottom: 20 },
  searchMetaStrong: { color: T.white, fontWeight: "700" as const },
  searchGrid: { flexDirection: "row", flexWrap: "wrap" as any, gap: 12 },
  searchGridMobile: { flexDirection: "column", flexWrap: "nowrap" as any, gap: 10 },
  searchResultCard: {
    width: "100%" as any,
    minHeight: 104,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: T.panel,
    borderWidth: 1,
    borderColor: T.borderDark,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    boxShadow: "0 18px 44px rgba(0,0,0,0.18)" as any,
  },
  searchResultIcon: { width: 46, height: 46, borderRadius: 14, alignItems: "center", justifyContent: "center", flexShrink: 0 },
  searchResultContent: { flex: 1, minWidth: 0, gap: 3 },
  searchResultTop: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 1 },
  searchResultCategory: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, fontWeight: "800" as const, letterSpacing: 1, textTransform: "uppercase" as any, color: T.mutedDark },
  searchResultBadge: { borderRadius: 6, paddingHorizontal: 7, paddingVertical: 2, marginLeft: "auto" as any },
  searchResultBadgeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, fontWeight: "800" as const, textTransform: "uppercase" as any },
  searchResultTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 22, fontWeight: "700" as const, color: T.white, lineHeight: 24 },
  searchResultDesc: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: T.mutedDark, lineHeight: 17 },
  searchResultFavourite: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: T.borderDark,
    backgroundColor: T.panelSoft,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  searchResultFavouriteActive: { backgroundColor: T.orange, borderColor: T.orange },
  emptyState: { alignItems: "center", paddingVertical: 60, paddingHorizontal: 20, backgroundColor: T.panel, borderRadius: 14, borderWidth: 1, borderColor: T.borderDark },
  emptyText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: T.muted },

  carouselSection: { marginBottom: 24, backgroundColor: "transparent", backgroundImage: "none" as any },
  carouselSectionCompact: { backgroundColor: "transparent", backgroundImage: "none" as any },
  rowHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 16 },
  rowMarker: { width: 3, height: 20, borderRadius: 2 },
  rowTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 24, fontWeight: "700" as const, color: T.white },
  rowTitleWebLight: { fontFamily: "DM Sans, system-ui, sans-serif" as any, color: "#121212" },
  rowTitleApp: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 22, fontWeight: "900" as const, color: "#172A38" },
  rowCount: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: T.darkMuted },
  rowCountWebLight: { color: "#7A7A7A" },
  rowCountApp: { color: "#7A8A95" },
  carouselShell: {
    minHeight: 600,
    borderRadius: RADIUS.xl,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: T.borderDark,
    boxShadow: "0 18px 44px rgba(0,0,0,0.18)" as any,
    flexDirection: "row",
  },
  carouselShellWebLight: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(18,18,18,0.08)",
    boxShadow: "0 18px 44px rgba(18,18,18,0.08)" as any,
  },
  carouselShellApp: {
    borderColor: "rgba(20,42,58,0.08)",
    boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any,
  },
  carouselShellCompact: {
    width: "100%" as any,
    maxWidth: "100%" as any,
    flexDirection: "column",
    minHeight: 0,
    touchAction: "pan-y" as any,
    backgroundColor: "transparent",
    backgroundImage: "none" as any,
    borderColor: "transparent",
    borderWidth: 0,
    boxShadow: "none" as any,
  },
  categoryPanel: {
    width: "40%" as any,
    minWidth: 310,
    paddingHorizontal: 32,
    paddingVertical: 44,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative" as any,
  },
  categoryPanelWebLight: {
    backgroundColor: "#FFFFFF",
  },
  categoryPanelWebPoster: {
    backgroundColor: "#FFFFFF",
    minWidth: 390,
    paddingHorizontal: 34,
    paddingVertical: 42,
    overflow: "hidden",
  },
  categoryPanelApp: {
    borderWidth: 1,
    borderColor: "rgba(20,42,58,0.08)",
    boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any,
  },
  categoryPanelCompact: {
    width: "100%" as any,
    minWidth: 0,
    minHeight: 430,
    paddingHorizontal: 22,
    paddingVertical: 28,
    borderRadius: RADIUS.xl,
  },
  categoryBgImage: {
    opacity: 0.72,
  },
  categoryBgImageWebLight: {
    opacity: 0,
    objectFit: "contain" as any,
    objectPosition: "right center" as any,
  },
  categoryBgImageWebPoster: {
    opacity: 0,
    objectFit: "cover" as any,
    objectPosition: "right center" as any,
    transform: [{ scale: 1.01 }],
  },
  categoryPosterArtworkClip: {
    position: "absolute" as any,
    top: 18,
    left: 18,
    right: 18,
    bottom: 18,
    borderRadius: 24,
    overflow: "hidden",
    zIndex: 1,
  },
  categoryPosterArtwork: {
    position: "absolute" as any,
    right: -96,
    bottom: -48,
    width: "122%" as any,
    height: "118%" as any,
    opacity: 0.86,
    zIndex: 1,
  },
  categoryBgImageCompact: { opacity: 0.74 },
  categoryBgImageNativeFit: { opacity: 0.92 },
  categoryBgWash: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(47,44,127,0.42)",
    backgroundImage: "linear-gradient(90deg, rgba(12,10,18,0.72) 0%, rgba(47,44,127,0.58) 48%, rgba(91,91,214,0.34) 100%)" as any,
  },
  categoryBgWashWebLight: {
    backgroundColor: "transparent",
    backgroundImage: "linear-gradient(90deg, rgba(255,255,255,0.98) 0%, rgba(255,255,255,0.84) 48%, rgba(255,255,255,0.08) 100%)" as any,
    zIndex: 1,
  },
  categoryBgWashWebPoster: {
    backgroundColor: "transparent",
    backgroundImage: [
      "linear-gradient(90deg, rgba(255,255,255,0.94) 0%, rgba(255,255,255,0.70) 42%, rgba(255,255,255,0.06) 100%)",
      "linear-gradient(180deg, rgba(255,255,255,0.02) 0%, rgba(255,255,255,0.00) 52%, rgba(255,255,255,0.18) 100%)",
    ].join(", ") as any,
    zIndex: 2,
  },
  categoryPosterGlow: {
    position: "absolute" as any,
    left: 0,
    right: 0,
    bottom: 0,
    height: "42%" as any,
    backgroundImage: "linear-gradient(0deg, rgba(255,255,255,0.34) 0%, rgba(255,255,255,0.00) 100%)" as any,
    zIndex: 2,
  },
  categoryPosterFrame: {
    position: "absolute" as any,
    inset: 18,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: 24,
    zIndex: 3,
  },
  categoryBgWashApp: {
    backgroundColor: "rgba(255,255,255,0.56)",
    backgroundImage: "none" as any,
  },
  categoryContent: { position: "relative" as any, zIndex: 4 },
  categoryContentWebPoster: {
    maxWidth: 330,
    justifyContent: "center",
  },
  categoryHero: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.30)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 18,
  },
  categoryImage: { width: "100%" as any, height: "100%" as any },
  categoryTypeImage: {
    width: 190,
    height: 220,
    marginBottom: 22,
    alignSelf: "flex-start",
  },
  categoryHeroWebPoster: {
    width: 58,
    height: 58,
    borderRadius: 20,
    marginBottom: 20,
    backgroundColor: "rgba(255,255,255,0.74)",
    borderColor: "rgba(18,18,18,0.10)",
    backdropFilter: "blur(12px)" as any,
    WebkitBackdropFilter: "blur(12px)" as any,
  },
  categoryHeroEmoji: { fontSize: 34, lineHeight: 42 },
  categoryTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 34, fontWeight: "700" as const, color: T.white },
  categoryTitleWebLight: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontWeight: "900" as const, color: "#121212" },
  categoryTitleWebPoster: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 38,
    fontWeight: "900" as const,
    lineHeight: 42,
    color: "#121212",
    textShadow: "0 10px 28px rgba(255,255,255,0.72)" as any,
  },
  categoryTitleApp: { fontFamily: "DM Sans, system-ui, sans-serif" as any, color: "#172A38", fontSize: 30, fontWeight: "900" as const },
  categorySub: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, color: "rgba(255,255,255,0.68)", lineHeight: 20, marginTop: 8, marginBottom: 22 },
  categorySubWebLight: { color: "#5F5F5F" },
  categorySubWebPoster: {
    color: "#4B5563",
    fontSize: 14,
    lineHeight: 22,
    maxWidth: 300,
    textShadow: "0 8px 24px rgba(255,255,255,0.82)" as any,
  },
  categorySubApp: { color: "#607482" },
  pillWrap: { flexDirection: "row", flexWrap: "wrap" as any, gap: 10 },
  pillWrapVertical: { flexDirection: "column", flexWrap: "nowrap" as any, alignItems: "flex-start", gap: 12 },
  categoryPill: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 999, borderWidth: 1, borderColor: "rgba(255,255,255,0.24)", paddingHorizontal: 18, paddingVertical: 10 },
  categoryPillWebLight: { borderColor: "rgba(18,18,18,0.12)", backgroundColor: "rgba(255,255,255,0.82)" },
  categoryPillWebPoster: {
    minWidth: 210,
    borderColor: "rgba(18,18,18,0.12)",
    backgroundColor: "rgba(255,255,255,0.62)",
    backdropFilter: "blur(16px)" as any,
    WebkitBackdropFilter: "blur(16px)" as any,
  },
  categoryPillApp: { borderColor: "rgba(20,42,58,0.10)", backgroundColor: "#F7FBFD" },
  categoryPillActive: { backgroundColor: "rgba(255,255,255,0.96)", borderColor: "rgba(255,255,255,0.96)" },
  categoryPillActiveWebPoster: {
    backgroundColor: "rgba(255,255,255,0.94)",
    borderColor: "rgba(255,255,255,0.94)",
    boxShadow: "0 14px 34px rgba(18,18,18,0.12)" as any,
  },
  categoryPillActiveApp: { borderColor: "rgba(20,42,58,0.10)" },
  categoryPillText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "700" as const, letterSpacing: 0.5, textTransform: "uppercase" as any, color: "rgba(255,255,255,0.70)" },
  categoryPillTextWebLight: { color: "#5F5F5F" },
  categoryPillTextWebPoster: { color: "#2A2A2A" },
  categoryPillTextApp: { color: "#607482" },
  categoryPillTextActive: { color: T.black },
  cardRail: {
    flex: 1,
    minHeight: 520,
    position: "relative" as any,
    backgroundColor: "transparent",
    backgroundImage: "none" as any,
    paddingHorizontal: 24,
    paddingVertical: 28,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  cardRailBackdrop: {
    position: "absolute" as any,
    inset: 0,
    backgroundColor: "transparent",
    backgroundImage: "none" as any,
    zIndex: 0,
  },
  cardRailCompact: {
    width: "100%" as any,
    maxWidth: "100%" as any,
    minHeight: 400,
    paddingHorizontal: 0,
    paddingTop: 18,
    paddingBottom: 0,
    alignItems: "stretch",
    backgroundColor: "transparent",
    backgroundImage: "none" as any,
    overflow: "hidden",
  },
  cardRailScroller: {
    width: "100%" as any,
    maxWidth: "100%" as any,
    position: "relative" as any,
    zIndex: 1,
    backgroundColor: "transparent",
    backgroundImage: "none" as any,
    overflowX: "auto" as any,
    overflowY: "hidden" as any,
    touchAction: "pan-x pan-y" as any,
    overscrollBehaviorX: "contain" as any,
    overscrollBehaviorY: "auto" as any,
  },
  cardRailScroll: { gap: 18, backgroundColor: "transparent", backgroundImage: "none" as any },
  cardRailScrollCompact: { paddingLeft: 28, paddingRight: 28, paddingBottom: 2, backgroundColor: "transparent", backgroundImage: "none" as any },
  cardStack: { width: 360, height: 480, position: "relative" as any, alignItems: "center", justifyContent: "center" },

  gameCard: { width: 290, height: 400, backgroundColor: "#1A1614", borderRadius: 22, overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,255,255,0.06)", boxShadow: "0 24px 70px rgba(0,0,0,0.18)" as any, backfaceVisibility: "hidden" as any, transformStyle: "preserve-3d" as any, willChange: "transform, opacity" as any },
  gameCardApp: { backgroundColor: "#FFFFFF", borderColor: "rgba(20,42,58,0.08)", boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any },
  stackedGameCard: { position: "absolute" as any, top: 40, left: 35 },
  gameCardLocked: { opacity: 0.58 },
  artZone: { height: 170, position: "relative" as any, overflow: "hidden", backgroundColor: "#2A2420" },
  artZoneApp: { backgroundColor: "#F1F8FB" },
  artStripe: { position: "absolute" as any, inset: 0, opacity: 0.18, backgroundImage: "repeating-linear-gradient(135deg, rgba(0,0,0,0.34) 0 2px, transparent 2px 12px)" as any },
  artWash: { position: "absolute" as any, inset: 0 },
  artPatternRow: { position: "absolute" as any, inset: 0, flexDirection: "row", flexWrap: "wrap" as any, gap: 18, padding: 18, opacity: 0.18 },
  artPatternMark: { color: T.white, fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 22, fontWeight: "700" as const },
  artIcon: { position: "absolute" as any, top: 18, left: 20, width: 50, height: 50, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.14)", borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },
  artIconApp: { backgroundColor: "rgba(255,255,255,0.84)", borderColor: "rgba(20,42,58,0.08)" },
  favouriteBtn: { position: "absolute" as any, top: 18, right: 14, width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(0,0,0,0.28)", borderWidth: 1, borderColor: "rgba(255,255,255,0.14)", alignItems: "center", justifyContent: "center", zIndex: 4 },
  favouriteBtnActive: { backgroundColor: C.orange, borderColor: C.orange },
  cardEmojiBadge: { position: "absolute" as any, left: 18, bottom: 12, width: 40, height: 40, borderRadius: 14, backgroundColor: "rgba(0,0,0,0.24)", borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", alignItems: "center", justifyContent: "center" },
  cardEmojiText: { fontSize: 20, lineHeight: 26 },
  artLabel: { position: "absolute" as any, right: 12, bottom: 10, backgroundColor: "rgba(0,0,0,0.35)", borderWidth: 1, borderColor: "rgba(255,255,255,0.10)", borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  artLabelText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, color: "rgba(255,255,255,0.48)", letterSpacing: 0.6 },
  badgeStack: { position: "absolute" as any, top: 58, right: 12, gap: 4, alignItems: "flex-end" },
  smallBadge: { borderRadius: 5, paddingHorizontal: 7, paddingVertical: 2, borderWidth: 1 },
  smallBadgeText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, fontWeight: "800" as const, letterSpacing: 0.6, textTransform: "uppercase" as any },
  cardBody: { flex: 1, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 18, gap: 8 },
  cardBodyApp: { backgroundColor: "#FFFFFF" },
  cardKickerRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  cardKicker: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 9, fontWeight: "800" as const, letterSpacing: 1.2, textTransform: "uppercase" as any },
  cardRule: { flex: 1, height: 1 },
  cardTitle: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 27, fontWeight: "700" as const, color: "#F5EFE3", lineHeight: 29, minHeight: 58 },
  cardTitleApp: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 23, fontWeight: "900" as const, color: "#172A38", lineHeight: 28 },
  cardDesc: { flex: 1, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: "rgba(245,239,227,0.52)", lineHeight: 20 },
  cardDescApp: { color: "#607482" },
  cardMeta: { flexDirection: "row", alignItems: "center", gap: 7 },
  diffBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  diffText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 10, fontWeight: "800" as const, letterSpacing: 0.4, textTransform: "uppercase" as any },
  duration: { marginLeft: "auto" as any, flexDirection: "row", alignItems: "center", gap: 4 },
  durationText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 11, color: "rgba(245,239,227,0.42)" },
  durationTextApp: { color: "#7A8A95" },
  playButton: { width: "100%" as any, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 11, borderWidth: 1, paddingVertical: 10, marginTop: "auto" as any },
  playButtonText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "800" as const },
});
