import { createWebStyles } from "../web";
import { C, RADIUS, SHADOW } from "../tokens";

const white = C.white;
const orange = C.orange;
const darkBorder = C.borderGreen;
const muted = C.mutedInverse;
const black = C.text;
const body = C.body;
const border = C.border;

export const game = createWebStyles({
  page: {
    minHeight: "100%" as any,
    backgroundColor: "#F7F1E8",
    backgroundImage: "linear-gradient(135deg, rgba(255,250,242,0.96) 0%, #F3EDE1 58%, #ECE4D7 100%)" as any,
    paddingHorizontal: 32,
    paddingTop: 30,
    paddingBottom: 46,
  },
  heroBand: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    marginBottom: 22,
  },
  heroCopy: { flex: 1 },
  eyebrowRow: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" as any, marginBottom: 8 },
  eyebrow: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.4,
    textTransform: "uppercase" as any,
    color: "rgba(18,18,18,0.48)",
  },
  phasePill: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  phaseText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 0.3,
  },
  title: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 40,
    fontWeight: "700" as const,
    lineHeight: 44,
    color: black,
  },
  subtitle: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    color: "rgba(18,18,18,0.58)",
    lineHeight: 22,
    maxWidth: 620,
    marginTop: 8,
  },
  heroIcon: {
    width: 76,
    height: 76,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  stage: {
    position: "relative" as any,
    overflow: "hidden",
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.08)",
    backgroundColor: "rgba(255,255,255,0.58)",
    boxShadow: "0 18px 48px rgba(18,18,18,0.08)" as any,
    padding: 24,
  },
  stageGlow: {
    position: "absolute" as any,
    top: -120,
    right: -100,
    width: 330,
    height: 330,
    borderRadius: 165,
    backgroundColor: "rgba(91,91,214,0.10)",
  },
  backButton: {
    alignSelf: "flex-start",
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.12)",
    borderRadius: RADIUS.sm,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: "rgba(255,255,255,0.74)",
  },
  backButtonText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "700" as const, color: body },

  focusOverlay: {
    position: "fixed" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 320,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  focusBlur: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(8,8,8,0.42)",
    backdropFilter: "blur(12px)" as any,
    WebkitBackdropFilter: "blur(12px)" as any,
  },
  focusCard: {
    width: "min(92vw, 960px)" as any,
    maxHeight: "88vh" as any,
    position: "relative" as any,
    zIndex: 2,
    overflow: "auto" as any,
  },
  backgroundPanel: {
    opacity: 0.72,
    transform: [{ scale: 0.985 }],
  },

  countdownPanel: {
    minHeight: 460,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(4,6,15,0.88)",
    boxShadow: "0 28px 90px rgba(0,0,0,0.34)" as any,
    paddingHorizontal: 28,
    paddingVertical: 38,
  },
  countdownKicker: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    letterSpacing: 1.4,
    textTransform: "uppercase" as any,
    color: "rgba(255,255,255,0.48)",
  },
  countdownNumber: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 138,
    fontWeight: "700" as const,
    lineHeight: 150,
    color: white,
    marginTop: 12,
    marginBottom: 18,
  },
  countdownText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    color: "rgba(255,255,255,0.58)",
    lineHeight: 22,
    textAlign: "center",
  },

  panel: {
    position: "relative" as any,
    zIndex: 2,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: 18,
    padding: 24,
    boxShadow: "0 28px 90px rgba(0,0,0,0.24)" as any,
    gap: 22,
  },
  playPanel: {
    position: "relative" as any,
    zIndex: 2,
    minHeight: 560,
    justifyContent: "space-between",
    backgroundColor: "rgba(4,6,15,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.11)",
    borderRadius: RADIUS.lg,
    padding: 24,
  },
  panelHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 16 },
  kicker: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.3,
    textTransform: "uppercase" as any,
    color: orange,
    marginBottom: 6,
  },
  panelTitle: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 32,
    fontWeight: "700" as const,
    lineHeight: 36,
    color: black,
  },
  settingsIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#161616",
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  settingsGrid: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))" as any,
    gap: 14,
  },
  settingBlock: {
    backgroundColor: "#F7F7F7",
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.md,
    padding: 16,
    gap: 10,
  },
  settingBlockWide: {
    gridColumn: "1 / -1" as any,
    backgroundColor: "#F7F7F7",
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.md,
    padding: 16,
    gap: 10,
  },
  fieldLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color: "#6A6A6A",
  },
  fieldHint: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: "#7A7A7A", lineHeight: 18 },
  segmented: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap" as any,
  },
  segment: {
    minWidth: 58,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.sm,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: white,
  },
  segmentActive: { backgroundColor: orange, borderColor: orange },
  segmentText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: body,
    textTransform: "capitalize" as any,
  },
  segmentTextActive: { color: white },
  rangeRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  inlineInputRow: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" as any },
  numberInput: {
    width: 92,
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.sm,
    backgroundColor: white,
    color: black,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 15,
    fontWeight: "800" as const,
    paddingHorizontal: 12,
    paddingVertical: 10,
    outlineStyle: "none" as any,
  },
  rangeDivider: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, color: "#7A7A7A" },
  primaryButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: RADIUS.sm,
    backgroundColor: orange,
    paddingHorizontal: 22,
    paddingVertical: 13,
    boxShadow: SHADOW.glow as any,
  },
  primaryButtonInline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderRadius: RADIUS.sm,
    backgroundColor: orange,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  primaryButtonText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, fontWeight: "800" as const, color: white },
  buttonDisabled: { opacity: 0.42 },

  playTimerRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  timerText: {
    minWidth: 46,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: "rgba(255,255,255,0.58)",
    textAlign: "right",
  },
  playTop: { flexDirection: "row", gap: 12, flexWrap: "wrap" as any },
  statTile: {
    flex: 1,
    minWidth: 150,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: darkBorder,
    borderRadius: RADIUS.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  statTileLight: {
    backgroundColor: "#F7F7F7",
    borderColor: "rgba(18,18,18,0.10)",
  },
  statValue: { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 30, fontWeight: "700" as const, color: white, lineHeight: 32 },
  statValueLight: { color: black },
  statLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color: muted,
    marginTop: 4,
  },
  statLabelLight: { color: "#6A6A6A" },
  progressTrack: { flex: 1, height: 6, borderRadius: 999, overflow: "hidden", backgroundColor: "rgba(255,255,255,0.08)" },
  progressFill: { height: "100%" as any, borderRadius: 999, backgroundColor: orange },
  numberStage: {
    minHeight: 270,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.045)",
  },
  numberDisplay: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 108,
    fontWeight: "700" as const,
    lineHeight: 116,
    color: white,
  },
  pauseCurtain: { alignItems: "center", justifyContent: "center", gap: 12 },
  pauseText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 15, fontWeight: "800" as const, color: white },
  manualControls: { flexDirection: "row", justifyContent: "center", gap: 12, marginTop: 18 },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: darkBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  controlRow: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" as any },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.14)",
    borderRadius: RADIUS.sm,
    backgroundColor: "#161616",
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  secondaryButtonText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 13, fontWeight: "800" as const, color: white },
  endButton: { backgroundColor: "rgba(255,118,90,0.12)", borderColor: "rgba(255,118,90,0.28)" },

  recallSummary: { flexDirection: "row", gap: 12, flexWrap: "wrap" as any },
  recallGrid: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(auto-fill, minmax(78px, 1fr))" as any,
    gap: 10,
    maxHeight: 300,
    overflow: "auto" as any,
    paddingRight: 4,
  },
  recallBoxWrap: {
    position: "relative" as any,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.13)",
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(0,0,0,0.24)",
    paddingHorizontal: 9,
    paddingTop: 19,
    paddingBottom: 9,
  },
  recallBoxIndex: {
    position: "absolute" as any,
    top: 6,
    left: 9,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 9,
    fontWeight: "800" as const,
    color: "rgba(255,255,255,0.34)",
  },
  recallBoxInput: {
    width: "100%" as any,
    color: white,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 22,
    fontWeight: "800" as const,
    textAlign: "center",
    paddingVertical: 3,
    outlineStyle: "none" as any,
  },
  recallInput: {
    minHeight: 170,
    textAlignVertical: "top" as any,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.13)",
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(0,0,0,0.24)",
    color: white,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 18,
    lineHeight: 28,
    padding: 16,
    outlineStyle: "none" as any,
  },
  resultStats: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))" as any,
    gap: 12,
  },
  answerList: { gap: 8 },
  answerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  answerRowGood: { borderColor: "rgba(125,236,212,0.22)", backgroundColor: "rgba(42,157,143,0.10)" },
  answerRowBad: { borderColor: "rgba(255,140,117,0.22)", backgroundColor: "rgba(255,118,90,0.10)" },
  answerIndex: { width: 34, fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 12, fontWeight: "800" as const, color: "#6A6A6A" },
  answerCol: { flex: 1 },
  answerLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 10,
    fontWeight: "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color: "#6A6A6A",
  },
  answerValue: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 16, fontWeight: "800" as const, color: black, marginTop: 2 },
  emptyText: { fontFamily: "DM Sans, system-ui, sans-serif" as any, fontSize: 14, color: "#6A6A6A", lineHeight: 22 },
});
