import { createWebStyles } from "../web";
import { C, RADIUS, SHADOW } from "../tokens";

const white = C.white;
const orange = C.orange;
const darkBorder = C.borderGreen;
const muted = C.mutedInverse;
const black = C.text;
const body = C.body;
const border = C.border;

export const game = createWebStyles({
  page: {
    backgroundColor: "transparent",
    backgroundImage: "none" as any,
    paddingHorizontal: 32,
    paddingTop: 30,
    paddingBottom: 24,
  },
  pageApp: { backgroundColor: "#F5F8FA" },
  pageMobile: {
    width: "100%" as any,
    maxWidth: "100vw" as any,
    overflowX: "hidden" as any,
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 18,
    boxSizing: "border-box" as any,
  },
  heroBand: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    marginBottom: 22,
  },
  heroBandMobile: { gap: 12, marginBottom: 16, alignItems: "flex-start" },
  heroCopy: { flex: 1 },
  heroCopyMobile: { minWidth: 0 },
  backLink: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 14,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: orange,
    boxShadow: "0 7px 18px rgba(232,93,42,0.22)" as any,
  },
  backLinkText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    color: white,
  },
  eyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap" as any,
    marginBottom: 8,
  },
  eyebrow: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.4,
    textTransform: "uppercase" as any,
    color: "#0F7EA8",
  },
  phasePill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  phaseText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 0.3,
  },
  title: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 40,
    fontWeight: "900" as const,
    lineHeight: 44,
    color: "#172A38",
  },
  titleMobile: { fontSize: 33, lineHeight: 36 },
  subtitle: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    color: "#607482",
    lineHeight: 22,
    maxWidth: 620,
    marginTop: 8,
  },
  subtitleMobile: { fontSize: 13, lineHeight: 20, marginTop: 6 },
  heroIcon: {
    width: 76,
    height: 76,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  heroIconMobile: { width: 56, height: 56, borderRadius: 18, flexShrink: 0 },
  heroArtwork: { width: "76%" as any, height: "76%" as any },
  stage: {
    position: "relative" as any,
    overflow: "hidden",
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: darkBorder,
    backgroundColor: "rgba(22,22,22,0.92)",
    boxShadow: "0 18px 44px rgba(0,0,0,0.18)" as any,
    padding: 24,
  },
  stageApp: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(20,42,58,0.08)",
    boxShadow: "0 16px 34px rgba(31,61,80,0.07)" as any,
  },
  stageMobile: {
    width: "100%" as any,
    maxWidth: "100%" as any,
    padding: 12,
    borderRadius: 18,
    boxSizing: "border-box" as any,
    touchAction: "pan-y" as any,
  },
  stageGlow: {
    position: "absolute" as any,
    top: -120,
    right: -100,
    width: 330,
    height: 330,
    borderRadius: 165,
    backgroundColor: "rgba(91,91,214,0.10)",
  },
  focusOverlay: {
    position: "fixed" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 320,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  focusOverlayMobile: { padding: 10 },
  focusBlur: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(8,8,8,0.42)",
    backdropFilter: "blur(12px)" as any,
    WebkitBackdropFilter: "blur(12px)" as any,
  },
  focusCard: {
    width: "min(92vw, 960px)" as any,
    maxHeight: "88vh" as any,
    position: "relative" as any,
    zIndex: 2,
    overflow: "auto" as any,
    overscrollBehavior: "contain" as any,
    WebkitOverflowScrolling: "touch" as any,
  },
  focusCardMobile: {
    width: "calc(100vw - 20px)" as any,
    maxHeight: "calc(100vh - 20px)" as any,
  },
  focusOverlayNative: {
    flex: 1,
    backgroundColor: "rgba(8,8,8,0.74)",
  },
  focusSafeAreaNative: {
    flex: 1,
  },
  focusScrollNative: {
    flex: 1,
  },
  focusScrollContentNative: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  focusCardNative: {
    width: "100%" as any,
    position: "relative" as any,
    zIndex: 2,
  },
  focusCardNativeMobile: {
    width: "100%" as any,
  },
  focusCloseRow: {
    width: "100%" as any,
    minHeight: 52,
    alignItems: "flex-end",
    justifyContent: "center",
    position: "relative" as any,
    zIndex: 3,
  },
  focusCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(18,18,18,0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    boxShadow: "0 8px 24px rgba(0,0,0,0.28)" as any,
  },
  backgroundPanel: {
    opacity: 0.72,
    transform: [{ scale: 0.985 }],
  },

  sessionPanel: {
    position: "relative" as any,
    zIndex: 2,
    overflow: "hidden",
    width: "100%" as any,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: 18,
    padding: 24,
    paddingTop: 28,
    boxShadow: "0 28px 90px rgba(0,0,0,0.24)" as any,
    gap: 22,
  },
  sessionPanelMobile: {
    maxWidth: "100%" as any,
    padding: 16,
    paddingTop: 20,
    borderRadius: 16,
    gap: 16,
    boxSizing: "border-box" as any,
    touchAction: "pan-y" as any,
  },
  sessionAccent: {
    position: "absolute" as any,
    top: 0,
    left: 0,
    right: 0,
    height: 4,
  },
  sessionSurface: {
    backgroundColor: "#F7F7F7",
    borderColor: "rgba(18,18,18,0.10)",
  },
  countdownPanel: {
    minHeight: 460,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingVertical: 38,
  },
  countdownPanelMobile: {
    minHeight: 520,
    paddingHorizontal: 18,
    paddingVertical: 30,
  },
  countdownKicker: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    letterSpacing: 1.4,
    textTransform: "uppercase" as any,
    color: "#6A6A6A",
  },
  countdownNumber: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 138,
    fontWeight: "700" as const,
    lineHeight: 150,
    color: black,
    marginTop: 12,
    marginBottom: 18,
  },
  countdownNumberMobile: { fontSize: 116, lineHeight: 124 },
  countdownText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    color: "#7A7A7A",
    lineHeight: 22,
    textAlign: "center",
  },

  panel: {
    position: "relative" as any,
    zIndex: 2,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: 18,
    padding: 24,
    boxShadow: "0 28px 90px rgba(0,0,0,0.24)" as any,
    gap: 22,
  },
  panelMobile: {
    width: "100%" as any,
    maxWidth: "100%" as any,
    padding: 16,
    borderRadius: 16,
    gap: 16,
    boxSizing: "border-box" as any,
    touchAction: "pan-y" as any,
  },
  resultPanelMobile: {},
  playPanel: {
    minHeight: 560,
    justifyContent: "space-between",
  },
  playPanelMobile: {
    minHeight: 560,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  panelHeaderMobile: { alignItems: "center", gap: 10 },
  panelHeaderCopyMobile: { flex: 1, minWidth: 0, paddingRight: 8 },
  kicker: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.3,
    textTransform: "uppercase" as any,
    color: orange,
    marginBottom: 6,
  },
  panelTitle: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 32,
    fontWeight: "700" as const,
    lineHeight: 36,
    color: black,
  },
  panelTitleMobile: { fontSize: 26, lineHeight: 30 },
  setupDescription: {
    marginTop: 6,
    maxWidth: 620,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    lineHeight: 19,
    color: muted,
  },
  settingsIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#161616",
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  settingsIconMobile: {
    width: 38,
    height: 38,
    borderRadius: 12,
    flexShrink: 0,
  },
  settingsGrid: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))" as any,
    gap: 14,
  },
  settingsGridMobile: {
    display: "flex" as any,
    flexDirection: "column",
    gap: 12,
    touchAction: "pan-y" as any,
  },
  settingBlock: {
    backgroundColor: "#F7F7F7",
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.md,
    padding: 16,
    gap: 10,
  },
  settingBlockMobile: {
    width: "100%" as any,
    maxWidth: "100%" as any,
    padding: 14,
    borderRadius: 16,
    boxSizing: "border-box" as any,
  },
  settingBlockWide: {
    gridColumn: "1 / -1" as any,
    backgroundColor: "#F7F7F7",
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.md,
    padding: 16,
    gap: 10,
  },
  settingBlockWideMobile: {
    gridColumn: "auto" as any,
    width: "100%" as any,
    maxWidth: "100%" as any,
    padding: 14,
    borderRadius: 16,
    boxSizing: "border-box" as any,
  },
  fieldLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color: "#6A6A6A",
  },
  fieldHint: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    color: "#7A7A7A",
    lineHeight: 18,
  },
  fieldHintMobile: { fontSize: 11, lineHeight: 16 },
  segmented: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap" as any,
  },
  segmentedMobile: { width: "100%" as any, flexWrap: "wrap" as any, gap: 7 },
  segment: {
    minWidth: 58,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.sm,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: white,
  },
  segmentMobile: {
    flex: 1,
    minWidth: 64,
    paddingHorizontal: 7,
    paddingVertical: 11,
  },
  segmentActive: { backgroundColor: orange, borderColor: orange },
  segmentText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: body,
    textTransform: "capitalize" as any,
  },
  segmentTextMobile: { fontSize: 12 },
  segmentTextActive: { color: white },
  rangeRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  rangeRowMobile: { width: "100%" as any, gap: 8 },
  inlineInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap" as any,
  },
  inlineInputRowMobile: {
    width: "100%" as any,
    flexWrap: "nowrap" as any,
    gap: 8,
  },
  smartSpeedBtn: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(232,93,42,0.24)",
    borderRadius: RADIUS.sm,
    backgroundColor: "rgba(232,93,42,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  smartSpeedBtnMobile: {
    width: "100%" as any,
    justifyContent: "center",
    boxSizing: "border-box" as any,
  },
  smartSpeedText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    color: orange,
  },
  numberInput: {
    width: 92,
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.sm,
    backgroundColor: white,
    color: black,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 15,
    fontWeight: "800" as const,
    paddingHorizontal: 12,
    paddingVertical: 10,
    outlineStyle: "none" as any,
  },
  numberInputMobile: {
    flex: 1,
    width: "auto" as any,
    minWidth: 0,
    textAlign: "center",
    boxSizing: "border-box" as any,
  },
  rangeDivider: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    color: "#7A7A7A",
  },
  rangeDividerMobile: { flexShrink: 0 },
  primaryButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: RADIUS.sm,
    backgroundColor: orange,
    paddingHorizontal: 22,
    paddingVertical: 13,
    boxShadow: SHADOW.glow as any,
  },
  primaryButtonMobile: {
    width: "100%" as any,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  primaryButtonInline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    borderRadius: RADIUS.sm,
    backgroundColor: orange,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  primaryButtonInlineMobile: { flex: 1, minWidth: 0, paddingHorizontal: 8 },
  primaryButtonText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    fontWeight: "800" as const,
    color: white,
  },
  buttonDisabled: { opacity: 0.42 },

  gameStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    flexWrap: "wrap" as any,
  },
  gameTimerPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 7,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "900" as const,
  },
  challengeStage: {
    minHeight: 250,
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
    gap: 22,
    padding: 24,
  },
  challengePrompt: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 64,
    lineHeight: 72,
    fontWeight: "700" as const,
    color: black,
    textAlign: "center",
  },
  challengeInput: {
    width: 180,
    borderWidth: 2,
    borderRadius: RADIUS.md,
    backgroundColor: white,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 28,
    fontWeight: "900" as const,
    color: black,
    textAlign: "center",
    outlineStyle: "none" as any,
  },
  gameStatRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
    flexWrap: "wrap" as any,
  },
  gameStatText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    fontWeight: "800" as const,
    color: body,
  },
  reactionStage: {
    minHeight: 340,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: RADIUS.lg,
    backgroundColor: "#1A1A1A",
    alignItems: "center",
    justifyContent: "center",
    gap: 13,
    padding: 24,
  },
  reactionTitle: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "900" as const,
    color: white,
    textAlign: "center",
  },
  reactionHint: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    lineHeight: 20,
    color: "rgba(255,255,255,0.64)",
    textAlign: "center",
  },
  wordChipGrid: { flexDirection: "row", flexWrap: "wrap" as any, gap: 10 },
  wordChip: {
    minWidth: 126,
    flexGrow: 1,
    flexBasis: "22%" as any,
    borderWidth: 1,
    borderColor: border,
    borderRadius: RADIUS.md,
    backgroundColor: "#F7F7F7",
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  wordChipIndex: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 10,
    fontWeight: "900" as const,
    color: "#9A9A9A",
  },
  wordChipText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 16,
    fontWeight: "800" as const,
    color: black,
    textTransform: "capitalize" as any,
  },
  wordChipCorrect: {
    borderColor: "rgba(42,157,143,0.35)",
    backgroundColor: "rgba(42,157,143,0.09)",
  },
  wordChipMissed: { opacity: 0.48 },
  wordRecallInput: {
    minHeight: 190,
    width: "100%" as any,
    borderWidth: 2,
    borderRadius: RADIUS.md,
    backgroundColor: "#F7F7F7",
    padding: 18,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 17,
    lineHeight: 26,
    color: black,
    textAlignVertical: "top",
    outlineStyle: "none" as any,
  },
  wordDisplayStage: {
    minHeight: 300,
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  wordDisplayValue: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 72,
    lineHeight: 80,
    fontWeight: "700" as const,
    color: black,
    textAlign: "center",
    textTransform: "capitalize" as any,
  },
  wordDisplayValueMobile: { fontSize: 54, lineHeight: 62 },
  wordRecallGrid: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))" as any,
    gap: 10,
    maxHeight: 360,
    overflow: "auto" as any,
    paddingRight: 3,
  },
  wordRecallGridMobile: {
    display: "flex" as any,
    flexDirection: "column",
    maxHeight: 390,
    gap: 8,
  },
  wordRecallBox: {
    position: "relative" as any,
  },
  wordRecallIndex: {
    position: "absolute" as any,
    zIndex: 2,
    top: 12,
    left: 13,
    width: 22,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 10,
    fontWeight: "900" as const,
    color: "#8A8A8A",
  },
  wordRecallBoxInput: {
    width: "100%" as any,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    backgroundColor: "#F7F7F7",
    color: black,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 16,
    fontWeight: "800" as const,
    paddingLeft: 44,
    paddingRight: 13,
    paddingVertical: 11,
    outlineStyle: "none" as any,
    boxSizing: "border-box" as any,
  },

  sequenceGrid: {
    display: "grid" as any,
    width: "min(72vw, 430px)" as any,
    maxWidth: "100%" as any,
    alignSelf: "center",
    gap: 12,
  },
  sequenceTile: {
    aspectRatio: 1,
    minWidth: 0,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: "#ECECF8",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 120ms ease, transform 120ms ease" as any,
  },
  sequenceTileMobile: { borderRadius: 8 },

  chimpStatus: {
    width: "100%" as any,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: RADIUS.sm,
    backgroundColor: "#F7F7F7",
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: body,
  },
  chimpStatusCorrect: {
    borderColor: "rgba(42,157,143,0.30)",
    backgroundColor: "rgba(42,157,143,0.09)",
    color: "#237D72",
  },
  chimpStatusWrong: {
    borderColor: "rgba(232,93,63,0.32)",
    backgroundColor: "rgba(232,93,63,0.10)",
    color: "#C6472D",
  },
  chimpLives: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  chimpBoard: {
    width: "min(82vw, 680px)" as any,
    maxWidth: "100%" as any,
    alignSelf: "center",
    gap: 8,
    paddingVertical: 8,
  },
  chimpBoardMobile: { width: "100%" as any, gap: 5 },
  chimpRow: { width: "100%" as any, flexDirection: "row", gap: 8 },
  chimpRowMobile: { gap: 5 },
  chimpEmptyTile: { flex: 1, minWidth: 0, aspectRatio: 1 },
  chimpTile: {
    flex: 1,
    aspectRatio: 1,
    minWidth: 0,
    borderWidth: 2,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 120ms ease, transform 100ms ease" as any,
  },
  chimpTileMobile: { borderRadius: 7 },
  chimpTileWrong: {
    backgroundColor: "#E85D3F",
    borderColor: "#E85D3F",
    transform: [{ scale: 0.93 }],
  },
  chimpTileCorrect: {
    backgroundColor: "#2A9D8F",
    borderColor: "#2A9D8F",
    transform: [{ scale: 0.94 }],
  },
  chimpTileNumber: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "900" as const,
    textAlign: "center",
  },
  chimpTileNumberMobile: { fontSize: 17, lineHeight: 20 },

  cardProgressTrack: { backgroundColor: "rgba(18,18,18,0.08)" },
  cardStudyStage: {
    minHeight: 390,
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 22,
  },
  playingCardLarge: {
    width: 232,
    height: 337,
    borderRadius: 13,
    boxShadow: "0 18px 34px rgba(0,0,0,0.16)" as any,
  },
  playingCardLargeMobile: { width: 176, height: 256, borderRadius: 10 },
  cardStudyLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: body,
  },
  cardManualControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  cardManualHint: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "700" as const,
    color: "#6A6A6A",
    textAlign: "center",
  },
  cardRecallLayout: { gap: 14 },
  cardPlacementSection: {
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: RADIUS.lg,
    backgroundColor: "#F7F7F7",
    padding: 14,
    gap: 10,
  },
  cardSectionHeader: { gap: 3 },
  cardSectionHint: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    lineHeight: 16,
    color: "#777777",
  },
  cardPlacementScroll: { maxHeight: 330 },
  cardPlacementScrollMobile: { maxHeight: 310 },
  cardPlacementContent: { gap: 8, paddingRight: 3 },
  cardPlacementRow: { width: "100%" as any, flexDirection: "row", gap: 8 },
  cardPlacementRowMobile: { gap: 6 },
  cardRecallSlot: {
    flex: 1,
    minWidth: 0,
    aspectRatio: 0.688,
    position: "relative" as any,
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "rgba(18,18,18,0.13)",
    borderRadius: 8,
    backgroundColor: white,
    alignItems: "center",
    justifyContent: "center",
  },
  cardRecallSlotMobile: { borderRadius: 7 },
  cardRecallSlotImage: { width: "100%" as any, height: "100%" as any },
  cardSlotSpacer: { flex: 1, minWidth: 0, aspectRatio: 0.688 },
  cardSlotIndex: {
    position: "absolute" as any,
    top: 5,
    left: 6,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 9,
    fontWeight: "900" as const,
    color: "#9A9A9A",
  },
  cardTraySection: {
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: RADIUS.lg,
    backgroundColor: white,
    padding: 14,
    gap: 10,
  },
  cardTrayScroll: { maxHeight: 128 },
  cardTrayContent: { gap: 8, paddingRight: 6 },
  cardTrayCard: {
    width: 72,
    height: 105,
    position: "relative" as any,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.12)",
    borderRadius: 7,
    backgroundColor: white,
    overflow: "hidden",
  },
  cardTrayCardMobile: { width: 60, height: 87, borderRadius: 6 },
  cardTrayCardDisabled: { opacity: 0.22 },
  cardTrayImage: { width: "100%" as any, height: "100%" as any },
  cardCountBadge: {
    position: "absolute" as any,
    right: 3,
    bottom: 3,
    minWidth: 21,
    height: 21,
    paddingHorizontal: 5,
    borderRadius: 11,
    backgroundColor: "#161616",
    alignItems: "center",
    justifyContent: "center",
  },
  cardCountBadgeEmpty: { backgroundColor: "#8A8A8A" },
  cardCountText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 10,
    fontWeight: "900" as const,
    color: white,
  },
  cardResultList: { maxHeight: 410 },
  cardResultListMobile: { maxHeight: 370 },
  cardResultContent: { gap: 8, paddingRight: 3 },
  cardResultRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  cardResultRowMobile: { gap: 8, paddingHorizontal: 9 },
  cardResultPair: { flex: 1, flexDirection: "row", gap: 12 },
  cardResultCard: { flex: 1, minWidth: 0, alignItems: "center", gap: 4 },
  cardResultImage: { width: 54, height: 78, borderRadius: 5 },
  cardResultMissing: {
    width: 54,
    height: 78,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.12)",
    borderRadius: 5,
    backgroundColor: "rgba(255,255,255,0.54)",
    alignItems: "center",
    justifyContent: "center",
  },
  cardResultName: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "900" as const,
    color: body,
  },

  doomsdayStage: {
    position: "relative" as any,
    zIndex: 20,
    overflow: "visible" as any,
    minHeight: 330,
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    padding: 24,
  },
  doomsdayHint: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color: "#6A6A6A",
  },
  doomsdayDate: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 50,
    lineHeight: 58,
    fontWeight: "700" as const,
    color: black,
    textAlign: "center",
  },
  doomsdayDateMobile: { fontSize: 38, lineHeight: 45 },
  weekdayDropdownWrap: {
    width: "min(100%, 390px)" as any,
    position: "relative" as any,
    zIndex: 50,
  },
  weekdaySelect: {
    width: "100%" as any,
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 2,
    borderRadius: RADIUS.md,
    backgroundColor: white,
    paddingHorizontal: 16,
  },
  weekdaySelectText: {
    flex: 1,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 15,
    fontWeight: "800" as const,
    color: "#8A8A8A",
  },
  weekdayMenu: {
    position: "absolute" as any,
    top: 59,
    left: 0,
    right: 0,
    zIndex: 100,
    elevation: 20,
    width: "100%" as any,
    height: 174,
    maxHeight: 174,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: RADIUS.md,
    backgroundColor: white,
    overflow: "auto" as any,
    overscrollBehavior: "contain" as any,
    WebkitOverflowScrolling: "touch" as any,
    boxShadow: "0 16px 36px rgba(0,0,0,0.16)" as any,
  },
  weekdayMenuContent: { paddingVertical: 3 },
  weekdayOption: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(18,18,18,0.07)",
  },
  weekdayEmoji: { width: 26, fontSize: 17 },
  weekdayOptionText: {
    flex: 1,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    fontWeight: "800" as const,
    color: black,
  },

  playTimerRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  playTimerRowMobile: { gap: 10 },
  timerText: {
    minWidth: 46,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: "#6A6A6A",
    textAlign: "right",
  },
  playTop: { flexDirection: "row", gap: 12, flexWrap: "wrap" as any },
  statTile: {
    flex: 1,
    minWidth: 150,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: darkBorder,
    borderRadius: RADIUS.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  statTileMobile: {
    minWidth: 0,
    paddingHorizontal: 9,
    paddingVertical: 12,
    boxSizing: "border-box" as any,
  },
  statTileLight: {
    backgroundColor: "#F7F7F7",
    borderColor: "rgba(18,18,18,0.10)",
  },
  statValue: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 30,
    fontWeight: "700" as const,
    color: white,
    lineHeight: 32,
  },
  statValueMobile: { fontSize: 25, lineHeight: 28 },
  statValueLight: { color: black },
  statLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color: muted,
    marginTop: 4,
  },
  statLabelMobile: { fontSize: 9.5, letterSpacing: 0.55 },
  statLabelLight: { color: "#6A6A6A" },
  progressTrack: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(18,18,18,0.08)",
  },
  progressFill: {
    height: "100%" as any,
    borderRadius: 999,
    backgroundColor: orange,
  },
  numberStage: {
    minHeight: 270,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    backgroundColor: "#F7F7F7",
  },
  numberStageMobile: { minHeight: 250, borderRadius: 18 },
  numberDisplay: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 108,
    fontWeight: "700" as const,
    lineHeight: 116,
    color: black,
    transition: "opacity 90ms ease, transform 90ms ease" as any,
  },
  numberDisplayMobile: { fontSize: 92, lineHeight: 100 },
  numberDisplayHidden: { opacity: 0, transform: [{ scale: 0.96 }] },
  pauseCurtain: { alignItems: "center", justifyContent: "center", gap: 12 },
  pauseText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 15,
    fontWeight: "800" as const,
    color: black,
  },
  manualControls: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
    marginTop: 18,
  },
  manualControlsMobile: { marginTop: 12 },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#161616",
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  controlRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap" as any,
  },
  controlRowMobile: { width: "100%" as any, gap: 8, flexWrap: "wrap" as any },
  sessionActionRow: { width: "100%" as any },
  sessionActionButton: { flexGrow: 1, minWidth: 132 },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.14)",
    borderRadius: RADIUS.sm,
    backgroundColor: "#161616",
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  secondaryButtonMobile: { flex: 1, minWidth: 0, paddingHorizontal: 8 },
  secondaryButtonText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: white,
  },
  endButton: {
    backgroundColor: "rgba(255,118,90,0.12)",
    borderColor: "rgba(255,118,90,0.28)",
  },

  recallSummary: { flexDirection: "row", gap: 12, flexWrap: "wrap" as any },
  recallSummaryMobile: {
    flexDirection: "row",
    flexWrap: "nowrap" as any,
    gap: 8,
  },
  recallHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  recallTimeAdjust: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap" as any,
  },
  recallTimeAdjustMobile: { width: "100%" as any, gap: 8 },
  timeAdjustButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(232,93,42,0.24)",
    borderRadius: 999,
    backgroundColor: "rgba(232,93,42,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  timeAdjustButtonMobile: { flex: 1, minWidth: 0 },
  timeAdjustText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    color: orange,
  },
  micButtonActive: { backgroundColor: orange, borderColor: orange },
  micButtonTextActive: { color: white },
  recallTimerPill: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(232,93,42,0.24)",
    borderRadius: 999,
    backgroundColor: "rgba(232,93,42,0.08)",
    paddingHorizontal: 12,
  },
  recallTimerPillUrgent: { backgroundColor: orange, borderColor: orange },
  recallTimerText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "800" as const,
    color: orange,
  },
  recallTimerTextUrgent: { color: white },
  recallGrid: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(auto-fill, minmax(78px, 1fr))" as any,
    gap: 10,
    maxHeight: 300,
    overflow: "auto" as any,
    paddingRight: 4,
  },
  recallGridMobile: {
    display: "flex" as any,
    flexDirection: "row",
    flexWrap: "wrap" as any,
    maxHeight: 360,
    gap: 8,
    paddingRight: 0,
  },
  recallBoxWrapMobile: {
    width: "31%" as any,
    minWidth: 86,
    flexGrow: 1,
  },
  recallBoxWrap: {
    position: "relative" as any,
    borderWidth: 1,
    borderColor: "rgba(18,18,18,0.10)",
    borderRadius: RADIUS.md,
    backgroundColor: "#F7F7F7",
    paddingHorizontal: 9,
    paddingTop: 19,
    paddingBottom: 9,
  },
  recallBoxIndex: {
    position: "absolute" as any,
    top: 6,
    left: 9,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 9,
    fontWeight: "800" as const,
    color: "#8A8A8A",
  },
  recallBoxInput: {
    width: "100%" as any,
    color: black,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 22,
    fontWeight: "800" as const,
    textAlign: "center",
    paddingVertical: 3,
    outlineStyle: "none" as any,
  },
  recallInput: {
    minHeight: 170,
    textAlignVertical: "top" as any,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.13)",
    borderRadius: RADIUS.md,
    backgroundColor: "rgba(0,0,0,0.24)",
    color: white,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 18,
    lineHeight: 28,
    padding: 16,
    outlineStyle: "none" as any,
  },
  resultStats: {
    display: "grid" as any,
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))" as any,
    gap: 12,
  },
  resultStatsMobile: {
    display: "flex" as any,
    flexDirection: "row",
    flexWrap: "wrap" as any,
    gap: 8,
  },
  answerList: { gap: 8 },
  answerListMobile: { maxHeight: 360, paddingRight: 2 },
  answerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  answerRowMobile: { gap: 8, paddingHorizontal: 10, paddingVertical: 10 },
  answerRowGood: {
    borderColor: "rgba(125,236,212,0.22)",
    backgroundColor: "rgba(42,157,143,0.10)",
  },
  answerRowBad: {
    borderColor: "rgba(255,140,117,0.22)",
    backgroundColor: "rgba(255,118,90,0.10)",
  },
  answerIndex: {
    width: 34,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    color: "#6A6A6A",
  },
  answerIndexMobile: { width: 26, fontSize: 11 },
  answerCol: { flex: 1 },
  answerColMobile: { minWidth: 0 },
  answerLabel: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 10,
    fontWeight: "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color: "#6A6A6A",
  },
  answerValue: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 16,
    fontWeight: "800" as const,
    color: black,
    marginTop: 2,
  },
  answerValueMobile: { fontSize: 14 },
  wordForgeStage: {
    minHeight: 190,
    borderWidth: 1,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    padding: 22,
  },
  wordForgeSource: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize: 56,
    lineHeight: 62,
    fontWeight: "700" as const,
    color: black,
    textAlign: "center",
    textTransform: "capitalize" as any,
  },
  wordForgeLetters: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap" as any,
    gap: 7,
  },
  wordForgeLetter: {
    width: 35,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: white,
  },
  wordForgeLetterText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 17,
    fontWeight: "900" as const,
    textTransform: "uppercase" as any,
  },
  wordForgeInput: {
    width: "100%" as any,
    minHeight: 58,
    borderWidth: 2,
    borderRadius: RADIUS.md,
    backgroundColor: "#F7F7F7",
    color: black,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 20,
    fontWeight: "800" as const,
    paddingHorizontal: 18,
    paddingVertical: 12,
    outlineStyle: "none" as any,
  },
  wordForgeStatusRow: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  wordForgeStatus: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 13,
    fontWeight: "700" as const,
    color: "#6A6A6A",
  },
  wordForgeStatusBad: { color: "#D64B45" },
  wordForgeFoundScroll: { maxHeight: 110 },
  wordForgeFound: {
    flexDirection: "row",
    flexWrap: "wrap" as any,
    gap: 8,
  },
  wordForgeFoundChip: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  wordForgeFoundText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "900" as const,
    textTransform: "capitalize" as any,
  },
  wordForgeResultsScroll: { maxHeight: 390 },
  wordForgeResultsContent: { gap: 20, paddingRight: 3 },
  wordForgeResultGroup: { gap: 9 },
  wordForgeRejectedChip: {
    borderColor: "rgba(214,75,69,0.25)",
    backgroundColor: "rgba(214,75,69,0.08)",
  },
  wordForgeRejectedText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    color: "#D64B45",
    textTransform: "capitalize" as any,
  },
  wordForgeSuggestionChip: {
    minHeight: 34,
    borderWidth: 1,
    borderColor: border,
    borderRadius: 999,
    backgroundColor: "#F7F7F7",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  wordForgeSuggestionText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 12,
    fontWeight: "800" as const,
    color: body,
    textTransform: "capitalize" as any,
  },
  emptyText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize: 14,
    color: "#6A6A6A",
    lineHeight: 22,
  },
});
