import type { ImageSourcePropType } from "react-native";

export type CardSuit = "clubs" | "diamonds" | "hearts" | "spades";

export type PlayingCardAsset = {
  id: string;
  rank: string;
  suit: CardSuit;
  label: string;
  shortLabel: string;
  image: ImageSourcePropType;
};

export const PLAYING_CARDS: PlayingCardAsset[] = [
  {
    id: "ace_of_clubs",
    rank: "ace",
    suit: "clubs",
    label: "Ace of Clubs",
    shortLabel: "A♣",
    image: require("../../../assets/images/cards/standard/ace_of_clubs.png"),
  },
  {
    id: "2_of_clubs",
    rank: "2",
    suit: "clubs",
    label: "2 of Clubs",
    shortLabel: "2♣",
    image: require("../../../assets/images/cards/standard/2_of_clubs.png"),
  },
  {
    id: "3_of_clubs",
    rank: "3",
    suit: "clubs",
    label: "3 of Clubs",
    shortLabel: "3♣",
    image: require("../../../assets/images/cards/standard/3_of_clubs.png"),
  },
  {
    id: "4_of_clubs",
    rank: "4",
    suit: "clubs",
    label: "4 of Clubs",
    shortLabel: "4♣",
    image: require("../../../assets/images/cards/standard/4_of_clubs.png"),
  },
  {
    id: "5_of_clubs",
    rank: "5",
    suit: "clubs",
    label: "5 of Clubs",
    shortLabel: "5♣",
    image: require("../../../assets/images/cards/standard/5_of_clubs.png"),
  },
  {
    id: "6_of_clubs",
    rank: "6",
    suit: "clubs",
    label: "6 of Clubs",
    shortLabel: "6♣",
    image: require("../../../assets/images/cards/standard/6_of_clubs.png"),
  },
  {
    id: "7_of_clubs",
    rank: "7",
    suit: "clubs",
    label: "7 of Clubs",
    shortLabel: "7♣",
    image: require("../../../assets/images/cards/standard/7_of_clubs.png"),
  },
  {
    id: "8_of_clubs",
    rank: "8",
    suit: "clubs",
    label: "8 of Clubs",
    shortLabel: "8♣",
    image: require("../../../assets/images/cards/standard/8_of_clubs.png"),
  },
  {
    id: "9_of_clubs",
    rank: "9",
    suit: "clubs",
    label: "9 of Clubs",
    shortLabel: "9♣",
    image: require("../../../assets/images/cards/standard/9_of_clubs.png"),
  },
  {
    id: "10_of_clubs",
    rank: "10",
    suit: "clubs",
    label: "10 of Clubs",
    shortLabel: "10♣",
    image: require("../../../assets/images/cards/standard/10_of_clubs.png"),
  },
  {
    id: "jack_of_clubs",
    rank: "jack",
    suit: "clubs",
    label: "Jack of Clubs",
    shortLabel: "J♣",
    image: require("../../../assets/images/cards/standard/jack_of_clubs.png"),
  },
  {
    id: "queen_of_clubs",
    rank: "queen",
    suit: "clubs",
    label: "Queen of Clubs",
    shortLabel: "Q♣",
    image: require("../../../assets/images/cards/standard/queen_of_clubs.png"),
  },
  {
    id: "king_of_clubs",
    rank: "king",
    suit: "clubs",
    label: "King of Clubs",
    shortLabel: "K♣",
    image: require("../../../assets/images/cards/standard/king_of_clubs.png"),
  },
  {
    id: "ace_of_diamonds",
    rank: "ace",
    suit: "diamonds",
    label: "Ace of Diamonds",
    shortLabel: "A♦",
    image: require("../../../assets/images/cards/standard/ace_of_diamonds.png"),
  },
  {
    id: "2_of_diamonds",
    rank: "2",
    suit: "diamonds",
    label: "2 of Diamonds",
    shortLabel: "2♦",
    image: require("../../../assets/images/cards/standard/2_of_diamonds.png"),
  },
  {
    id: "3_of_diamonds",
    rank: "3",
    suit: "diamonds",
    label: "3 of Diamonds",
    shortLabel: "3♦",
    image: require("../../../assets/images/cards/standard/3_of_diamonds.png"),
  },
  {
    id: "4_of_diamonds",
    rank: "4",
    suit: "diamonds",
    label: "4 of Diamonds",
    shortLabel: "4♦",
    image: require("../../../assets/images/cards/standard/4_of_diamonds.png"),
  },
  {
    id: "5_of_diamonds",
    rank: "5",
    suit: "diamonds",
    label: "5 of Diamonds",
    shortLabel: "5♦",
    image: require("../../../assets/images/cards/standard/5_of_diamonds.png"),
  },
  {
    id: "6_of_diamonds",
    rank: "6",
    suit: "diamonds",
    label: "6 of Diamonds",
    shortLabel: "6♦",
    image: require("../../../assets/images/cards/standard/6_of_diamonds.png"),
  },
  {
    id: "7_of_diamonds",
    rank: "7",
    suit: "diamonds",
    label: "7 of Diamonds",
    shortLabel: "7♦",
    image: require("../../../assets/images/cards/standard/7_of_diamonds.png"),
  },
  {
    id: "8_of_diamonds",
    rank: "8",
    suit: "diamonds",
    label: "8 of Diamonds",
    shortLabel: "8♦",
    image: require("../../../assets/images/cards/standard/8_of_diamonds.png"),
  },
  {
    id: "9_of_diamonds",
    rank: "9",
    suit: "diamonds",
    label: "9 of Diamonds",
    shortLabel: "9♦",
    image: require("../../../assets/images/cards/standard/9_of_diamonds.png"),
  },
  {
    id: "10_of_diamonds",
    rank: "10",
    suit: "diamonds",
    label: "10 of Diamonds",
    shortLabel: "10♦",
    image: require("../../../assets/images/cards/standard/10_of_diamonds.png"),
  },
  {
    id: "jack_of_diamonds",
    rank: "jack",
    suit: "diamonds",
    label: "Jack of Diamonds",
    shortLabel: "J♦",
    image: require("../../../assets/images/cards/standard/jack_of_diamonds.png"),
  },
  {
    id: "queen_of_diamonds",
    rank: "queen",
    suit: "diamonds",
    label: "Queen of Diamonds",
    shortLabel: "Q♦",
    image: require("../../../assets/images/cards/standard/queen_of_diamonds.png"),
  },
  {
    id: "king_of_diamonds",
    rank: "king",
    suit: "diamonds",
    label: "King of Diamonds",
    shortLabel: "K♦",
    image: require("../../../assets/images/cards/standard/king_of_diamonds.png"),
  },
  {
    id: "ace_of_hearts",
    rank: "ace",
    suit: "hearts",
    label: "Ace of Hearts",
    shortLabel: "A♥",
    image: require("../../../assets/images/cards/standard/ace_of_hearts.png"),
  },
  {
    id: "2_of_hearts",
    rank: "2",
    suit: "hearts",
    label: "2 of Hearts",
    shortLabel: "2♥",
    image: require("../../../assets/images/cards/standard/2_of_hearts.png"),
  },
  {
    id: "3_of_hearts",
    rank: "3",
    suit: "hearts",
    label: "3 of Hearts",
    shortLabel: "3♥",
    image: require("../../../assets/images/cards/standard/3_of_hearts.png"),
  },
  {
    id: "4_of_hearts",
    rank: "4",
    suit: "hearts",
    label: "4 of Hearts",
    shortLabel: "4♥",
    image: require("../../../assets/images/cards/standard/4_of_hearts.png"),
  },
  {
    id: "5_of_hearts",
    rank: "5",
    suit: "hearts",
    label: "5 of Hearts",
    shortLabel: "5♥",
    image: require("../../../assets/images/cards/standard/5_of_hearts.png"),
  },
  {
    id: "6_of_hearts",
    rank: "6",
    suit: "hearts",
    label: "6 of Hearts",
    shortLabel: "6♥",
    image: require("../../../assets/images/cards/standard/6_of_hearts.png"),
  },
  {
    id: "7_of_hearts",
    rank: "7",
    suit: "hearts",
    label: "7 of Hearts",
    shortLabel: "7♥",
    image: require("../../../assets/images/cards/standard/7_of_hearts.png"),
  },
  {
    id: "8_of_hearts",
    rank: "8",
    suit: "hearts",
    label: "8 of Hearts",
    shortLabel: "8♥",
    image: require("../../../assets/images/cards/standard/8_of_hearts.png"),
  },
  {
    id: "9_of_hearts",
    rank: "9",
    suit: "hearts",
    label: "9 of Hearts",
    shortLabel: "9♥",
    image: require("../../../assets/images/cards/standard/9_of_hearts.png"),
  },
  {
    id: "10_of_hearts",
    rank: "10",
    suit: "hearts",
    label: "10 of Hearts",
    shortLabel: "10♥",
    image: require("../../../assets/images/cards/standard/10_of_hearts.png"),
  },
  {
    id: "jack_of_hearts",
    rank: "jack",
    suit: "hearts",
    label: "Jack of Hearts",
    shortLabel: "J♥",
    image: require("../../../assets/images/cards/standard/jack_of_hearts.png"),
  },
  {
    id: "queen_of_hearts",
    rank: "queen",
    suit: "hearts",
    label: "Queen of Hearts",
    shortLabel: "Q♥",
    image: require("../../../assets/images/cards/standard/queen_of_hearts.png"),
  },
  {
    id: "king_of_hearts",
    rank: "king",
    suit: "hearts",
    label: "King of Hearts",
    shortLabel: "K♥",
    image: require("../../../assets/images/cards/standard/king_of_hearts.png"),
  },
  {
    id: "ace_of_spades",
    rank: "ace",
    suit: "spades",
    label: "Ace of Spades",
    shortLabel: "A♠",
    image: require("../../../assets/images/cards/standard/ace_of_spades.png"),
  },
  {
    id: "2_of_spades",
    rank: "2",
    suit: "spades",
    label: "2 of Spades",
    shortLabel: "2♠",
    image: require("../../../assets/images/cards/standard/2_of_spades.png"),
  },
  {
    id: "3_of_spades",
    rank: "3",
    suit: "spades",
    label: "3 of Spades",
    shortLabel: "3♠",
    image: require("../../../assets/images/cards/standard/3_of_spades.png"),
  },
  {
    id: "4_of_spades",
    rank: "4",
    suit: "spades",
    label: "4 of Spades",
    shortLabel: "4♠",
    image: require("../../../assets/images/cards/standard/4_of_spades.png"),
  },
  {
    id: "5_of_spades",
    rank: "5",
    suit: "spades",
    label: "5 of Spades",
    shortLabel: "5♠",
    image: require("../../../assets/images/cards/standard/5_of_spades.png"),
  },
  {
    id: "6_of_spades",
    rank: "6",
    suit: "spades",
    label: "6 of Spades",
    shortLabel: "6♠",
    image: require("../../../assets/images/cards/standard/6_of_spades.png"),
  },
  {
    id: "7_of_spades",
    rank: "7",
    suit: "spades",
    label: "7 of Spades",
    shortLabel: "7♠",
    image: require("../../../assets/images/cards/standard/7_of_spades.png"),
  },
  {
    id: "8_of_spades",
    rank: "8",
    suit: "spades",
    label: "8 of Spades",
    shortLabel: "8♠",
    image: require("../../../assets/images/cards/standard/8_of_spades.png"),
  },
  {
    id: "9_of_spades",
    rank: "9",
    suit: "spades",
    label: "9 of Spades",
    shortLabel: "9♠",
    image: require("../../../assets/images/cards/standard/9_of_spades.png"),
  },
  {
    id: "10_of_spades",
    rank: "10",
    suit: "spades",
    label: "10 of Spades",
    shortLabel: "10♠",
    image: require("../../../assets/images/cards/standard/10_of_spades.png"),
  },
  {
    id: "jack_of_spades",
    rank: "jack",
    suit: "spades",
    label: "Jack of Spades",
    shortLabel: "J♠",
    image: require("../../../assets/images/cards/standard/jack_of_spades.png"),
  },
  {
    id: "queen_of_spades",
    rank: "queen",
    suit: "spades",
    label: "Queen of Spades",
    shortLabel: "Q♠",
    image: require("../../../assets/images/cards/standard/queen_of_spades.png"),
  },
  {
    id: "king_of_spades",
    rank: "king",
    suit: "spades",
    label: "King of Spades",
    shortLabel: "K♠",
    image: require("../../../assets/images/cards/standard/king_of_spades.png"),
  },
];

export const PLAYING_CARD_BY_ID = Object.fromEntries(
  PLAYING_CARDS.map((card) => [card.id, card]),
) as Record<string, PlayingCardAsset>;
