import { createWebStyles } from "../../styles/web";
import { P } from "../../styles/tokens";

// ── MEMORY TEST ───────────────────────────────────────────────────────────────
export const test = createWebStyles({
  section: {
    paddingVertical:   100,
    paddingHorizontal: 56,
    backgroundColor:   P.green,
  },
  sectionMobile: {
    paddingVertical:   64,
    paddingHorizontal: 20,
  },
  inner: {
    maxWidth:         860,
    marginHorizontal: "auto" as any,
    width:            "100%" as any,
  },
  head: {
    alignItems:   "center",
    marginBottom: 52,
  },
  headMobile: {
    marginBottom: 34,
  },
  eyebrow: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      13,
    fontWeight:    "500" as const,
    letterSpacing: 1.5,
    textTransform: "uppercase" as any,
    color:         P.gold,
    marginBottom:  14,
  },
  h2: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      50,
    fontWeight:    "600" as const,
    color:         P.white,
    letterSpacing: 0,
    textAlign:     "center",
  },
  h2Mobile: {
    fontSize:   38,
    lineHeight: 42,
  },
  subText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   16,
    color:      "rgba(255,255,255,0.45)",
    marginTop:  14,
    maxWidth:   440,
    textAlign:  "center",
    lineHeight: 27,
  },
  subTextMobile: {
    fontSize:   15,
    lineHeight: 24,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.09)",
    borderRadius:    22,
    padding:         40,
    alignItems:      "center",
  },
  cardMobile: {
    borderRadius: 16,
    padding:      20,
  },
  primaryButton: {
    alignSelf:        "center",
    flexDirection:    "row",
    alignItems:       "center",
    justifyContent:   "center",
    gap:              9,
    borderRadius:     10,
    backgroundColor:  "#E85D2A",
    paddingHorizontal: 24,
    paddingVertical:   14,
    cursor:           "pointer" as any,
    boxShadow:        "0 0 40px rgba(232,93,42,0.20)" as any,
  },
  primaryButtonMobile: {
    width:    "100%" as any,
    maxWidth: 320,
  },
  primaryButtonInline: {
    alignSelf:        "center",
    flexDirection:    "row",
    alignItems:       "center",
    justifyContent:   "center",
    gap:              9,
    borderRadius:     10,
    backgroundColor:  "#E85D2A",
    paddingHorizontal: 20,
    paddingVertical:   12,
    cursor:           "pointer" as any,
  },
  primaryButtonInlineMobile: {
    width:      "100%" as any,
    minHeight:  46,
    alignSelf: "stretch",
  },
  primaryButtonText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize:   14,
    fontWeight: "800" as const,
    color:      "#FFFFFF",
  },
  countdownPanel: {
    minHeight:       420,
    width:           "100%" as any,
    alignItems:      "center",
    justifyContent:  "center",
    borderRadius:    24,
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(4,6,15,0.88)",
    boxShadow:       "0 28px 90px rgba(0,0,0,0.34)" as any,
    paddingHorizontal: 28,
    paddingVertical:   38,
  },
  countdownPanelMobile: {
    minHeight:    340,
    borderRadius: 18,
  },
  countdownKicker: {
    fontFamily:    "DM Sans, system-ui, sans-serif" as any,
    fontSize:      12,
    fontWeight:    "800" as const,
    letterSpacing: 1.4,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.48)",
  },
  countdownNumber: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   138,
    fontWeight: "700" as const,
    lineHeight: 150,
    color:      "#FFFFFF",
    marginTop:  12,
    marginBottom: 18,
  },
  countdownNumberMobile: {
    fontSize:   104,
    lineHeight: 112,
  },
  countdownText: {
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize:   14,
    color:      "rgba(255,255,255,0.58)",
    lineHeight: 22,
    textAlign:  "center",
  },
  playPanel: {
    width:           "100%" as any,
    minHeight:       500,
    justifyContent:  "space-between",
    backgroundColor: "rgba(4,6,15,0.82)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.11)",
    borderRadius:    24,
    padding:         24,
    gap:             20,
  },
  playPanelMobile: {
    minHeight:    420,
    borderRadius: 18,
    padding:      18,
  },
  playTimerRow: {
    flexDirection: "row",
    alignItems:    "center",
    gap:           14,
  },
  progressTrack: {
    flex:            1,
    height:          6,
    borderRadius:    999,
    overflow:        "hidden",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  progressFill: {
    height:          "100%" as any,
    borderRadius:    999,
    backgroundColor: "#E85D2A",
  },
  timerText: {
    minWidth:   46,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize:   13,
    fontWeight: "800" as const,
    color:      "rgba(255,255,255,0.58)",
    textAlign:  "right",
  },
  playTop: {
    flexDirection: "row",
    gap:           12,
    flexWrap:      "wrap" as any,
  },
  statTile: {
    flex:              1,
    minWidth:          110,
    backgroundColor:   "rgba(255,255,255,0.06)",
    borderWidth:       1,
    borderColor:       "rgba(255,255,255,0.09)",
    borderRadius:      16,
    paddingHorizontal: 16,
    paddingVertical:   14,
  },
  statValue: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   30,
    fontWeight: "700" as const,
    color:      "#FFFFFF",
    lineHeight: 32,
  },
  statLabel: {
    fontFamily:    "DM Sans, system-ui, sans-serif" as any,
    fontSize:      11,
    fontWeight:    "800" as const,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.45)",
    marginTop:     4,
  },
  wordStage: {
    minHeight:       250,
    alignItems:      "center",
    justifyContent:  "center",
    borderRadius:    24,
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.045)",
    paddingHorizontal: 16,
  },
  wordStageMobile: {
    minHeight:    190,
    borderRadius: 18,
  },
  wordDisplay: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   96,
    fontWeight: "700" as const,
    lineHeight: 106,
    color:      "#FFFFFF",
    textAlign:  "center",
    transition: "opacity 90ms ease, transform 90ms ease" as any,
  },
  wordDisplayMobile: {
    fontSize:   58,
    lineHeight: 66,
  },
  wordDisplayHidden: {
    opacity: 0,
    transform: [{ scale: 0.96 }],
  },
  recallPanel: {
    width:           "100%" as any,
    backgroundColor: "rgba(4,6,15,0.82)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.11)",
    borderRadius:    24,
    padding:         24,
    gap:             22,
  },
  recallPanelMobile: {
    padding:      16,
    borderRadius: 18,
    gap:          16,
    overflow:     "hidden",
  },
  panelHeader: {
    flexDirection:  "row",
    alignItems:     "center",
    justifyContent: "space-between",
    gap:            16,
  },
  panelHeaderMobile: {
    alignItems: "flex-start",
    gap:        10,
  },
  panelTitleWrap: {
    flex:     1,
    minWidth: 0,
  },
  kicker: {
    fontFamily:    "DM Sans, system-ui, sans-serif" as any,
    fontSize:      11,
    fontWeight:    "800" as const,
    letterSpacing: 1.3,
    textTransform: "uppercase" as any,
    color:         "#E85D2A",
    marginBottom:  6,
  },
  panelTitle: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   32,
    fontWeight: "700" as const,
    lineHeight: 36,
    color:      "#FFFFFF",
  },
  panelTitleMobile: {
    fontSize:   24,
    lineHeight: 28,
  },
  settingsIcon: {
    width:           42,
    height:          42,
    borderRadius:    14,
    backgroundColor: "#161616",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.12)",
    alignItems:      "center",
    justifyContent:  "center",
  },
  settingsIconMobile: {
    display: "none" as any,
  },
  phaseTitle: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     32,
    fontWeight:   "600" as const,
    color:        P.white,
    marginBottom: 10,
    textAlign:    "center",
  },
  phaseTitleMobile: {
    fontSize:   28,
    lineHeight: 32,
  },
  phaseText: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     15,
    color:        "rgba(255,255,255,0.45)",
    marginBottom: 32,
    textAlign:    "center",
    lineHeight:   26,
  },
  phaseTextMobile: {
    marginBottom: 12,
    lineHeight:   22,
  },
  digitRow: {
    flexDirection:  "row",
    justifyContent: "center",
    gap:            10,
    marginBottom:   30,
  },
  digitBox: {
    width:           54,
    height:          68,
    borderRadius:    11,
    backgroundColor: "rgba(255,255,255,0.10)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.18)",
    alignItems:      "center",
    justifyContent:  "center",
  },
  digitText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   38,
    fontWeight: "600" as const,
    color:      P.white,
  },
  countdown: {
    width:           54,
    height:          54,
    borderRadius:    999,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth:     2,
    borderColor:     P.gold,
    alignItems:      "center",
    justifyContent:  "center",
    alignSelf:       "center",
  },
  countdownNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   26,
    fontWeight: "600" as const,
    color:      P.gold,
  },
  recallDigitBox: {
    width:           54,
    height:          68,
    borderRadius:    11,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.09)",
    alignItems:      "center",
    justifyContent:  "center",
  },
  eyebrowGold: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      15,
    letterSpacing: 1.0,
    textTransform: "uppercase" as any,
    color:         P.gold,
    marginBottom:  22,
    textAlign:     "center",
  },
  chunkBox: {
    backgroundColor:   "rgba(255,255,255,0.05)",
    borderRadius:      14,
    padding:           24,
    maxWidth:          460,
    alignSelf:         "center",
    marginBottom:      28,
    width:             "100%" as any,
  },
  chunkText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   15,
    color:      "rgba(255,255,255,0.65)",
    lineHeight: 26,
  },
  chunkRow: {
    flexDirection:  "row",
    justifyContent: "center",
    gap:            14,
    marginTop:      18,
  },
  chunkPill: {
    backgroundColor:   "rgba(255,255,255,0.09)",
    borderRadius:      9,
    paddingHorizontal: 17,
    paddingVertical:   9,
  },
  chunkPillText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   28,
    fontWeight: "600" as const,
    color:      P.gold,
  },
  chunkNote: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    color:      "rgba(255,255,255,0.35)",
    marginTop:  10,
    textAlign:  "center",
  },
  resultScoreRow: {
    flexDirection:  "row",
    justifyContent: "center",
    gap:            44,
    marginBottom:   36,
  },
  resultScoreItem: {
    alignItems: "center",
  },
  resultScoreLabel: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      13,
    letterSpacing: 1.0,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.35)",
    marginBottom:  10,
  },
  resultCircle: {
    width:          96,
    height:         96,
    borderRadius:   999,
    alignItems:     "center",
    justifyContent: "center",
    marginBottom:   10,
    borderWidth:    2,
  },
  resultCircleNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   34,
    fontWeight: "700" as const,
  },
  resultCircleSub: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    color:      "rgba(255,255,255,0.40)",
  },
  improvementBadge: {
    backgroundColor:   "rgba(255,255,255,0.05)",
    borderRadius:      10,
    paddingHorizontal: 22,
    paddingVertical:   12,
    marginBottom:      28,
    alignSelf:         "center",
  },
  improvementText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   14,
    color:      P.gold,
  },
  resultNote: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     14,
    color:        "rgba(255,255,255,0.40)",
    marginBottom: 28,
    textAlign:    "center",
  },
  btn: {
    borderRadius:      999,
    paddingHorizontal: 32,
    paddingVertical:   13,
    cursor:            "pointer" as any,
    transition:        "transform 0.2s" as any,
  },
  btnPrimary:     { backgroundColor: P.gold },
  btnPrimaryText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   15,
    fontWeight: "600" as const,
    color:      "#FFFFFF",
  },
  btnSecondary: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.15)",
  },
  btnSecondaryText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   15,
    color:      "rgba(255,255,255,0.60)",
  },
  scoreBadge: {
    backgroundColor:   P.gold,
    borderRadius:      999,
    paddingHorizontal: 16,
    paddingVertical:   6,
    marginBottom:      22,
    alignSelf:         "center",
  },
  scoreBadgeText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    fontWeight: "600" as const,
    color:      "#FFFFFF",
  },
  emojiIcon: {
    fontSize:     60,
    marginBottom: 20,
    textAlign:    "center",
  },

  // ── Phase wrappers ──────────────────────────────────────────────────────────
  phaseWrap: { alignItems: "center", width: "100%" as any },

  // ── Recall digit character ──────────────────────────────────────────────────
  recallCharText:  { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 34, fontWeight: "600" as const, color: "#FFFFFF" },
  recallCharEmpty: { color: "rgba(255,255,255,0.18)" },

  // ── Inline emphasis (nested Text children) ──────────────────────────────────
  emphasis:     { color: "#E85D2A", fontStyle: "italic" },
  emphasisBold: { color: "#E85D2A", fontWeight: "700" as const },

  // ── Result circle variants ──────────────────────────────────────────────────
  resultCircleDefault:   { backgroundColor: "rgba(255,255,255,0.08)", borderColor: "rgba(255,255,255,0.12)" },
  resultCircleHighlight: { backgroundColor: "#E85D2A",                borderColor: "#E85D2A" },
  resultNumDefault:      { color: "#FFFFFF" },
  resultNumHighlight:    { color: "#FFFFFF" },

  // ── Word memory test — show phase ───────────────────────────────────────────
  wordTimerTrack: {
    width:           300,
    height:          3,
    borderRadius:    2,
    backgroundColor: "rgba(255,255,255,0.10)",
    marginBottom:    36,
    overflow:        "hidden",
  },
  wordTimerTrackMobile: {
    width:       "100%" as any,
    maxWidth:    280,
    marginBottom: 26,
  },
  wordTimerFill: {
    height:          "100%" as any,
    backgroundColor: "#E85D2A",
    borderRadius:    2,
    transition:      "width 1s linear" as any,
  },
  wordBig: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      76,
    fontWeight:    "600" as const,
    color:         "#FFFFFF",
    letterSpacing: -1.5,
    textAlign:     "center",
    marginVertical: 8,
  },
  wordBigMobile: {
    fontSize:      56,
    lineHeight:    62,
    letterSpacing: 0,
  },
  wordCounter: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      16,
    color:         "rgba(255,255,255,0.40)",
    letterSpacing: 1.0,
    marginTop:     12,
  },

  // ── Word memory test — recall grid ──────────────────────────────────────────
  inputGrid: {
    display:             "grid" as any,
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))" as any,
    gap:                 10,
    width:               "100%" as any,
    maxWidth:            "100%" as any,
    marginBottom:        24,
  },
  inputGridMobile: {
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))" as any,
    width:               "100%" as any,
    maxWidth:            "100%" as any,
    gap:                 10,
  },
  recallBoxWrap: {
    position:        "relative" as any,
    width:           "100%" as any,
    minHeight:       68,
    boxSizing:       "border-box" as any,
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.13)",
    borderRadius:    16,
    backgroundColor: "rgba(0,0,0,0.24)",
    paddingHorizontal: 9,
    paddingTop:        19,
    paddingBottom:     9,
  },
  recallBoxIndex: {
    position:   "absolute" as any,
    top:        6,
    left:       9,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize:   9,
    fontWeight: "800" as const,
    color:      "rgba(255,255,255,0.34)",
  },
  recallBoxInput: {
    width:       "100%" as any,
    color:       "#FFFFFF",
    fontFamily:  "DM Sans, system-ui, sans-serif" as any,
    fontSize:    18,
    fontWeight:  "800" as const,
    textAlign:   "center",
    paddingVertical: 8,
    outlineStyle: "none" as any,
  },

  // ── Word memory test — result phase ─────────────────────────────────────────
  scoreRow: {
    flexDirection:  "row",
    alignItems:     "flex-end",
    justifyContent: "center",
    gap:            4,
    marginBottom:   10,
  },
  scoreNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   84,
    fontWeight: "700" as const,
    color:      "#E85D2A",
    lineHeight: 84,
  },
  scoreNumMobile: {
    fontSize:   68,
    lineHeight: 70,
  },
  scoreDenom: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     36,
    color:        "rgba(255,255,255,0.30)",
    paddingBottom: 12,
  },
  wordResultGrid: {
    display:             "grid" as any,
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))" as any,
    gap:                 8,
    width:               "100%" as any,
    maxWidth:            "100%" as any,
    marginBottom:        24,
  },
  wordResultGridMobile: {
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))" as any,
    gap:                 7,
  },
  wordResultChip: {
    borderRadius:      8,
    paddingHorizontal: 8,
    paddingVertical:   8,
    borderWidth:       1,
    minWidth:          0,
    alignItems:        "center",
    justifyContent:    "center",
  },
  wordResultHit:  { backgroundColor: "rgba(232,93,42,0.12)", borderColor: "rgba(232,93,42,0.40)" },
  wordResultMiss: { backgroundColor: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.09)" },
  wordResultText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   16,
    fontWeight: "500" as const,
    lineHeight: 20,
    textAlign:  "center",
  },
  wordResultTextHit:  { color: "#E85D2A" },
  wordResultTextMiss: { color: "rgba(255,255,255,0.30)" },

  // ── Technique tip box ────────────────────────────────────────────────────────
  tipIntro: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     18,
    fontWeight:   "600" as const,
    color:        "#FFFFFF",
    textAlign:    "center",
    marginBottom: 14,
    maxWidth:     "100%" as any,
  },
  tipBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth:     1,
    borderColor:     "rgba(232,93,42,0.20)",
    borderRadius:    14,
    padding:         22,
    maxWidth:        "100%" as any,
    width:           "100%" as any,
    marginBottom:    24,
    gap:             8,
  },
  storyPath: {
    display:             "grid" as any,
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))" as any,
    gap:                 8,
    marginTop:           10,
    marginBottom:        4,
  },
  storyPathMobile: {
    gap: 5,
  },
  storyImageFrame: {
    width:           "100%" as any,
    aspectRatio:     1672 / 941,
    borderRadius:    13,
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.16)",
    backgroundColor: "#FFFFFF",
    overflow:        "hidden",
    marginTop:       10,
    marginBottom:    6,
  },
  storyImageFrameMobile: {
    borderRadius: 10,
    marginTop:    8,
  },
  storyImage: {
    width:  "100%" as any,
    height: "100%" as any,
  },
  storyStep: {
    minWidth:        0,
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.10)",
    borderRadius:    12,
    backgroundColor: "rgba(255,255,255,0.055)",
    alignItems:      "center",
    justifyContent:  "center",
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  storyIcon: {
    fontSize:   22,
    lineHeight: 28,
  },
  storyLabel: {
    maxWidth:   "100%" as any,
    fontFamily: "DM Sans, system-ui, sans-serif" as any,
    fontSize:   10,
    fontWeight: "800" as const,
    color:      "rgba(255,255,255,0.72)",
    textAlign:  "center",
    marginTop:  4,
    overflow:   "hidden",
  },

  // ── Score comparison (second attempt+) ─────────────────────────────────────
  compareWrap: {
    width:           "100%" as any,
    maxWidth:        400,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius:    16,
    paddingVertical: 20,
    paddingHorizontal: 24,
    marginTop:       4,
    marginBottom:    24,
    alignItems:      "center",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.07)",
  },
  compareScoreRow: {
    flexDirection:  "row",
    alignItems:     "center",
    justifyContent: "center",
    gap:            16,
    marginBottom:   12,
  },
  compareBox: {
    alignItems:        "center",
    backgroundColor:   "rgba(255,255,255,0.06)",
    borderRadius:      12,
    paddingHorizontal: 22,
    paddingVertical:   14,
    borderWidth:       1,
    borderColor:       "rgba(255,255,255,0.08)",
    minWidth:          96,
  },
  compareBoxActive: {
    backgroundColor: "rgba(232,93,42,0.12)",
    borderColor:     "rgba(232,93,42,0.35)",
  },
  compareBoxLabel: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      11,
    letterSpacing: 1.2,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.35)",
    marginBottom:  6,
  },
  compareBoxNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   44,
    fontWeight: "700" as const,
    color:      "#FFFFFF",
    lineHeight: 46,
  },
  compareBoxNumHighlight: { color: "#E85D2A" },
  compareBoxDenom: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    color:      "rgba(255,255,255,0.30)",
    marginTop:  2,
  },
  compareArrow: {
    fontSize: 20,
    color:    "rgba(255,255,255,0.22)",
  },
  compareDelta: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   14,
    color:      "#E85D2A",
    textAlign:  "center",
    lineHeight: 22,
  },
  compareDeltaNeutral: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   14,
    color:      "rgba(255,255,255,0.35)",
    textAlign:  "center",
    lineHeight: 22,
  },

  // ── Second-attempt motivational CTA ─────────────────────────────────────────
  ctaHook: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     24,
    fontWeight:   "600" as const,
    color:        "#FFFFFF",
    textAlign:    "center",
    lineHeight:   32,
    marginBottom: 22,
    maxWidth:     340,
  },
  resultBtnRow: {
    flexDirection:  "row",
    gap:            12,
    justifyContent: "center",
    flexWrap:       "wrap" as any,
  },
});
