import { createWebStyles } from "../../styles/web";
import { P } from "../../styles/tokens";

// ── MEMORY TEST ───────────────────────────────────────────────────────────────
export const test = createWebStyles({
  section: {
    paddingVertical:   100,
    paddingHorizontal: 56,
    backgroundColor:   P.green,
  },
  inner: {
    maxWidth:         860,
    marginHorizontal: "auto" as any,
    width:            "100%" as any,
  },
  head: {
    alignItems:   "center",
    marginBottom: 52,
  },
  eyebrow: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      13,
    fontWeight:    "500" as const,
    letterSpacing: 1.5,
    textTransform: "uppercase" as any,
    color:         P.gold,
    marginBottom:  14,
  },
  h2: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      50,
    fontWeight:    "600" as const,
    color:         P.white,
    letterSpacing: -1.0,
    textAlign:     "center",
  },
  subText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   16,
    color:      "rgba(255,255,255,0.45)",
    marginTop:  14,
    maxWidth:   440,
    textAlign:  "center",
    lineHeight: 27,
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.09)",
    borderRadius:    22,
    padding:         40,
    alignItems:      "center",
  },
  phaseTitle: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     32,
    fontWeight:   "600" as const,
    color:        P.white,
    marginBottom: 10,
    textAlign:    "center",
  },
  phaseText: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     15,
    color:        "rgba(255,255,255,0.45)",
    marginBottom: 32,
    textAlign:    "center",
    lineHeight:   26,
  },
  digitRow: {
    flexDirection:  "row",
    justifyContent: "center",
    gap:            10,
    marginBottom:   30,
  },
  digitBox: {
    width:           54,
    height:          68,
    borderRadius:    11,
    backgroundColor: "rgba(255,255,255,0.10)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.18)",
    alignItems:      "center",
    justifyContent:  "center",
  },
  digitText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   38,
    fontWeight: "600" as const,
    color:      P.white,
  },
  countdown: {
    width:           54,
    height:          54,
    borderRadius:    999,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth:     2,
    borderColor:     P.gold,
    alignItems:      "center",
    justifyContent:  "center",
    alignSelf:       "center",
  },
  countdownNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   26,
    fontWeight: "600" as const,
    color:      P.gold,
  },
  recallDigitBox: {
    width:           54,
    height:          68,
    borderRadius:    11,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.09)",
    alignItems:      "center",
    justifyContent:  "center",
  },
  eyebrowGold: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      15,
    letterSpacing: 1.0,
    textTransform: "uppercase" as any,
    color:         P.gold,
    marginBottom:  22,
    textAlign:     "center",
  },
  chunkBox: {
    backgroundColor:   "rgba(255,255,255,0.05)",
    borderRadius:      14,
    padding:           24,
    maxWidth:          460,
    alignSelf:         "center",
    marginBottom:      28,
    width:             "100%" as any,
  },
  chunkText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   15,
    color:      "rgba(255,255,255,0.65)",
    lineHeight: 26,
  },
  chunkRow: {
    flexDirection:  "row",
    justifyContent: "center",
    gap:            14,
    marginTop:      18,
  },
  chunkPill: {
    backgroundColor:   "rgba(255,255,255,0.09)",
    borderRadius:      9,
    paddingHorizontal: 17,
    paddingVertical:   9,
  },
  chunkPillText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   28,
    fontWeight: "600" as const,
    color:      P.gold,
  },
  chunkNote: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    color:      "rgba(255,255,255,0.35)",
    marginTop:  10,
    textAlign:  "center",
  },
  resultScoreRow: {
    flexDirection:  "row",
    justifyContent: "center",
    gap:            44,
    marginBottom:   36,
  },
  resultScoreItem: {
    alignItems: "center",
  },
  resultScoreLabel: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      13,
    letterSpacing: 1.0,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.35)",
    marginBottom:  10,
  },
  resultCircle: {
    width:          96,
    height:         96,
    borderRadius:   999,
    alignItems:     "center",
    justifyContent: "center",
    marginBottom:   10,
    borderWidth:    2,
  },
  resultCircleNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   34,
    fontWeight: "700" as const,
  },
  resultCircleSub: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    color:      "rgba(255,255,255,0.40)",
  },
  improvementBadge: {
    backgroundColor:   "rgba(255,255,255,0.05)",
    borderRadius:      10,
    paddingHorizontal: 22,
    paddingVertical:   12,
    marginBottom:      28,
    alignSelf:         "center",
  },
  improvementText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   14,
    color:      P.gold,
  },
  resultNote: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     14,
    color:        "rgba(255,255,255,0.40)",
    marginBottom: 28,
    textAlign:    "center",
  },
  btn: {
    borderRadius:      999,
    paddingHorizontal: 32,
    paddingVertical:   13,
    cursor:            "pointer" as any,
    transition:        "transform 0.2s" as any,
  },
  btnPrimary:     { backgroundColor: P.gold },
  btnPrimaryText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   15,
    fontWeight: "600" as const,
    color:      "#FFFFFF",
  },
  btnSecondary: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.15)",
  },
  btnSecondaryText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   15,
    color:      "rgba(255,255,255,0.60)",
  },
  scoreBadge: {
    backgroundColor:   P.gold,
    borderRadius:      999,
    paddingHorizontal: 16,
    paddingVertical:   6,
    marginBottom:      22,
    alignSelf:         "center",
  },
  scoreBadgeText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    fontWeight: "600" as const,
    color:      "#FFFFFF",
  },
  emojiIcon: {
    fontSize:     60,
    marginBottom: 20,
    textAlign:    "center",
  },

  // ── Phase wrappers ──────────────────────────────────────────────────────────
  phaseWrap: { alignItems: "center", width: "100%" as any },

  // ── Recall digit character ──────────────────────────────────────────────────
  recallCharText:  { fontFamily: "Cormorant Garamond, Georgia, serif" as any, fontSize: 34, fontWeight: "600" as const, color: "#FFFFFF" },
  recallCharEmpty: { color: "rgba(255,255,255,0.18)" },

  // ── Inline emphasis (nested Text children) ──────────────────────────────────
  emphasis:     { color: "#E85D2A", fontStyle: "italic" },
  emphasisBold: { color: "#E85D2A", fontWeight: "700" as const },

  // ── Result circle variants ──────────────────────────────────────────────────
  resultCircleDefault:   { backgroundColor: "rgba(255,255,255,0.08)", borderColor: "rgba(255,255,255,0.12)" },
  resultCircleHighlight: { backgroundColor: "#E85D2A",                borderColor: "#E85D2A" },
  resultNumDefault:      { color: "#FFFFFF" },
  resultNumHighlight:    { color: "#FFFFFF" },

  // ── Word memory test — show phase ───────────────────────────────────────────
  wordTimerTrack: {
    width:           300,
    height:          3,
    borderRadius:    2,
    backgroundColor: "rgba(255,255,255,0.10)",
    marginBottom:    36,
    overflow:        "hidden",
  },
  wordTimerFill: {
    height:          "100%" as any,
    backgroundColor: "#E85D2A",
    borderRadius:    2,
    transition:      "width 1s linear" as any,
  },
  wordBig: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      76,
    fontWeight:    "600" as const,
    color:         "#FFFFFF",
    letterSpacing: -1.5,
    textAlign:     "center",
    marginVertical: 8,
  },
  wordCounter: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      16,
    color:         "rgba(255,255,255,0.40)",
    letterSpacing: 1.0,
    marginTop:     12,
  },

  // ── Word memory test — recall grid ──────────────────────────────────────────
  inputGrid: {
    display:             "grid" as any,
    gridTemplateColumns: "repeat(4, 1fr)" as any,
    gap:                 8,
    width:               "100%" as any,
    maxWidth:            520,
    marginBottom:        24,
  },

  // ── Word memory test — result phase ─────────────────────────────────────────
  scoreRow: {
    flexDirection:  "row",
    alignItems:     "flex-end",
    justifyContent: "center",
    gap:            4,
    marginBottom:   10,
  },
  scoreNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   84,
    fontWeight: "700" as const,
    color:      "#E85D2A",
    lineHeight: 84,
  },
  scoreDenom: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     36,
    color:        "rgba(255,255,255,0.30)",
    paddingBottom: 12,
  },
  wordResultGrid: {
    flexDirection:  "row",
    flexWrap:       "wrap" as any,
    justifyContent: "center",
    gap:            6,
    maxWidth:       540,
    marginBottom:   24,
  },
  wordResultChip: {
    borderRadius:      8,
    paddingHorizontal: 11,
    paddingVertical:   6,
    borderWidth:       1,
  },
  wordResultHit:  { backgroundColor: "rgba(232,93,42,0.12)", borderColor: "rgba(232,93,42,0.40)" },
  wordResultMiss: { backgroundColor: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.09)" },
  wordResultText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   15,
    fontWeight: "500" as const,
  },
  wordResultTextHit:  { color: "#E85D2A" },
  wordResultTextMiss: { color: "rgba(255,255,255,0.30)" },

  // ── Technique tip box ────────────────────────────────────────────────────────
  tipIntro: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     18,
    fontWeight:   "600" as const,
    color:        "#FFFFFF",
    textAlign:    "center",
    marginBottom: 14,
    maxWidth:     420,
  },
  tipBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth:     1,
    borderColor:     "rgba(232,93,42,0.20)",
    borderRadius:    14,
    padding:         22,
    maxWidth:        480,
    width:           "100%" as any,
    marginBottom:    24,
    gap:             8,
  },

  // ── Score comparison (second attempt+) ─────────────────────────────────────
  compareWrap: {
    width:           "100%" as any,
    maxWidth:        400,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius:    16,
    paddingVertical: 20,
    paddingHorizontal: 24,
    marginTop:       4,
    marginBottom:    24,
    alignItems:      "center",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.07)",
  },
  compareScoreRow: {
    flexDirection:  "row",
    alignItems:     "center",
    justifyContent: "center",
    gap:            16,
    marginBottom:   12,
  },
  compareBox: {
    alignItems:        "center",
    backgroundColor:   "rgba(255,255,255,0.06)",
    borderRadius:      12,
    paddingHorizontal: 22,
    paddingVertical:   14,
    borderWidth:       1,
    borderColor:       "rgba(255,255,255,0.08)",
    minWidth:          96,
  },
  compareBoxActive: {
    backgroundColor: "rgba(232,93,42,0.12)",
    borderColor:     "rgba(232,93,42,0.35)",
  },
  compareBoxLabel: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      11,
    letterSpacing: 1.2,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.35)",
    marginBottom:  6,
  },
  compareBoxNum: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   44,
    fontWeight: "700" as const,
    color:      "#FFFFFF",
    lineHeight: 46,
  },
  compareBoxNumHighlight: { color: "#E85D2A" },
  compareBoxDenom: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    color:      "rgba(255,255,255,0.30)",
    marginTop:  2,
  },
  compareArrow: {
    fontSize: 20,
    color:    "rgba(255,255,255,0.22)",
  },
  compareDelta: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   14,
    color:      "#E85D2A",
    textAlign:  "center",
    lineHeight: 22,
  },
  compareDeltaNeutral: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   14,
    color:      "rgba(255,255,255,0.35)",
    textAlign:  "center",
    lineHeight: 22,
  },

  // ── Second-attempt motivational CTA ─────────────────────────────────────────
  ctaHook: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     24,
    fontWeight:   "600" as const,
    color:        "#FFFFFF",
    textAlign:    "center",
    lineHeight:   32,
    marginBottom: 22,
    maxWidth:     340,
  },
  resultBtnRow: {
    flexDirection:  "row",
    gap:            12,
    justifyContent: "center",
    flexWrap:       "wrap" as any,
  },
});
