import { createWebStyles } from "../../styles/web";
import { INNER_W, P } from "../../styles/tokens";

// ── TECHNIQUES / VAULT ────────────────────────────────────────────────────────
export const vault = createWebStyles({
  section: {
    paddingVertical:   100,
    paddingHorizontal: 56,
    backgroundColor:   P.cream,
  },
  inner: {
    ...INNER_W,
    display:             "grid" as any,
    gridTemplateColumns: "1fr 1.2fr" as any,
    gap:                 72,
    alignItems:          "start" as any,
  },
  eyebrow: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      13,
    fontWeight:    "500" as const,
    letterSpacing: 1.5,
    textTransform: "uppercase" as any,
    color:         P.amber,
    marginBottom:  14,
  },
  h2: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      50,
    fontWeight:    "600" as const,
    color:         P.green,
    letterSpacing: -1.0,
    lineHeight:    56,
    marginBottom:  18,
  },
  subText: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     16,
    color:        P.textMid,
    lineHeight:   27,
    marginBottom: 36,
  },
  tabList: {
    flexDirection: "column",
    gap:           9,
  },
  tab: {
    flexDirection:     "row",
    alignItems:        "center",
    gap:               14,
    paddingHorizontal: 18,
    paddingVertical:   14,
    borderRadius:      13,
    borderWidth:       1,
    cursor:            "pointer" as any,
    transition:        "all 0.2s" as any,
  },
  tabDot: {
    width:        7,
    height:       7,
    borderRadius: 999,
  },
  tabCat: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      12,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    marginBottom:  2,
  },
  tabTitle: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   17,
    fontWeight: "600" as const,
  },
  detailCard: {
    borderRadius: 22,
    padding:      44,
    boxShadow:    "0 20px 56px rgba(0,0,0,0.20)" as any,
  },
  detailCat: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      12,
    letterSpacing: 1.0,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.45)",
    marginBottom:  14,
  },
  detailTitle: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     34,
    fontWeight:   "600" as const,
    color:        P.white,
    marginBottom: 18,
    lineHeight:   40,
  },
  detailDesc: {
    fontFamily:   "Cormorant Garamond, Georgia, serif" as any,
    fontSize:     15,
    color:        "rgba(255,255,255,0.65)",
    lineHeight:   26,
    marginBottom: 28,
  },
  exampleBox: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth:     1,
    borderColor:     "rgba(255,255,255,0.10)",
    borderRadius:    13,
    padding:         22,
  },
  exampleLabel: {
    fontFamily:    "Cormorant Garamond, Georgia, serif" as any,
    fontSize:      12,
    letterSpacing: 0.8,
    textTransform: "uppercase" as any,
    color:         "rgba(255,255,255,0.35)",
    marginBottom:  8,
  },
  exampleText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   19,
    color:      P.gold,
    lineHeight: 28,
    fontStyle:  "italic",
  },
  detailFooter: {
    marginTop:     28,
    flexDirection: "row",
    alignItems:    "center",
    gap:           9,
  },
  detailFooterIcon: {
    width:           30,
    height:          30,
    borderRadius:    999,
    backgroundColor: "rgba(255,255,255,0.10)",
    alignItems:      "center",
    justifyContent:  "center",
  },
  detailFooterText: {
    fontFamily: "Cormorant Garamond, Georgia, serif" as any,
    fontSize:   13,
    color:      "rgba(255,255,255,0.42)",
  },
  checkIconText: { fontSize: 13, color: "#FFFFFF" },

  // ── Technique detail card backgrounds (one per technique, index-matched) ────
  detailCardBg0: { backgroundColor: "#121212" },
  detailCardBg1: { backgroundColor: "#1A1A1A" },
  detailCardBg2: { backgroundColor: "#161616" },
  detailCardBg3: { backgroundColor: "#1E1E1E" },

  // ── Tab active / inactive state variants ────────────────────────────────────
  tabActive:        { backgroundColor: "#121212", borderColor: "#121212" },
  tabInactive:      { backgroundColor: "#FFFFFF", borderColor: "#DADADA" },
  tabDotActive:     { backgroundColor: "#E85D2A" },
  tabDotInactive:   { backgroundColor: "#DADADA" },
  tabCatActive:     { color: "#E85D2A" },
  tabCatInactive:   { color: "#9E9E9E" },
  tabTitleActive:   { color: "#FFFFFF" },
  tabTitleInactive: { color: "#121212" },
});
